

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\buffer_sp_files\drive

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7916 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.20E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.24E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.24E-01                                  

 init: end check errors, cpu clock= 1.26E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.26E-01                     

       establish matrix -- done, cpu clock= 1.26E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.27E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.27E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.27E-01                                          

 dcop: end dcop, cpu clock= 1.30E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  5.00E-09 #sweeps=5001 cpu clock= 1.31E-01 

 tran: time= 5.0364E-10 tot_iter=      62 conv_iter=      24 cpu clock= 1.33E-01

 tran: time= 1.0373E-09 tot_iter=      86 conv_iter=      33 cpu clock= 1.34E-01

 tran: time= 1.5597E-09 tot_iter=     109 conv_iter=      42 cpu clock= 1.34E-01

 tran: time= 2.0782E-09 tot_iter=     124 conv_iter=      48 cpu clock= 1.35E-01

 tran: time= 2.7210E-09 tot_iter=     132 conv_iter=      52 cpu clock= 1.35E-01

 tran: time= 3.2210E-09 tot_iter=     136 conv_iter=      54 cpu clock= 1.35E-01

 tran: time= 3.7210E-09 tot_iter=     140 conv_iter=      56 cpu clock= 1.35E-01

 tran: time= 4.2210E-09 tot_iter=     144 conv_iter=      58 cpu clock= 1.35E-01

 tran: time= 4.7210E-09 tot_iter=     148 conv_iter=      60 cpu clock= 1.36E-01

 tran: time= 5.0000E-09 tot_iter=     152 conv_iter=      62 cpu clock= 1.36E-01

 sweep: tran tran0    end, cpu clock= 1.36E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.15 seconds                           

           job started at     14:36:43 12/06/2025                               

           job ended   at     14:36:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\buffer_sp_files\drive

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  5.00E-09 #sweeps=5001 cpu clock= 1.05E-01 

 tran: time= 5.0364E-10 tot_iter=      62 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 1.0373E-09 tot_iter=      86 conv_iter=      33 cpu clock= 1.08E-01

 tran: time= 1.5597E-09 tot_iter=     109 conv_iter=      42 cpu clock= 1.08E-01

 tran: time= 2.0782E-09 tot_iter=     124 conv_iter=      48 cpu clock= 1.08E-01

 tran: time= 2.7210E-09 tot_iter=     132 conv_iter=      52 cpu clock= 1.09E-01

 tran: time= 3.2210E-09 tot_iter=     136 conv_iter=      54 cpu clock= 1.09E-01

 tran: time= 3.7210E-09 tot_iter=     140 conv_iter=      56 cpu clock= 1.09E-01

 tran: time= 4.2210E-09 tot_iter=     144 conv_iter=      58 cpu clock= 1.09E-01

 tran: time= 4.7210E-09 tot_iter=     148 conv_iter=      60 cpu clock= 1.09E-01

 tran: time= 5.0000E-09 tot_iter=     152 conv_iter=      62 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     14:36:46 12/06/2025                               

           job ended   at     14:36:46 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
