

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\buffer_sp_files\drive

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12880 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=      18  

 sweep: tran tran0    begin, stop_t=  5.00E-09 #sweeps=5001 cpu clock= 1.14E-01 

 tran: time= 5.2495E-10 tot_iter=      62 conv_iter=      25 cpu clock= 1.15E-01

 tran: time= 1.0321E-09 tot_iter=      84 conv_iter=      33 cpu clock= 1.16E-01

 tran: time= 1.5384E-09 tot_iter=     101 conv_iter=      40 cpu clock= 1.16E-01

 tran: time= 2.0330E-09 tot_iter=     115 conv_iter=      45 cpu clock= 1.17E-01

 tran: time= 2.6099E-09 tot_iter=     125 conv_iter=      50 cpu clock= 1.17E-01

 tran: time= 3.1011E-09 tot_iter=     129 conv_iter=      52 cpu clock= 1.17E-01

 tran: time= 3.6011E-09 tot_iter=     133 conv_iter=      54 cpu clock= 1.17E-01

 tran: time= 4.1011E-09 tot_iter=     137 conv_iter=      56 cpu clock= 1.17E-01

 tran: time= 4.6011E-09 tot_iter=     141 conv_iter=      58 cpu clock= 1.18E-01

 tran: time= 5.0000E-09 tot_iter=     145 conv_iter=      60 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     14:36:39 12/06/2025                               

           job ended   at     14:36:39 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
