

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\buffer_sp_files\drive

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6428 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.12E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.16E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.16E-01                                  

 init: end check errors, cpu clock= 1.19E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.19E-01                     

       establish matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.19E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.20E-01                                          

 dcop: end dcop, cpu clock= 1.22E-01 peak memory=      72 mb tot_iter=      22  

 sweep: tran tran0    begin, stop_t=  5.00E-09 #sweeps=5001 cpu clock= 1.24E-01 

 tran: time= 5.1564E-10 tot_iter=      75 conv_iter=      28 cpu clock= 1.26E-01

 tran: time= 1.0684E-09 tot_iter=      99 conv_iter=      37 cpu clock= 1.26E-01

 tran: time= 1.5385E-09 tot_iter=     113 conv_iter=      43 cpu clock= 1.27E-01

 tran: time= 2.0438E-09 tot_iter=     132 conv_iter=      50 cpu clock= 1.27E-01

 tran: time= 2.5287E-09 tot_iter=     146 conv_iter=      57 cpu clock= 1.27E-01

 tran: time= 3.0186E-09 tot_iter=     154 conv_iter=      61 cpu clock= 1.28E-01

 tran: time= 3.6703E-09 tot_iter=     160 conv_iter=      64 cpu clock= 1.28E-01

 tran: time= 4.1703E-09 tot_iter=     164 conv_iter=      66 cpu clock= 1.28E-01

 tran: time= 4.6703E-09 tot_iter=     168 conv_iter=      68 cpu clock= 1.28E-01

 tran: time= 5.0000E-09 tot_iter=     172 conv_iter=      70 cpu clock= 1.28E-01

 sweep: tran tran0    end, cpu clock= 1.28E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     14:36:47 12/06/2025                               

           job ended   at     14:36:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\buffer_sp_files\drive

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17984 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      22  

 sweep: tran tran0    begin, stop_t=  5.00E-09 #sweeps=5001 cpu clock= 1.08E-01 

 tran: time= 5.1564E-10 tot_iter=      75 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 1.0684E-09 tot_iter=      99 conv_iter=      37 cpu clock= 1.11E-01

 tran: time= 1.5385E-09 tot_iter=     113 conv_iter=      43 cpu clock= 1.11E-01

 tran: time= 2.0438E-09 tot_iter=     132 conv_iter=      50 cpu clock= 1.12E-01

 tran: time= 2.5287E-09 tot_iter=     146 conv_iter=      57 cpu clock= 1.12E-01

 tran: time= 3.0186E-09 tot_iter=     154 conv_iter=      61 cpu clock= 1.12E-01

 tran: time= 3.6703E-09 tot_iter=     160 conv_iter=      64 cpu clock= 1.12E-01

 tran: time= 4.1703E-09 tot_iter=     164 conv_iter=      66 cpu clock= 1.12E-01

 tran: time= 4.6703E-09 tot_iter=     168 conv_iter=      68 cpu clock= 1.13E-01

 tran: time= 5.0000E-09 tot_iter=     172 conv_iter=      70 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     14:36:51 12/06/2025                               

           job ended   at     14:36:51 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
