

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10456 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.70E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.71E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.72E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.72E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.72E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.72E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.73E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.73E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.73E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:49 12/01/2025                               

           job ended   at     23:08:49 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14780 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.68E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.69E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.70E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.70E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.71E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.71E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.71E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.71E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.71E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:52 12/01/2025                               

           job ended   at     23:08:52 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9324 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.70E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.72E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     11:49:59 12/02/2025                               

           job ended   at     11:49:59 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14116 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.30E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.37E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.37E-01                                  

 init: end check errors, cpu clock= 2.44E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.44E-01                     

       establish matrix -- done, cpu clock= 2.45E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.45E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.46E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.47E-01                                          

 dcop: end dcop, cpu clock= 2.48E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.50E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.52E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.53E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.54E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.54E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.54E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.54E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.54E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.54E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.54E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.54E-01

 sweep: tran tran0    end, cpu clock= 2.54E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     11:50:02 12/02/2025                               

           job ended   at     11:50:02 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21468 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.74E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.76E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.80E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.82E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.82E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.82E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.82E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.82E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.82E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.82E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:09:14 12/06/2025                               

           job ended   at     00:09:14 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12228 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.70E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:17 12/06/2025                               

           job ended   at     00:09:18 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12568 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.50E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.50E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.60E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.60E-01                                          

 dcop: end dcop, cpu clock= 2.62E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.64E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.65E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.67E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.67E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.67E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.68E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.68E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.68E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.68E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.68E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.68E-01

 sweep: tran tran0    end, cpu clock= 2.68E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:39 12/06/2025                               

           job ended   at     00:21:40 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16348 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.40E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.47E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.47E-01                                  

 init: end check errors, cpu clock= 2.54E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.54E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.56E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.56E-01                                          

 dcop: end dcop, cpu clock= 2.57E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.59E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.61E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.63E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.63E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.63E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.63E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.63E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.63E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.63E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.63E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.63E-01

 sweep: tran tran0    end, cpu clock= 2.63E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:43 12/06/2025                               

           job ended   at     00:21:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20040 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.50E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.50E-01                                  

 init: end check errors, cpu clock= 2.57E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.57E-01                     

       establish matrix -- done, cpu clock= 2.57E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.59E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.61E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.63E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.64E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.66E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.66E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.66E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.66E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.67E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.67E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.67E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.67E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.67E-01

 sweep: tran tran0    end, cpu clock= 2.67E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:39 12/06/2025                               

           job ended   at     00:29:40 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7320 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.70E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.70E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.70E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.70E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:43 12/06/2025                               

           job ended   at     00:29:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14360 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.69E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.69E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.70E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.70E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.70E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.70E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.70E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:30:39 12/06/2025                               

           job ended   at     00:30:39 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13872 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.72E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.74E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.75E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.75E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:42 12/06/2025                               

           job ended   at     00:30:42 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20084 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.79E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.81E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.82E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.83E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.83E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.83E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.83E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.83E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.83E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.83E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:18 12/06/2025                               

           job ended   at     00:46:18 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11612 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.71E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:46:20 12/06/2025                               

           job ended   at     00:46:21 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15548 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.56E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.62E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.62E-01                                  

 init: end check errors, cpu clock= 2.70E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.70E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.73E-01                                          

 dcop: end dcop, cpu clock= 2.74E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.76E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.78E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.80E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.80E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.80E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.80E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.80E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.80E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.80E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:49:20 12/06/2025                               

           job ended   at     00:49:21 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19700 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.71E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:23 12/06/2025                               

           job ended   at     00:49:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2040 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.70E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.70E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.70E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.70E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.70E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.70E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:00 12/06/2025                               

           job ended   at     00:53:01 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13968 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.72E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:03 12/06/2025                               

           job ended   at     00:53:03 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14680 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.67E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.67E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.77E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.77E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.77E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:22 12/06/2025                               

           job ended   at     00:55:22 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20316 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.71E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.72E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.74E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.74E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.74E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:25 12/06/2025                               

           job ended   at     00:55:25 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12488 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.72E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:22 12/06/2025                               

           job ended   at     00:56:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8840 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.71E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.73E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.75E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.75E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.75E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:25 12/06/2025                               

           job ended   at     00:56:25 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.73E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.75E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.75E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.76E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.76E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.76E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.76E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.76E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:36 12/06/2025                               

           job ended   at     01:01:37 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21352 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      75 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      75 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.73E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:39 12/06/2025                               

           job ended   at     01:01:39 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3704 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.77E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.77E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.77E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:33 12/06/2025                               

           job ended   at     01:20:34 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7584 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\a00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4351E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.71E-01

 tran: time= 5.2957E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.9433E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.6433E-10 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0343E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.2043E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3743E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5443E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      90 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:37 12/06/2025                               

           job ended   at     01:20:37 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
