

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21244 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.69E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.69E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.78E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.78E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.79E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.80E-01                                          

 dcop: end dcop, cpu clock= 2.83E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.85E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.87E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.88E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.89E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.89E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.89E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.89E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.89E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.89E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.89E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.89E-01

 sweep: tran tran0    end, cpu clock= 2.89E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     18:56:52 12/01/2025                               

           job ended   at     18:56:52 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13356 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.49E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.49E-01                                  

 init: end check errors, cpu clock= 2.57E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.57E-01                     

       establish matrix -- done, cpu clock= 2.57E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.57E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.59E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.61E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.63E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.65E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.66E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.67E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.67E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.67E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.67E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.67E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.67E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.67E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.67E-01

 sweep: tran tran0    end, cpu clock= 2.67E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     18:56:55 12/01/2025                               

           job ended   at     18:56:55 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14444 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.60E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.62E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.65E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.66E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.68E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.68E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.68E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.68E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.69E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.69E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.69E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     19:25:06 12/01/2025                               

           job ended   at     19:25:07 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8628 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.40E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.46E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.46E-01                                  

 init: end check errors, cpu clock= 2.54E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.54E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.56E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.56E-01                                          

 dcop: end dcop, cpu clock= 2.58E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.59E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.61E-01

 tran: time= 3.4939E-10 tot_iter=     116 conv_iter=      41 cpu clock= 2.62E-01

 tran: time= 5.1235E-10 tot_iter=     129 conv_iter=      47 cpu clock= 2.62E-01

 tran: time= 7.4835E-10 tot_iter=     135 conv_iter=      50 cpu clock= 2.62E-01

 tran: time= 9.1835E-10 tot_iter=     139 conv_iter=      52 cpu clock= 2.62E-01

 tran: time= 1.0884E-09 tot_iter=     143 conv_iter=      54 cpu clock= 2.62E-01

 tran: time= 1.2584E-09 tot_iter=     147 conv_iter=      56 cpu clock= 2.62E-01

 tran: time= 1.4284E-09 tot_iter=     151 conv_iter=      58 cpu clock= 2.63E-01

 tran: time= 1.5984E-09 tot_iter=     155 conv_iter=      60 cpu clock= 2.63E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.63E-01

 sweep: tran tran0    end, cpu clock= 2.63E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.26 seconds                           

           job started at     19:25:09 12/01/2025                               

           job ended   at     19:25:10 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
