

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8904 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.71E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.73E-01

 tran: time= 3.4181E-10 tot_iter=     117 conv_iter=      41 cpu clock= 2.75E-01

 tran: time= 5.2714E-10 tot_iter=     133 conv_iter=      48 cpu clock= 2.75E-01

 tran: time= 6.8463E-10 tot_iter=     137 conv_iter=      50 cpu clock= 2.75E-01

 tran: time= 8.5463E-10 tot_iter=     141 conv_iter=      52 cpu clock= 2.75E-01

 tran: time= 1.0246E-09 tot_iter=     145 conv_iter=      54 cpu clock= 2.76E-01

 tran: time= 1.1946E-09 tot_iter=     149 conv_iter=      56 cpu clock= 2.76E-01

 tran: time= 1.3646E-09 tot_iter=     153 conv_iter=      58 cpu clock= 2.76E-01

 tran: time= 1.5346E-09 tot_iter=     157 conv_iter=      60 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      62 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     18:56:53 12/01/2025                               

           job ended   at     18:56:53 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19460 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.59E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.59E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.66E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.67E-01

 tran: time= 3.4181E-10 tot_iter=     117 conv_iter=      41 cpu clock= 2.69E-01

 tran: time= 5.2714E-10 tot_iter=     133 conv_iter=      48 cpu clock= 2.70E-01

 tran: time= 6.8463E-10 tot_iter=     137 conv_iter=      50 cpu clock= 2.70E-01

 tran: time= 8.5463E-10 tot_iter=     141 conv_iter=      52 cpu clock= 2.70E-01

 tran: time= 1.0246E-09 tot_iter=     145 conv_iter=      54 cpu clock= 2.70E-01

 tran: time= 1.1946E-09 tot_iter=     149 conv_iter=      56 cpu clock= 2.70E-01

 tran: time= 1.3646E-09 tot_iter=     153 conv_iter=      58 cpu clock= 2.70E-01

 tran: time= 1.5346E-09 tot_iter=     157 conv_iter=      60 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      62 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     18:56:56 12/01/2025                               

           job ended   at     18:56:56 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14360 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.60E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.60E-01                                          

 dcop: end dcop, cpu clock= 2.62E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.64E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.65E-01

 tran: time= 3.4181E-10 tot_iter=     117 conv_iter=      41 cpu clock= 2.66E-01

 tran: time= 5.2714E-10 tot_iter=     133 conv_iter=      48 cpu clock= 2.67E-01

 tran: time= 6.8463E-10 tot_iter=     137 conv_iter=      50 cpu clock= 2.67E-01

 tran: time= 8.5463E-10 tot_iter=     141 conv_iter=      52 cpu clock= 2.67E-01

 tran: time= 1.0246E-09 tot_iter=     145 conv_iter=      54 cpu clock= 2.67E-01

 tran: time= 1.1946E-09 tot_iter=     149 conv_iter=      56 cpu clock= 2.67E-01

 tran: time= 1.3646E-09 tot_iter=     153 conv_iter=      58 cpu clock= 2.67E-01

 tran: time= 1.5346E-09 tot_iter=     157 conv_iter=      60 cpu clock= 2.67E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      62 cpu clock= 2.67E-01

 sweep: tran tran0    end, cpu clock= 2.67E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     19:25:08 12/01/2025                               

           job ended   at     19:25:08 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18592 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\a01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.70E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.72E-01

 tran: time= 3.4181E-10 tot_iter=     117 conv_iter=      41 cpu clock= 2.73E-01

 tran: time= 5.2714E-10 tot_iter=     133 conv_iter=      48 cpu clock= 2.73E-01

 tran: time= 6.8463E-10 tot_iter=     137 conv_iter=      50 cpu clock= 2.73E-01

 tran: time= 8.5463E-10 tot_iter=     141 conv_iter=      52 cpu clock= 2.73E-01

 tran: time= 1.0246E-09 tot_iter=     145 conv_iter=      54 cpu clock= 2.74E-01

 tran: time= 1.1946E-09 tot_iter=     149 conv_iter=      56 cpu clock= 2.74E-01

 tran: time= 1.3646E-09 tot_iter=     153 conv_iter=      58 cpu clock= 2.74E-01

 tran: time= 1.5346E-09 tot_iter=     157 conv_iter=      60 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      62 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     19:25:11 12/01/2025                               

           job ended   at     19:25:11 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
