

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11972 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.63E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.63E-01                                  

 init: end check errors, cpu clock= 2.70E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.70E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.72E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.77E-01 

 tran: time= 1.7715E-10 tot_iter=      58 conv_iter=      22 cpu clock= 2.79E-01

 tran: time= 3.5512E-10 tot_iter=     112 conv_iter=      40 cpu clock= 2.80E-01

 tran: time= 5.3239E-10 tot_iter=     128 conv_iter=      47 cpu clock= 2.80E-01

 tran: time= 6.8539E-10 tot_iter=     132 conv_iter=      49 cpu clock= 2.80E-01

 tran: time= 8.5539E-10 tot_iter=     136 conv_iter=      51 cpu clock= 2.80E-01

 tran: time= 1.0254E-09 tot_iter=     140 conv_iter=      53 cpu clock= 2.80E-01

 tran: time= 1.1954E-09 tot_iter=     144 conv_iter=      55 cpu clock= 2.80E-01

 tran: time= 1.3654E-09 tot_iter=     148 conv_iter=      57 cpu clock= 2.80E-01

 tran: time= 1.5354E-09 tot_iter=     152 conv_iter=      59 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     156 conv_iter=      61 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:49 12/01/2025                               

           job ended   at     23:08:50 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15848 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.52E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.67E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.67E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.72E-01 

 tran: time= 1.7715E-10 tot_iter=      58 conv_iter=      22 cpu clock= 2.74E-01

 tran: time= 3.5512E-10 tot_iter=     112 conv_iter=      40 cpu clock= 2.75E-01

 tran: time= 5.3239E-10 tot_iter=     128 conv_iter=      47 cpu clock= 2.75E-01

 tran: time= 6.8539E-10 tot_iter=     132 conv_iter=      49 cpu clock= 2.75E-01

 tran: time= 8.5539E-10 tot_iter=     136 conv_iter=      51 cpu clock= 2.75E-01

 tran: time= 1.0254E-09 tot_iter=     140 conv_iter=      53 cpu clock= 2.75E-01

 tran: time= 1.1954E-09 tot_iter=     144 conv_iter=      55 cpu clock= 2.75E-01

 tran: time= 1.3654E-09 tot_iter=     148 conv_iter=      57 cpu clock= 2.75E-01

 tran: time= 1.5354E-09 tot_iter=     152 conv_iter=      59 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     156 conv_iter=      61 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:52 12/01/2025                               

           job ended   at     23:08:52 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
