

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5456 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.73E-01 

 tran: time= 1.7715E-10 tot_iter=      58 conv_iter=      22 cpu clock= 2.74E-01

 tran: time= 3.4960E-10 tot_iter=     115 conv_iter=      41 cpu clock= 2.75E-01

 tran: time= 5.1568E-10 tot_iter=     132 conv_iter=      48 cpu clock= 2.76E-01

 tran: time= 7.5024E-10 tot_iter=     138 conv_iter=      51 cpu clock= 2.76E-01

 tran: time= 9.2024E-10 tot_iter=     142 conv_iter=      53 cpu clock= 2.76E-01

 tran: time= 1.0902E-09 tot_iter=     146 conv_iter=      55 cpu clock= 2.76E-01

 tran: time= 1.2602E-09 tot_iter=     150 conv_iter=      57 cpu clock= 2.76E-01

 tran: time= 1.4302E-09 tot_iter=     154 conv_iter=      59 cpu clock= 2.76E-01

 tran: time= 1.6002E-09 tot_iter=     158 conv_iter=      61 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      63 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:51 12/01/2025                               

           job ended   at     23:08:51 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13572 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.71E-01 

 tran: time= 1.7715E-10 tot_iter=      58 conv_iter=      22 cpu clock= 2.72E-01

 tran: time= 3.4960E-10 tot_iter=     115 conv_iter=      41 cpu clock= 2.73E-01

 tran: time= 5.1568E-10 tot_iter=     132 conv_iter=      48 cpu clock= 2.74E-01

 tran: time= 7.5024E-10 tot_iter=     138 conv_iter=      51 cpu clock= 2.74E-01

 tran: time= 9.2024E-10 tot_iter=     142 conv_iter=      53 cpu clock= 2.74E-01

 tran: time= 1.0902E-09 tot_iter=     146 conv_iter=      55 cpu clock= 2.74E-01

 tran: time= 1.2602E-09 tot_iter=     150 conv_iter=      57 cpu clock= 2.74E-01

 tran: time= 1.4302E-09 tot_iter=     154 conv_iter=      59 cpu clock= 2.74E-01

 tran: time= 1.6002E-09 tot_iter=     158 conv_iter=      61 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      63 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:54 12/01/2025                               

           job ended   at     23:08:54 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14528 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.71E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.71E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.71E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.71E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.72E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.72E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.72E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:50:01 12/02/2025                               

           job ended   at     11:50:01 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18380 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.30E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.37E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.37E-01                                  

 init: end check errors, cpu clock= 2.44E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.44E-01                     

       establish matrix -- done, cpu clock= 2.44E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.44E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.46E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.46E-01                                          

 dcop: end dcop, cpu clock= 2.48E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\b01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.50E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.52E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.54E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.54E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.54E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.55E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.55E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.55E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.55E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.55E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.55E-01

 sweep: tran tran0    end, cpu clock= 2.55E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     11:50:04 12/02/2025                               

           job ended   at     11:50:05 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.70E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.72E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.73E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.73E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.73E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:16 12/06/2025                               

           job ended   at     00:09:16 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9772 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.73E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.73E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.74E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.74E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:21 12/06/2025                               

           job ended   at     00:09:21 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15392 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.60E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.62E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.64E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.66E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.68E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.68E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.68E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.68E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.68E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.68E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.68E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.68E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.68E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:41 12/06/2025                               

           job ended   at     00:21:42 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13684 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.42E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.49E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.49E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.57E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.57E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.60E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.62E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.64E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.65E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.66E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.66E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.66E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.66E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.66E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.66E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.66E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.66E-01

 sweep: tran tran0    end, cpu clock= 2.66E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:45 12/06/2025                               

           job ended   at     00:21:45 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17724 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.40E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.47E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.47E-01                                  

 init: end check errors, cpu clock= 2.54E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.54E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.56E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.57E-01                                          

 dcop: end dcop, cpu clock= 2.58E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.60E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.62E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.63E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.64E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.64E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.64E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.64E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.64E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.64E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.64E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.64E-01

 sweep: tran tran0    end, cpu clock= 2.64E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:42 12/06/2025                               

           job ended   at     00:29:42 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8840 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.93E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.00E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.00E-01                                  

 init: end check errors, cpu clock= 3.07E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.07E-01                     

       establish matrix -- done, cpu clock= 3.07E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.07E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.09E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.09E-01                                          

 dcop: end dcop, cpu clock= 3.10E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.12E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 3.14E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 3.15E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 3.16E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 3.16E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 3.16E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 3.16E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 3.16E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 3.16E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 3.16E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 3.16E-01

 sweep: tran tran0    end, cpu clock= 3.16E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.33 seconds                           

           job started at     00:29:45 12/06/2025                               

           job ended   at     00:29:46 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12456 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.69E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.69E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.69E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.69E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.70E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.70E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.70E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:41 12/06/2025                               

           job ended   at     00:30:41 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15892 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.71E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.71E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.72E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.72E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.72E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.72E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.72E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:44 12/06/2025                               

           job ended   at     00:30:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1068 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.56E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.63E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.63E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.71E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.73E-01                                          

 dcop: end dcop, cpu clock= 2.76E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.80E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.82E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.82E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.82E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.82E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.82E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.82E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.82E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:19 12/06/2025                               

           job ended   at     00:46:20 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13660 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.74E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.76E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.77E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.77E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.77E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.77E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.77E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:46:22 12/06/2025                               

           job ended   at     00:46:22 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15888 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.63E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.63E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.73E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.79E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.80E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.81E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.81E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.81E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.81E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.81E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.81E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.81E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.81E-01

 sweep: tran tran0    end, cpu clock= 2.81E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:49:22 12/06/2025                               

           job ended   at     00:49:22 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19976 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.70E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.70E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.71E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.71E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.71E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.71E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.71E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:25 12/06/2025                               

           job ended   at     00:49:25 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19084 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.76E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.77E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.77E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.77E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.77E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.77E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:02 12/06/2025                               

           job ended   at     00:53:02 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4268 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.61E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.61E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.72E-01                                          

 dcop: end dcop, cpu clock= 2.73E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.76E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.78E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.79E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.80E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.80E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.80E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.80E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.80E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.80E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:53:05 12/06/2025                               

           job ended   at     00:53:05 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18920 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.77E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.77E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.78E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.78E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.78E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.78E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:24 12/06/2025                               

           job ended   at     00:55:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12096 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.72E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.73E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.73E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.73E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:26 12/06/2025                               

           job ended   at     00:55:26 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2664 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.70E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.70E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.70E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.70E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.71E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.71E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.71E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:56:24 12/06/2025                               

           job ended   at     00:56:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13836 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.72E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.73E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.73E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.73E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:27 12/06/2025                               

           job ended   at     00:56:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18876 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.69E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.70E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.70E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.70E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.70E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.70E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.70E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:38 12/06/2025                               

           job ended   at     01:01:38 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12292 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.70E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.71E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.71E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.71E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.71E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.71E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.71E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:40 12/06/2025                               

           job ended   at     01:01:41 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16324 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.64E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.64E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.72E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.74E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.74E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.79E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.80E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.81E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.81E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.81E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.81E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.81E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.81E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.81E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.81E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:36 12/06/2025                               

           job ended   at     01:20:36 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10596 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.64E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.71E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.71E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.79E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.79E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.80E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.81E-01                                          

 dcop: end dcop, cpu clock= 2.82E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\b01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.84E-01 

 tran: time= 1.7472E-10 tot_iter=      88 conv_iter=      36 cpu clock= 2.86E-01

 tran: time= 3.4130E-10 tot_iter=     168 conv_iter=      66 cpu clock= 2.87E-01

 tran: time= 5.6566E-10 tot_iter=     193 conv_iter=      77 cpu clock= 2.88E-01

 tran: time= 7.3566E-10 tot_iter=     197 conv_iter=      79 cpu clock= 2.88E-01

 tran: time= 9.0566E-10 tot_iter=     201 conv_iter=      81 cpu clock= 2.88E-01

 tran: time= 1.0757E-09 tot_iter=     205 conv_iter=      83 cpu clock= 2.88E-01

 tran: time= 1.2457E-09 tot_iter=     209 conv_iter=      85 cpu clock= 2.88E-01

 tran: time= 1.4157E-09 tot_iter=     213 conv_iter=      87 cpu clock= 2.88E-01

 tran: time= 1.5857E-09 tot_iter=     217 conv_iter=      89 cpu clock= 2.88E-01

 tran: time= 1.7000E-09 tot_iter=     221 conv_iter=      91 cpu clock= 2.88E-01

 sweep: tran tran0    end, cpu clock= 2.88E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:40 12/06/2025                               

           job ended   at     01:20:40 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
