

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      756 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.74E-01 

 tran: time= 1.7335E-10 tot_iter=      60 conv_iter=      22 cpu clock= 2.75E-01

 tran: time= 3.4848E-10 tot_iter=     120 conv_iter=      42 cpu clock= 2.76E-01

 tran: time= 5.6208E-10 tot_iter=     132 conv_iter=      48 cpu clock= 2.76E-01

 tran: time= 7.3208E-10 tot_iter=     136 conv_iter=      50 cpu clock= 2.76E-01

 tran: time= 9.0208E-10 tot_iter=     140 conv_iter=      52 cpu clock= 2.76E-01

 tran: time= 1.0721E-09 tot_iter=     144 conv_iter=      54 cpu clock= 2.76E-01

 tran: time= 1.2421E-09 tot_iter=     148 conv_iter=      56 cpu clock= 2.76E-01

 tran: time= 1.4121E-09 tot_iter=     152 conv_iter=      58 cpu clock= 2.77E-01

 tran: time= 1.5821E-09 tot_iter=     156 conv_iter=      60 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     160 conv_iter=      62 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:50 12/01/2025                               

           job ended   at     23:08:50 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18056 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.59E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.59E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.65E-01 

 tran: time= 1.7335E-10 tot_iter=      60 conv_iter=      22 cpu clock= 2.66E-01

 tran: time= 3.4848E-10 tot_iter=     120 conv_iter=      42 cpu clock= 2.68E-01

 tran: time= 5.6208E-10 tot_iter=     132 conv_iter=      48 cpu clock= 2.68E-01

 tran: time= 7.3208E-10 tot_iter=     136 conv_iter=      50 cpu clock= 2.68E-01

 tran: time= 9.0208E-10 tot_iter=     140 conv_iter=      52 cpu clock= 2.68E-01

 tran: time= 1.0721E-09 tot_iter=     144 conv_iter=      54 cpu clock= 2.68E-01

 tran: time= 1.2421E-09 tot_iter=     148 conv_iter=      56 cpu clock= 2.68E-01

 tran: time= 1.4121E-09 tot_iter=     152 conv_iter=      58 cpu clock= 2.68E-01

 tran: time= 1.5821E-09 tot_iter=     156 conv_iter=      60 cpu clock= 2.68E-01

 tran: time= 1.7000E-09 tot_iter=     160 conv_iter=      62 cpu clock= 2.68E-01

 sweep: tran tran0    end, cpu clock= 2.68E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:53 12/01/2025                               

           job ended   at     23:08:53 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12500 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.50E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.50E-01                                  

 init: end check errors, cpu clock= 2.57E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.57E-01                     

       establish matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.59E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.60E-01                                          

 dcop: end dcop, cpu clock= 2.61E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.64E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.70E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.70E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.70E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     11:50:00 12/02/2025                               

           job ended   at     11:50:00 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.27E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.33E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.33E-01                                  

 init: end check errors, cpu clock= 2.41E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.41E-01                     

       establish matrix -- done, cpu clock= 2.41E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.41E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.43E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.43E-01                                          

 dcop: end dcop, cpu clock= 2.45E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\c00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.47E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.48E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.50E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.50E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.50E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.50E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.51E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.51E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.51E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.51E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.51E-01

 sweep: tran tran0    end, cpu clock= 2.51E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     11:50:03 12/02/2025                               

           job ended   at     11:50:04 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21184 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.72E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.73E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:15 12/06/2025                               

           job ended   at     00:09:15 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12180 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.72E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.74E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.74E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.74E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:20 12/06/2025                               

           job ended   at     00:09:20 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.42E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.57E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.62E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.64E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.64E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.64E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.64E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.64E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.65E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.65E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:41 12/06/2025                               

           job ended   at     00:21:41 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9456 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.37E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.44E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.44E-01                                  

 init: end check errors, cpu clock= 2.51E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.51E-01                     

       establish matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.53E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.53E-01                                          

 dcop: end dcop, cpu clock= 2.55E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.57E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.58E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.60E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.60E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.60E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.60E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.61E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.61E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.61E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.61E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.61E-01

 sweep: tran tran0    end, cpu clock= 2.61E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:44 12/06/2025                               

           job ended   at     00:21:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3372 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.50E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.50E-01                                  

 init: end check errors, cpu clock= 2.57E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.57E-01                     

       establish matrix -- done, cpu clock= 2.57E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.59E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.61E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.63E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.65E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.66E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.66E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.67E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.67E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.67E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.67E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.67E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.67E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.67E-01

 sweep: tran tran0    end, cpu clock= 2.67E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:41 12/06/2025                               

           job ended   at     00:29:41 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14076 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.71E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.72E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:29:44 12/06/2025                               

           job ended   at     00:29:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7848 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.71E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:40 12/06/2025                               

           job ended   at     00:30:40 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12104 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.77E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.79E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.80E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.80E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.80E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.80E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.80E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.81E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.81E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.81E-01

 sweep: tran tran0    end, cpu clock= 2.81E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:30:43 12/06/2025                               

           job ended   at     00:30:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13928 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.68E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.76E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.76E-01                                  

 init: end check errors, cpu clock= 2.83E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.83E-01                     

       establish matrix -- done, cpu clock= 2.83E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.83E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.85E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.85E-01                                          

 dcop: end dcop, cpu clock= 2.86E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.89E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.91E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.92E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.92E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.93E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.93E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.93E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.93E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.93E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.93E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.93E-01

 sweep: tran tran0    end, cpu clock= 2.93E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.31 seconds                           

           job started at     00:46:19 12/06/2025                               

           job ended   at     00:46:19 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11296 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.72E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.73E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:46:21 12/06/2025                               

           job ended   at     00:46:21 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13120 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.72E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.74E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.74E-01                                          

 dcop: end dcop, cpu clock= 2.76E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.79E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.81E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.81E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.81E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.81E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.81E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.81E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.82E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:49:21 12/06/2025                               

           job ended   at     00:49:22 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.71E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.73E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.73E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.74E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.74E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.74E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:24 12/06/2025                               

           job ended   at     00:49:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9540 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.52E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.74E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.75E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.76E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.76E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.76E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.76E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.76E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.76E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:01 12/06/2025                               

           job ended   at     00:53:02 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15468 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.71E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.72E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.74E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.74E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.74E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:04 12/06/2025                               

           job ended   at     00:53:04 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6640 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.68E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.69E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.69E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.69E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.69E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.69E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.69E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:55:23 12/06/2025                               

           job ended   at     00:55:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3840 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.61E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.77E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.77E-01                     

       establish matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.78E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.79E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.82E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.84E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.85E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.86E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.86E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.86E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.86E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.86E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.86E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.86E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.86E-01

 sweep: tran tran0    end, cpu clock= 2.86E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.22 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:55:25 12/06/2025                               

           job ended   at     00:55:26 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10140 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.69E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.69E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.69E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.69E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.69E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.69E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.69E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:56:23 12/06/2025                               

           job ended   at     00:56:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14892 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.70E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:26 12/06/2025                               

           job ended   at     00:56:26 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13684 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.70E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:37 12/06/2025                               

           job ended   at     01:01:37 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11892 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.72E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.73E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.74E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.74E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.74E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.74E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.74E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:40 12/06/2025                               

           job ended   at     01:01:40 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5624 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.65E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.72E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.72E-01                                  

 init: end check errors, cpu clock= 2.79E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.79E-01                     

       establish matrix -- done, cpu clock= 2.80E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.80E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.81E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.81E-01                                          

 dcop: end dcop, cpu clock= 2.83E-01 peak memory=      73 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.84E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.86E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.88E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.88E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.88E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.88E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.88E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.89E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.89E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.89E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.89E-01

 sweep: tran tran0    end, cpu clock= 2.89E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:35 12/06/2025                               

           job ended   at     01:20:35 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11776 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      74 mb tot_iter=       6  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\c00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7098E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4383E-10 tot_iter=     175 conv_iter=      67 cpu clock= 2.68E-01

 tran: time= 5.4873E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.69E-01

 tran: time= 7.1873E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.69E-01

 tran: time= 8.8873E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.69E-01

 tran: time= 1.0587E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.69E-01

 tran: time= 1.2287E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.69E-01

 tran: time= 1.3987E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.69E-01

 tran: time= 1.5687E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     01:20:38 12/06/2025                               

           job ended   at     01:20:38 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
