

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\iutPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20440 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.63E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.63E-01                                  

 init: end check errors, cpu clock= 2.70E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.70E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\iutPAD.out.

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.73E-01                       

 sweep: dc dc0    end, cpu clock= 2.82E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:43 12/01/2025                               

           job ended   at     23:08:43 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\iutPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19900 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.46E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.46E-01                                  

 init: end check errors, cpu clock= 2.53E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.53E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.55E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\iutPAD.out.

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.56E-01                       

 sweep: dc dc0    end, cpu clock= 2.64E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.17 seconds                               

           total elapsed time            0.26 seconds                           

           job started at     11:49:53 12/02/2025                               

           job ended   at     11:49:53 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15120 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.58E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.60E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.61E-01                       

 sweep: dc dc0    end, cpu clock= 2.70E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     00:09:06 12/06/2025                               

           job ended   at     00:09:06 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18128 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.76E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.76E-01                     

       establish matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.79E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.80E-01                       

 sweep: dc dc0    end, cpu clock= 2.88E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:21:33 12/06/2025                               

           job ended   at     00:21:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9108 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.40E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.46E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.46E-01                                  

 init: end check errors, cpu clock= 2.53E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.53E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.55E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.56E-01                       

 sweep: dc dc0    end, cpu clock= 2.65E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     00:29:33 12/06/2025                               

           job ended   at     00:29:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.84E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.93E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.93E-01                                  

 init: end check errors, cpu clock= 3.01E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.01E-01                     

       establish matrix -- done, cpu clock= 3.02E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.02E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.03E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 3.04E-01                       

 sweep: dc dc0    end, cpu clock= 3.13E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.22 seconds                               

           total elapsed time            0.31 seconds                           

           job started at     00:30:32 12/06/2025                               

           job ended   at     00:30:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12000 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.64E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.64E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.72E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.74E-01                       

 sweep: dc dc0    end, cpu clock= 2.83E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:46:13 12/06/2025                               

           job ended   at     00:46:13 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16276 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.61E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.61E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.69E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.71E-01 peak memory=      74 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.71E-01                       

 sweep: dc dc0    end, cpu clock= 2.80E-01 peak memory=      74 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:49:15 12/06/2025                               

           job ended   at     00:49:16 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.68E-01                       

 sweep: dc dc0    end, cpu clock= 2.77E-01 peak memory=      74 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:52:54 12/06/2025                               

           job ended   at     00:52:54 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14712 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.63E-01                       

 sweep: dc dc0    end, cpu clock= 2.72E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     00:55:17 12/06/2025                               

           job ended   at     00:55:17 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19832 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.63E-01                       

 sweep: dc dc0    end, cpu clock= 2.72E-01 peak memory=      74 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     00:56:17 12/06/2025                               

           job ended   at     00:56:18 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6068 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.65E-01                       

 sweep: dc dc0    end, cpu clock= 2.74E-01 peak memory=      73 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     01:01:31 12/06/2025                               

           job ended   at     01:01:32 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19668 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.63E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.70E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.70E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.78E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.78E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.80E-01 peak memory=      74 mb            

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\iutPAD.out.sw0 

 sweep: dc dc0    begin, #sweeps=  67 cpu clock= 2.80E-01                       

 sweep: dc dc0    end, cpu clock= 2.89E-01 peak memory=      74 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:26 12/06/2025                               

           job ended   at     01:20:26 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
