

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdnPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5860 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.61E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.61E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.71E-01                                          

 dcop: end dcop, cpu clock= 2.74E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdnPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.76E-01 

 tran: time= 1.7296E-10 tot_iter=      54 conv_iter=      20 cpu clock= 2.77E-01

 tran: time= 3.4618E-10 tot_iter=     102 conv_iter=      36 cpu clock= 2.78E-01

 tran: time= 5.2847E-10 tot_iter=     132 conv_iter=      47 cpu clock= 2.78E-01

 tran: time= 7.4830E-10 tot_iter=     138 conv_iter=      50 cpu clock= 2.78E-01

 tran: time= 9.1830E-10 tot_iter=     142 conv_iter=      52 cpu clock= 2.78E-01

 tran: time= 1.0883E-09 tot_iter=     146 conv_iter=      54 cpu clock= 2.79E-01

 tran: time= 1.2583E-09 tot_iter=     150 conv_iter=      56 cpu clock= 2.79E-01

 tran: time= 1.4283E-09 tot_iter=     154 conv_iter=      58 cpu clock= 2.79E-01

 tran: time= 1.5983E-09 tot_iter=     158 conv_iter=      60 cpu clock= 2.79E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      62 cpu clock= 2.79E-01

 sweep: tran tran0    end, cpu clock= 2.79E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:48 12/01/2025                               

           job ended   at     23:08:48 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdnPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10604 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.46E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.46E-01                                  

 init: end check errors, cpu clock= 2.53E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.53E-01                     

       establish matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.54E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.55E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.56E-01                                          

 dcop: end dcop, cpu clock= 2.57E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdnPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.60E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.62E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.64E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.64E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.64E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.64E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.65E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.65E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.65E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:49:58 12/02/2025                               

           job ended   at     11:49:58 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8080 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.72E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.74E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.75E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.75E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.75E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:13 12/06/2025                               

           job ended   at     00:09:13 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21288 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.62E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.62E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.70E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.71E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.72E-01                                          

 dcop: end dcop, cpu clock= 2.73E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.76E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.77E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.79E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.79E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.80E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.80E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.80E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.80E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.80E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:21:38 12/06/2025                               

           job ended   at     00:21:39 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.59E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.59E-01                     

       establish matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.64E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.66E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.67E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.68E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.68E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.68E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.68E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.68E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.68E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.68E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.68E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:38 12/06/2025                               

           job ended   at     00:29:39 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.69E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.71E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:38 12/06/2025                               

           job ended   at     00:30:38 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14608 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.62E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.62E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.71E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.71E-01                                          

 dcop: end dcop, cpu clock= 2.73E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.76E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.78E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.79E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.80E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.80E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.80E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.80E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.80E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.80E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:17 12/06/2025                               

           job ended   at     00:46:17 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15700 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.59E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.74E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.74E-01                     

       establish matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.76E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.76E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.81E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.82E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.83E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.83E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.83E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.83E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.83E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.83E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.84E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.84E-01

 sweep: tran tran0    end, cpu clock= 2.84E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:49:20 12/06/2025                               

           job ended   at     00:49:20 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7640 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.07E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.07E-01                                  

 init: end check errors, cpu clock= 3.14E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.14E-01                     

       establish matrix -- done, cpu clock= 3.15E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.15E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.17E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.17E-01                                          

 dcop: end dcop, cpu clock= 3.19E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.21E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 3.23E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 3.24E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 3.25E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 3.25E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 3.25E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 3.25E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 3.25E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 3.25E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 3.25E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 3.25E-01

 sweep: tran tran0    end, cpu clock= 3.25E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.34 seconds                           

           job started at     00:52:59 12/06/2025                               

           job ended   at     00:52:59 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14204 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.70E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.72E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:21 12/06/2025                               

           job ended   at     00:55:21 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1668 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.68E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.70E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.70E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:22 12/06/2025                               

           job ended   at     00:56:22 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1348 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.69E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.70E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:35 12/06/2025                               

           job ended   at     01:01:36 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19864 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.64E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.64E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.71E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.74E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rdnPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.79E-01

 tran: time= 3.4046E-10 tot_iter=     158 conv_iter=      61 cpu clock= 2.81E-01

 tran: time= 5.4062E-10 tot_iter=     195 conv_iter=      76 cpu clock= 2.81E-01

 tran: time= 6.8460E-10 tot_iter=     199 conv_iter=      78 cpu clock= 2.81E-01

 tran: time= 8.5460E-10 tot_iter=     203 conv_iter=      80 cpu clock= 2.81E-01

 tran: time= 1.0246E-09 tot_iter=     207 conv_iter=      82 cpu clock= 2.81E-01

 tran: time= 1.1946E-09 tot_iter=     211 conv_iter=      84 cpu clock= 2.82E-01

 tran: time= 1.3646E-09 tot_iter=     215 conv_iter=      86 cpu clock= 2.82E-01

 tran: time= 1.5346E-09 tot_iter=     219 conv_iter=      88 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     223 conv_iter=      90 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:32 12/06/2025                               

           job ended   at     01:20:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
