

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdtPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14904 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.69E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.69E-01                                  

 init: end check errors, cpu clock= 2.77E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.77E-01                     

       establish matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.79E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.79E-01                                          

 dcop: end dcop, cpu clock= 2.82E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdtPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.85E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.86E-01

 tran: time= 3.4046E-10 tot_iter=     111 conv_iter=      39 cpu clock= 2.87E-01

 tran: time= 5.3393E-10 tot_iter=     134 conv_iter=      47 cpu clock= 2.88E-01

 tran: time= 6.8832E-10 tot_iter=     138 conv_iter=      49 cpu clock= 2.88E-01

 tran: time= 8.5832E-10 tot_iter=     142 conv_iter=      51 cpu clock= 2.88E-01

 tran: time= 1.0283E-09 tot_iter=     146 conv_iter=      53 cpu clock= 2.88E-01

 tran: time= 1.1983E-09 tot_iter=     150 conv_iter=      55 cpu clock= 2.88E-01

 tran: time= 1.3683E-09 tot_iter=     154 conv_iter=      57 cpu clock= 2.88E-01

 tran: time= 1.5383E-09 tot_iter=     158 conv_iter=      59 cpu clock= 2.88E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      61 cpu clock= 2.88E-01

 sweep: tran tran0    end, cpu clock= 2.89E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     18:56:50 12/01/2025                               

           job ended   at     18:56:50 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdtPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19860 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.42E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.49E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.49E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.60E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdtPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.62E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.63E-01

 tran: time= 3.4046E-10 tot_iter=     111 conv_iter=      39 cpu clock= 2.64E-01

 tran: time= 5.3393E-10 tot_iter=     134 conv_iter=      47 cpu clock= 2.65E-01

 tran: time= 6.8832E-10 tot_iter=     138 conv_iter=      49 cpu clock= 2.65E-01

 tran: time= 8.5832E-10 tot_iter=     142 conv_iter=      51 cpu clock= 2.65E-01

 tran: time= 1.0283E-09 tot_iter=     146 conv_iter=      53 cpu clock= 2.65E-01

 tran: time= 1.1983E-09 tot_iter=     150 conv_iter=      55 cpu clock= 2.65E-01

 tran: time= 1.3683E-09 tot_iter=     154 conv_iter=      57 cpu clock= 2.65E-01

 tran: time= 1.5383E-09 tot_iter=     158 conv_iter=      59 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      61 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     19:25:05 12/01/2025                               

           job ended   at     19:25:05 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
