

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdxPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20100 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.62E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.62E-01                                  

 init: end check errors, cpu clock= 2.70E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.70E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.70E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.71E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.72E-01                                          

 dcop: end dcop, cpu clock= 2.74E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdxPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.76E-01 

 tran: time= 1.7774E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.77E-01

 tran: time= 3.5136E-10 tot_iter=     118 conv_iter=      41 cpu clock= 2.78E-01

 tran: time= 5.2268E-10 tot_iter=     132 conv_iter=      47 cpu clock= 2.79E-01

 tran: time= 6.8494E-10 tot_iter=     136 conv_iter=      49 cpu clock= 2.79E-01

 tran: time= 8.5494E-10 tot_iter=     140 conv_iter=      51 cpu clock= 2.79E-01

 tran: time= 1.0249E-09 tot_iter=     144 conv_iter=      53 cpu clock= 2.79E-01

 tran: time= 1.1949E-09 tot_iter=     148 conv_iter=      55 cpu clock= 2.79E-01

 tran: time= 1.3649E-09 tot_iter=     152 conv_iter=      57 cpu clock= 2.79E-01

 tran: time= 1.5349E-09 tot_iter=     156 conv_iter=      59 cpu clock= 2.79E-01

 tran: time= 1.7000E-09 tot_iter=     160 conv_iter=      61 cpu clock= 2.79E-01

 sweep: tran tran0    end, cpu clock= 2.79E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:48 12/01/2025                               

           job ended   at     23:08:49 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdxPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9872 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.45E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.45E-01                                  

 init: end check errors, cpu clock= 2.52E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.52E-01                     

       establish matrix -- done, cpu clock= 2.52E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.53E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.54E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.54E-01                                          

 dcop: end dcop, cpu clock= 2.56E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rdxPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.58E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.60E-01

 tran: time= 3.4322E-10 tot_iter=     175 conv_iter=      66 cpu clock= 2.62E-01

 tran: time= 5.6696E-10 tot_iter=     194 conv_iter=      75 cpu clock= 2.62E-01

 tran: time= 7.3696E-10 tot_iter=     198 conv_iter=      77 cpu clock= 2.62E-01

 tran: time= 9.0696E-10 tot_iter=     202 conv_iter=      79 cpu clock= 2.62E-01

 tran: time= 1.0770E-09 tot_iter=     206 conv_iter=      81 cpu clock= 2.62E-01

 tran: time= 1.2470E-09 tot_iter=     210 conv_iter=      83 cpu clock= 2.62E-01

 tran: time= 1.4170E-09 tot_iter=     214 conv_iter=      85 cpu clock= 2.62E-01

 tran: time= 1.5870E-09 tot_iter=     218 conv_iter=      87 cpu clock= 2.62E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      89 cpu clock= 2.62E-01

 sweep: tran tran0    end, cpu clock= 2.62E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:49:59 12/02/2025                               

           job ended   at     11:49:59 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
