

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rutPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15168 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rutPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.70E-01 

 tran: time= 1.7091E-10 tot_iter=      59 conv_iter=      22 cpu clock= 2.72E-01

 tran: time= 3.4181E-10 tot_iter=     117 conv_iter=      41 cpu clock= 2.73E-01

 tran: time= 5.2714E-10 tot_iter=     133 conv_iter=      48 cpu clock= 2.74E-01

 tran: time= 6.8463E-10 tot_iter=     137 conv_iter=      50 cpu clock= 2.74E-01

 tran: time= 8.5463E-10 tot_iter=     141 conv_iter=      52 cpu clock= 2.74E-01

 tran: time= 1.0246E-09 tot_iter=     145 conv_iter=      54 cpu clock= 2.74E-01

 tran: time= 1.1946E-09 tot_iter=     149 conv_iter=      56 cpu clock= 2.74E-01

 tran: time= 1.3646E-09 tot_iter=     153 conv_iter=      58 cpu clock= 2.74E-01

 tran: time= 1.5346E-09 tot_iter=     157 conv_iter=      60 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      62 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:46 12/01/2025                               

           job ended   at     23:08:46 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rutPAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17468 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.46E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.46E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.58E-01                                          

 dcop: end dcop, cpu clock= 2.60E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\rutPAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.62E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.67E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.69E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.69E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.70E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.70E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.70E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.70E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.70E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:49:56 12/02/2025                               

           job ended   at     11:49:56 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17636 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.61E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.69E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.69E-01                                  

 init: end check errors, cpu clock= 2.86E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.86E-01                     

       establish matrix -- done, cpu clock= 2.86E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.87E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.88E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.89E-01                                          

 dcop: end dcop, cpu clock= 2.93E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.96E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 3.02E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 3.04E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 3.05E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 3.05E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 3.05E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 3.05E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 3.05E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 3.05E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 3.05E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 3.05E-01

 sweep: tran tran0    end, cpu clock= 3.05E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.23 seconds                               

           total elapsed time            0.32 seconds                           

           job started at     00:09:10 12/06/2025                               

           job ended   at     00:09:10 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15952 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.61E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.61E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.73E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.80E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.81E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.82E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.82E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.82E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.82E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.82E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.82E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:21:36 12/06/2025                               

           job ended   at     00:21:36 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6840 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.69E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.71E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.71E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.77E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.78E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.79E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.79E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.79E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.79E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.79E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.79E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.79E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.79E-01

 sweep: tran tran0    end, cpu clock= 2.79E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:29:36 12/06/2025                               

           job ended   at     00:29:36 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19728 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.63E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.72E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.72E-01                                  

 init: end check errors, cpu clock= 2.83E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.83E-01                     

       establish matrix -- done, cpu clock= 2.83E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.83E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.85E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.85E-01                                          

 dcop: end dcop, cpu clock= 2.86E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.88E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.91E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.93E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.93E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.93E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.94E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.94E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.94E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.94E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.94E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.94E-01

 sweep: tran tran0    end, cpu clock= 2.94E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.31 seconds                           

           job started at     00:30:36 12/06/2025                               

           job ended   at     00:30:36 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14928 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.61E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.69E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.69E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.79E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.79E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.80E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.81E-01                                          

 dcop: end dcop, cpu clock= 2.82E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.84E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.86E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.88E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.88E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.88E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.88E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.88E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.89E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.89E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.89E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.89E-01

 sweep: tran tran0    end, cpu clock= 2.89E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:15 12/06/2025                               

           job ended   at     00:46:15 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20860 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.76E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.82E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.84E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.84E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.84E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.84E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.84E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.84E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.85E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.85E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.85E-01

 sweep: tran tran0    end, cpu clock= 2.85E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:49:18 12/06/2025                               

           job ended   at     00:49:18 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5608 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.59E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.77E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.83E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.84E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.85E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.85E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.85E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.85E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.85E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.85E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.85E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.85E-01

 sweep: tran tran0    end, cpu clock= 2.86E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:52:56 12/06/2025                               

           job ended   at     00:52:57 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15732 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.59E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.76E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.76E-01                     

       establish matrix -- done, cpu clock= 2.76E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.76E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.77E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.78E-01                                          

 dcop: end dcop, cpu clock= 2.79E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.81E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.83E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.85E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.85E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.85E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.85E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.85E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.85E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.85E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.85E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.86E-01

 sweep: tran tran0    end, cpu clock= 2.86E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:55:19 12/06/2025                               

           job ended   at     00:55:20 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3584 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.64E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.64E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.79E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.81E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.83E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.83E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.83E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.83E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.83E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.83E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.83E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.84E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.84E-01

 sweep: tran tran0    end, cpu clock= 2.84E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:56:20 12/06/2025                               

           job ended   at     00:56:20 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16048 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.76E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.76E-01                     

       establish matrix -- done, cpu clock= 2.76E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.77E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.78E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.78E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.82E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.85E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.86E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.87E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.87E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.87E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.87E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.87E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.87E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.87E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.87E-01

 sweep: tran tran0    end, cpu clock= 2.87E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:01:34 12/06/2025                               

           job ended   at     01:01:34 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13288 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.59E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.74E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.74E-01                     

       establish matrix -- done, cpu clock= 2.74E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.76E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\rutPAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7020E-10 tot_iter=      90 conv_iter=      36 cpu clock= 2.82E-01

 tran: time= 3.4056E-10 tot_iter=     176 conv_iter=      68 cpu clock= 2.85E-01

 tran: time= 5.1422E-10 tot_iter=     192 conv_iter=      76 cpu clock= 2.85E-01

 tran: time= 7.5305E-10 tot_iter=     198 conv_iter=      79 cpu clock= 2.85E-01

 tran: time= 9.2305E-10 tot_iter=     202 conv_iter=      81 cpu clock= 2.85E-01

 tran: time= 1.0930E-09 tot_iter=     206 conv_iter=      83 cpu clock= 2.85E-01

 tran: time= 1.2630E-09 tot_iter=     210 conv_iter=      85 cpu clock= 2.86E-01

 tran: time= 1.4330E-09 tot_iter=     214 conv_iter=      87 cpu clock= 2.86E-01

 tran: time= 1.6030E-09 tot_iter=     218 conv_iter=      89 cpu clock= 2.86E-01

 tran: time= 1.7000E-09 tot_iter=     222 conv_iter=      91 cpu clock= 2.86E-01

 sweep: tran tran0    end, cpu clock= 2.86E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:30 12/06/2025                               

           job ended   at     01:20:30 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
