

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8776 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.63E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.70E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.70E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.78E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.78E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.79E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.80E-01                                          

 dcop: end dcop, cpu clock= 2.81E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.83E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.85E-01

 tran: time= 3.4046E-10 tot_iter=     111 conv_iter=      39 cpu clock= 2.86E-01

 tran: time= 5.3393E-10 tot_iter=     134 conv_iter=      47 cpu clock= 2.86E-01

 tran: time= 6.8832E-10 tot_iter=     138 conv_iter=      49 cpu clock= 2.86E-01

 tran: time= 8.5832E-10 tot_iter=     142 conv_iter=      51 cpu clock= 2.86E-01

 tran: time= 1.0283E-09 tot_iter=     146 conv_iter=      53 cpu clock= 2.86E-01

 tran: time= 1.1983E-09 tot_iter=     150 conv_iter=      55 cpu clock= 2.86E-01

 tran: time= 1.3683E-09 tot_iter=     154 conv_iter=      57 cpu clock= 2.86E-01

 tran: time= 1.5383E-09 tot_iter=     158 conv_iter=      59 cpu clock= 2.86E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      61 cpu clock= 2.87E-01

 sweep: tran tran0    end, cpu clock= 2.87E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     23:08:55 12/01/2025                               

           job ended   at     23:08:55 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8104 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.73E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.74E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.78E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.80E-01

 tran: time= 3.4046E-10 tot_iter=     111 conv_iter=      39 cpu clock= 2.81E-01

 tran: time= 5.3393E-10 tot_iter=     134 conv_iter=      47 cpu clock= 2.81E-01

 tran: time= 6.8832E-10 tot_iter=     138 conv_iter=      49 cpu clock= 2.82E-01

 tran: time= 8.5832E-10 tot_iter=     142 conv_iter=      51 cpu clock= 2.82E-01

 tran: time= 1.0283E-09 tot_iter=     146 conv_iter=      53 cpu clock= 2.82E-01

 tran: time= 1.1983E-09 tot_iter=     150 conv_iter=      55 cpu clock= 2.82E-01

 tran: time= 1.3683E-09 tot_iter=     154 conv_iter=      57 cpu clock= 2.82E-01

 tran: time= 1.5383E-09 tot_iter=     158 conv_iter=      59 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      61 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:57 12/01/2025                               

           job ended   at     23:08:58 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20148 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.58E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.63E-01

 tran: time= 3.4006E-10 tot_iter=     167 conv_iter=      64 cpu clock= 2.64E-01

 tran: time= 5.4442E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.65E-01

 tran: time= 7.0384E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.65E-01

 tran: time= 8.7384E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.65E-01

 tran: time= 1.0438E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.65E-01

 tran: time= 1.2138E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.65E-01

 tran: time= 1.3838E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.65E-01

 tran: time= 1.5538E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:05 12/02/2025                               

           job ended   at     11:50:06 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19584 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.35E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.42E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.42E-01                                  

 init: end check errors, cpu clock= 2.49E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.49E-01                     

       establish matrix -- done, cpu clock= 2.50E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.50E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.51E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.52E-01                                          

 dcop: end dcop, cpu clock= 2.53E-01 peak memory=      74 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.56E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.57E-01

 tran: time= 3.4006E-10 tot_iter=     167 conv_iter=      64 cpu clock= 2.59E-01

 tran: time= 5.4442E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.59E-01

 tran: time= 7.0384E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.59E-01

 tran: time= 8.7384E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.59E-01

 tran: time= 1.0438E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.59E-01

 tran: time= 1.2138E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.59E-01

 tran: time= 1.3838E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.60E-01

 tran: time= 1.5538E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.60E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.60E-01

 sweep: tran tran0    end, cpu clock= 2.60E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:09 12/02/2025                               

           job ended   at     11:50:09 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3668 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.74E-01

 tran: time= 3.4006E-10 tot_iter=     167 conv_iter=      64 cpu clock= 2.76E-01

 tran: time= 5.4442E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.76E-01

 tran: time= 7.0384E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.76E-01

 tran: time= 8.7384E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 1.0438E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.77E-01

 tran: time= 1.2138E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.77E-01

 tran: time= 1.3838E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.77E-01

 tran: time= 1.5538E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:22 12/06/2025                               

           job ended   at     00:09:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18056 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       4  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.70E-01

 tran: time= 3.4006E-10 tot_iter=     167 conv_iter=      64 cpu clock= 2.72E-01

 tran: time= 5.4442E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.72E-01

 tran: time= 7.0384E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.72E-01

 tran: time= 8.7384E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 1.0438E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.2138E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.3838E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.73E-01

 tran: time= 1.5538E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:26 12/06/2025                               

           job ended   at     00:09:26 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
