

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16672 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.80E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.81E-01

 tran: time= 3.4707E-10 tot_iter=     114 conv_iter=      41 cpu clock= 2.82E-01

 tran: time= 5.2405E-10 tot_iter=     131 conv_iter=      48 cpu clock= 2.83E-01

 tran: time= 7.6422E-10 tot_iter=     137 conv_iter=      51 cpu clock= 2.83E-01

 tran: time= 9.3422E-10 tot_iter=     141 conv_iter=      53 cpu clock= 2.83E-01

 tran: time= 1.1042E-09 tot_iter=     145 conv_iter=      55 cpu clock= 2.83E-01

 tran: time= 1.2742E-09 tot_iter=     149 conv_iter=      57 cpu clock= 2.83E-01

 tran: time= 1.4442E-09 tot_iter=     153 conv_iter=      59 cpu clock= 2.83E-01

 tran: time= 1.6142E-09 tot_iter=     157 conv_iter=      61 cpu clock= 2.83E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:56 12/01/2025                               

           job ended   at     23:08:56 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10508 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.67E-01 

 tran: time= 1.7762E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.68E-01

 tran: time= 3.4707E-10 tot_iter=     114 conv_iter=      41 cpu clock= 2.69E-01

 tran: time= 5.2405E-10 tot_iter=     131 conv_iter=      48 cpu clock= 2.70E-01

 tran: time= 7.6422E-10 tot_iter=     137 conv_iter=      51 cpu clock= 2.70E-01

 tran: time= 9.3422E-10 tot_iter=     141 conv_iter=      53 cpu clock= 2.70E-01

 tran: time= 1.1042E-09 tot_iter=     145 conv_iter=      55 cpu clock= 2.70E-01

 tran: time= 1.2742E-09 tot_iter=     149 conv_iter=      57 cpu clock= 2.70E-01

 tran: time= 1.4442E-09 tot_iter=     153 conv_iter=      59 cpu clock= 2.70E-01

 tran: time= 1.6142E-09 tot_iter=     157 conv_iter=      61 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      62 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:59 12/01/2025                               

           job ended   at     23:08:59 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14460 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.58E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.63E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.64E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.65E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.65E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.65E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.65E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.65E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.65E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:07 12/02/2025                               

           job ended   at     11:50:07 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14700 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.29E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.36E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.36E-01                                  

 init: end check errors, cpu clock= 2.43E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.43E-01                     

       establish matrix -- done, cpu clock= 2.43E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.43E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.45E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.46E-01                                          

 dcop: end dcop, cpu clock= 2.47E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\x01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.49E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.51E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.53E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.53E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.53E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.53E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.53E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.53E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.53E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.54E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.54E-01

 sweep: tran tran0    end, cpu clock= 2.54E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     11:50:10 12/02/2025                               

           job ended   at     11:50:10 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6012 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.76E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.78E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.79E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.79E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.79E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.79E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.79E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.79E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.79E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:09:24 12/06/2025                               

           job ended   at     00:09:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11868 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.69E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.70E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:28 12/06/2025                               

           job ended   at     00:09:29 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5392 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.69E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.71E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:21:47 12/06/2025                               

           job ended   at     00:21:48 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7180 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.58E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.63E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.65E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.65E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.65E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.65E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.65E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.65E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.65E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.66E-01

 sweep: tran tran0    end, cpu clock= 2.66E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:51 12/06/2025                               

           job ended   at     00:21:51 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12532 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.70E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.71E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.72E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:29:48 12/06/2025                               

           job ended   at     00:29:48 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16048 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.55E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.57E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.62E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.64E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.64E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.64E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.64E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.64E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.64E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.65E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:52 12/06/2025                               

           job ended   at     00:29:52 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3848 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.68E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.70E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.70E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:46 12/06/2025                               

           job ended   at     00:30:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16152 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.75E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.76E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.77E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.77E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:49 12/06/2025                               

           job ended   at     00:30:50 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19868 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.62E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.62E-01                                  

 init: end check errors, cpu clock= 2.69E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.69E-01                     

       establish matrix -- done, cpu clock= 2.70E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.70E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.72E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.72E-01                                          

 dcop: end dcop, cpu clock= 2.74E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.76E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.78E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.79E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.80E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.80E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.80E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.80E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.80E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.80E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.80E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.80E-01

 sweep: tran tran0    end, cpu clock= 2.80E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:46:24 12/06/2025                               

           job ended   at     00:46:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.15E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.15E-01                                  

 init: end check errors, cpu clock= 3.22E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.22E-01                     

       establish matrix -- done, cpu clock= 3.23E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.23E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.24E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.24E-01                                          

 dcop: end dcop, cpu clock= 3.26E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.28E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 3.30E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 3.32E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 3.32E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 3.33E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 3.33E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 3.33E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 3.33E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 3.33E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 3.33E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 3.33E-01

 sweep: tran tran0    end, cpu clock= 3.33E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.35 seconds                           

           job started at     00:46:27 12/06/2025                               

           job ended   at     00:46:28 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12736 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.29E+00                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.30E+00 peak memory=      73 mb      

 init: begin check errors, cpu clock= 1.30E+00                                  

 init: end check errors, cpu clock= 1.31E+00 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.31E+00                     

       establish matrix -- done, cpu clock= 1.31E+00 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 1.31E+00 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 1.31E+00 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 1.31E+00                                          

 dcop: end dcop, cpu clock= 1.31E+00 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 1.31E+00 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 1.31E+00

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 1.31E+00

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 1.32E+00

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 1.32E+00

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 1.32E+00

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 1.32E+00

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 1.32E+00

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 1.32E+00

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 1.32E+00

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 1.32E+00

 sweep: tran tran0    end, cpu clock= 1.32E+00 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            1.33 seconds                           

           job started at     00:49:27 12/06/2025                               

           job ended   at     00:49:29 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15520 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.68E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.70E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.70E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:31 12/06/2025                               

           job ended   at     00:49:31 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6476 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.70E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.72E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.72E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.72E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:07 12/06/2025                               

           job ended   at     00:53:07 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17252 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.74E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.76E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.76E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.77E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:09 12/06/2025                               

           job ended   at     00:53:10 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18556 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.69E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.71E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:29 12/06/2025                               

           job ended   at     00:55:29 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.69E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.71E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.71E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.71E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:55:32 12/06/2025                               

           job ended   at     00:55:32 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10524 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.71E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.72E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.73E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:30 12/06/2025                               

           job ended   at     00:56:30 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19312 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.71E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.72E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.73E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.73E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:33 12/06/2025                               

           job ended   at     00:56:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11608 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.68E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.69E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.69E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.70E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.70E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.70E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.70E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.70E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     01:01:43 12/06/2025                               

           job ended   at     01:01:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20112 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.74E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.75E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.76E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.76E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.76E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.76E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.76E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.76E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:45 12/06/2025                               

           job ended   at     01:01:45 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10928 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.66E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.66E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.80E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.82E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.82E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.82E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.82E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.83E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.83E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.83E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.83E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:44 12/06/2025                               

           job ended   at     01:20:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19700 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.66E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\x01PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.70E-01 

 tran: time= 1.7414E-10 tot_iter=      87 conv_iter=      35 cpu clock= 2.72E-01

 tran: time= 3.4873E-10 tot_iter=     171 conv_iter=      65 cpu clock= 2.73E-01

 tran: time= 5.3181E-10 tot_iter=     190 conv_iter=      74 cpu clock= 2.74E-01

 tran: time= 6.8912E-10 tot_iter=     194 conv_iter=      76 cpu clock= 2.74E-01

 tran: time= 8.5912E-10 tot_iter=     198 conv_iter=      78 cpu clock= 2.74E-01

 tran: time= 1.0291E-09 tot_iter=     202 conv_iter=      80 cpu clock= 2.74E-01

 tran: time= 1.1991E-09 tot_iter=     206 conv_iter=      82 cpu clock= 2.74E-01

 tran: time= 1.3691E-09 tot_iter=     210 conv_iter=      84 cpu clock= 2.74E-01

 tran: time= 1.5391E-09 tot_iter=     214 conv_iter=      86 cpu clock= 2.74E-01

 tran: time= 1.7000E-09 tot_iter=     218 conv_iter=      88 cpu clock= 2.74E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:47 12/06/2025                               

           job ended   at     01:20:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
