

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18080 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.72E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.74E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.74E-01                                          

 dcop: end dcop, cpu clock= 2.76E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.78E-01 

 tran: time= 1.7296E-10 tot_iter=      54 conv_iter=      20 cpu clock= 2.79E-01

 tran: time= 3.4884E-10 tot_iter=     106 conv_iter=      38 cpu clock= 2.80E-01

 tran: time= 5.1754E-10 tot_iter=     132 conv_iter=      47 cpu clock= 2.81E-01

 tran: time= 7.2212E-10 tot_iter=     138 conv_iter=      50 cpu clock= 2.81E-01

 tran: time= 8.9212E-10 tot_iter=     142 conv_iter=      52 cpu clock= 2.81E-01

 tran: time= 1.0621E-09 tot_iter=     146 conv_iter=      54 cpu clock= 2.81E-01

 tran: time= 1.2321E-09 tot_iter=     150 conv_iter=      56 cpu clock= 2.81E-01

 tran: time= 1.4021E-09 tot_iter=     154 conv_iter=      58 cpu clock= 2.81E-01

 tran: time= 1.5721E-09 tot_iter=     158 conv_iter=      60 cpu clock= 2.81E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      62 cpu clock= 2.81E-01

 sweep: tran tran0    end, cpu clock= 2.81E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     23:08:55 12/01/2025                               

           job ended   at     23:08:55 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.66E-01 

 tran: time= 1.7296E-10 tot_iter=      54 conv_iter=      20 cpu clock= 2.67E-01

 tran: time= 3.4884E-10 tot_iter=     106 conv_iter=      38 cpu clock= 2.68E-01

 tran: time= 5.1754E-10 tot_iter=     132 conv_iter=      47 cpu clock= 2.68E-01

 tran: time= 7.2212E-10 tot_iter=     138 conv_iter=      50 cpu clock= 2.68E-01

 tran: time= 8.9212E-10 tot_iter=     142 conv_iter=      52 cpu clock= 2.68E-01

 tran: time= 1.0621E-09 tot_iter=     146 conv_iter=      54 cpu clock= 2.69E-01

 tran: time= 1.2321E-09 tot_iter=     150 conv_iter=      56 cpu clock= 2.69E-01

 tran: time= 1.4021E-09 tot_iter=     154 conv_iter=      58 cpu clock= 2.69E-01

 tran: time= 1.5721E-09 tot_iter=     158 conv_iter=      60 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     162 conv_iter=      62 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:58 12/01/2025                               

           job ended   at     23:08:58 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20188 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.69E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.73E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.75E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.75E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.75E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.76E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.76E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.76E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.76E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:50:06 12/02/2025                               

           job ended   at     11:50:06 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15580 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.30E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.37E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.37E-01                                  

 init: end check errors, cpu clock= 2.44E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.44E-01                     

       establish matrix -- done, cpu clock= 2.44E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.44E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.46E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.46E-01                                          

 dcop: end dcop, cpu clock= 2.48E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.50E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.52E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.53E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.54E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.54E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.54E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.54E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.54E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.54E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.54E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.54E-01

 sweep: tran tran0    end, cpu clock= 2.54E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     11:50:09 12/02/2025                               

           job ended   at     11:50:09 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11892 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.55E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.63E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.63E-01                                  

 init: end check errors, cpu clock= 2.71E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.71E-01                     

       establish matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.71E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.73E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.79E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.81E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.81E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.81E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.82E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.82E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.82E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.82E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:09:23 12/06/2025                               

           job ended   at     00:09:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21092 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.70E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.71E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.72E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:09:26 12/06/2025                               

           job ended   at     00:09:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4484 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.70E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.71E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.72E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.72E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.72E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.72E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.72E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.72E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:21:46 12/06/2025                               

           job ended   at     00:21:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16508 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.50E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.50E-01                                  

 init: end check errors, cpu clock= 2.58E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.58E-01                     

       establish matrix -- done, cpu clock= 2.58E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 2.58E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 2.59E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.60E-01                                          

 dcop: end dcop, cpu clock= 2.61E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.63E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.64E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.66E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.66E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.67E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.67E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.67E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.67E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.67E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.67E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.67E-01

 sweep: tran tran0    end, cpu clock= 2.67E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:50 12/06/2025                               

           job ended   at     00:21:50 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14712 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.88E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.96E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.96E-01                                  

 init: end check errors, cpu clock= 3.03E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.03E-01                     

       establish matrix -- done, cpu clock= 3.03E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.03E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.05E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.05E-01                                          

 dcop: end dcop, cpu clock= 3.07E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.09E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 3.10E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 3.12E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 3.13E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 3.13E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 3.13E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 3.13E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 3.13E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 3.13E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 3.14E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 3.14E-01

 sweep: tran tran0    end, cpu clock= 3.14E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.23 seconds                               

           total elapsed time            0.33 seconds                           

           job started at     00:29:47 12/06/2025                               

           job ended   at     00:29:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13728 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.59E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.59E-01                     

       establish matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.59E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.67E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.68E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.69E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.69E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.69E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.69E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.69E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.69E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:51 12/06/2025                               

           job ended   at     00:29:51 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5048 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.71E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.72E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.73E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.73E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.73E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.73E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.73E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.73E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:45 12/06/2025                               

           job ended   at     00:30:46 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10268 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.62E-01                                          

 dcop: end dcop, cpu clock= 2.63E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.65E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.67E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.68E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.69E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.69E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.69E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.69E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.69E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.69E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:48 12/06/2025                               

           job ended   at     00:30:49 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18636 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.73E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.76E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.80E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.81E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.82E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.82E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.82E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.82E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.82E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.82E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.82E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.82E-01

 sweep: tran tran0    end, cpu clock= 2.82E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:23 12/06/2025                               

           job ended   at     00:46:23 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 8.15E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 8.23E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 8.23E-01                                  

 init: end check errors, cpu clock= 8.31E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 8.31E-01                     

       establish matrix -- done, cpu clock= 8.31E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 8.31E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 8.32E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 8.33E-01                                          

 dcop: end dcop, cpu clock= 8.34E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 8.36E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 8.38E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 8.39E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 8.40E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 8.40E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 8.40E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 8.40E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 8.40E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 8.40E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 8.40E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 8.40E-01

 sweep: tran tran0    end, cpu clock= 8.41E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.86 seconds                           

           job started at     00:46:26 12/06/2025                               

           job ended   at     00:46:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20504 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 6.76E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 6.83E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 6.83E-01                                  

 init: end check errors, cpu clock= 6.90E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 6.90E-01                     

       establish matrix -- done, cpu clock= 6.91E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 6.91E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 6.92E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 6.93E-01                                          

 dcop: end dcop, cpu clock= 6.94E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 6.96E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 6.98E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 6.99E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 7.00E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 7.00E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 7.00E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 7.00E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 7.00E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 7.00E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 7.00E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 7.01E-01

 sweep: tran tran0    end, cpu clock= 7.01E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.72 seconds                           

           job started at     00:49:26 12/06/2025                               

           job ended   at     00:49:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16704 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.58E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.58E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.75E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.76E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.77E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.77E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:30 12/06/2025                               

           job ended   at     00:49:30 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16360 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.61E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.72E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.72E-01                                  

 init: end check errors, cpu clock= 2.84E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.84E-01                     

       establish matrix -- done, cpu clock= 2.85E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.85E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.87E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.87E-01                                          

 dcop: end dcop, cpu clock= 2.89E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.91E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.92E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.94E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.95E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.95E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.95E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.95E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.96E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.96E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.96E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.96E-01

 sweep: tran tran0    end, cpu clock= 2.96E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.22 seconds                               

           total elapsed time            0.31 seconds                           

           job started at     00:53:06 12/06/2025                               

           job ended   at     00:53:06 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20416 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.51E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.67E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.67E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.74E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.76E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.77E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.77E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.77E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.77E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.77E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.78E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:09 12/06/2025                               

           job ended   at     00:53:09 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4168 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 4.16E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 4.23E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 4.23E-01                                  

 init: end check errors, cpu clock= 4.32E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 4.32E-01                     

       establish matrix -- done, cpu clock= 4.32E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 4.32E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 4.34E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 4.34E-01                                          

 dcop: end dcop, cpu clock= 4.36E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 4.38E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 4.39E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 4.41E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 4.41E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 4.41E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 4.42E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 4.42E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 4.42E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 4.42E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 4.42E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 4.42E-01

 sweep: tran tran0    end, cpu clock= 4.42E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.46 seconds                           

           job started at     00:55:28 12/06/2025                               

           job ended   at     00:55:29 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20252 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.63E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.70E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.70E-01                                  

 init: end check errors, cpu clock= 2.78E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.78E-01                     

       establish matrix -- done, cpu clock= 2.78E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.78E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.80E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.80E-01                                          

 dcop: end dcop, cpu clock= 2.82E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.84E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.85E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.87E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.88E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.88E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.88E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.88E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.88E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.88E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.88E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.88E-01

 sweep: tran tran0    end, cpu clock= 2.88E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.22 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:55:31 12/06/2025                               

           job ended   at     00:55:31 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11828 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.25E+00                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.26E+00 peak memory=      73 mb      

 init: begin check errors, cpu clock= 1.26E+00                                  

 init: end check errors, cpu clock= 1.27E+00 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.27E+00                     

       establish matrix -- done, cpu clock= 1.27E+00 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 1.27E+00 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 1.27E+00 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 1.27E+00                                          

 dcop: end dcop, cpu clock= 1.27E+00 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 1.27E+00 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 1.27E+00

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 1.27E+00

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 1.27E+00

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 1.27E+00

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 1.27E+00

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 1.27E+00

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 1.27E+00

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 1.27E+00

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 1.27E+00

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 1.27E+00

 sweep: tran tran0    end, cpu clock= 1.28E+00 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            1.29 seconds                           

           job started at     00:56:28 12/06/2025                               

           job ended   at     00:56:30 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.62E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.62E-01                     

       establish matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.64E-01                                          

 dcop: end dcop, cpu clock= 2.65E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.69E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.70E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.71E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.71E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.71E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.71E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.71E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.71E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.71E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.71E-01

 sweep: tran tran0    end, cpu clock= 2.71E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:32 12/06/2025                               

           job ended   at     00:56:32 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17484 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.52E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.52E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.68E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.69E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.70E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.70E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.70E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.70E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.70E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.70E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     01:01:42 12/06/2025                               

           job ended   at     01:01:42 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16056 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.45E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.51E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.51E-01                                  

 init: end check errors, cpu clock= 2.59E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.59E-01                     

       establish matrix -- done, cpu clock= 2.59E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.61E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.61E-01                                          

 dcop: end dcop, cpu clock= 2.62E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.64E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.66E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.67E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.68E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.68E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.68E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.68E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.68E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.68E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.68E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.68E-01

 sweep: tran tran0    end, cpu clock= 2.68E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     01:01:44 12/06/2025                               

           job ended   at     01:01:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5240 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.74E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.74E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.76E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.76E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.81E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.83E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.83E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.83E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.83E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.83E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.84E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.84E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.84E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.84E-01

 sweep: tran tran0    end, cpu clock= 2.84E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:43 12/06/2025                               

           job ended   at     01:20:43 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9764 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.52E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\y00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.72E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.73E-01

 tran: time= 3.4277E-10 tot_iter=     158 conv_iter=      62 cpu clock= 2.75E-01

 tran: time= 5.1501E-10 tot_iter=     190 conv_iter=      75 cpu clock= 2.75E-01

 tran: time= 7.1391E-10 tot_iter=     196 conv_iter=      78 cpu clock= 2.75E-01

 tran: time= 8.8391E-10 tot_iter=     200 conv_iter=      80 cpu clock= 2.75E-01

 tran: time= 1.0539E-09 tot_iter=     204 conv_iter=      82 cpu clock= 2.75E-01

 tran: time= 1.2239E-09 tot_iter=     208 conv_iter=      84 cpu clock= 2.75E-01

 tran: time= 1.3939E-09 tot_iter=     212 conv_iter=      86 cpu clock= 2.76E-01

 tran: time= 1.5639E-09 tot_iter=     216 conv_iter=      88 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     220 conv_iter=      90 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:46 12/06/2025                               

           job ended   at     01:20:46 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
