

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19644 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.66E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.74E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.74E-01                                  

 init: end check errors, cpu clock= 2.82E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.82E-01                     

       establish matrix -- done, cpu clock= 2.82E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.82E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.83E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.84E-01                                          

 dcop: end dcop, cpu clock= 2.86E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.88E-01 

 tran: time= 1.7296E-10 tot_iter=      54 conv_iter=      20 cpu clock= 2.90E-01

 tran: time= 3.4014E-10 tot_iter=     105 conv_iter=      37 cpu clock= 2.91E-01

 tran: time= 5.1358E-10 tot_iter=     129 conv_iter=      46 cpu clock= 2.91E-01

 tran: time= 7.3423E-10 tot_iter=     135 conv_iter=      49 cpu clock= 2.91E-01

 tran: time= 9.0423E-10 tot_iter=     139 conv_iter=      51 cpu clock= 2.91E-01

 tran: time= 1.0742E-09 tot_iter=     143 conv_iter=      53 cpu clock= 2.91E-01

 tran: time= 1.2442E-09 tot_iter=     147 conv_iter=      55 cpu clock= 2.91E-01

 tran: time= 1.4142E-09 tot_iter=     151 conv_iter=      57 cpu clock= 2.91E-01

 tran: time= 1.5842E-09 tot_iter=     155 conv_iter=      59 cpu clock= 2.91E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      61 cpu clock= 2.91E-01

 sweep: tran tran0    end, cpu clock= 2.92E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     23:08:56 12/01/2025                               

           job ended   at     23:08:57 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20508 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.60E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.60E-01                     

       establish matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.60E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.66E-01 

 tran: time= 1.7296E-10 tot_iter=      54 conv_iter=      20 cpu clock= 2.68E-01

 tran: time= 3.4014E-10 tot_iter=     105 conv_iter=      37 cpu clock= 2.68E-01

 tran: time= 5.1358E-10 tot_iter=     129 conv_iter=      46 cpu clock= 2.69E-01

 tran: time= 7.3423E-10 tot_iter=     135 conv_iter=      49 cpu clock= 2.69E-01

 tran: time= 9.0423E-10 tot_iter=     139 conv_iter=      51 cpu clock= 2.69E-01

 tran: time= 1.0742E-09 tot_iter=     143 conv_iter=      53 cpu clock= 2.69E-01

 tran: time= 1.2442E-09 tot_iter=     147 conv_iter=      55 cpu clock= 2.69E-01

 tran: time= 1.4142E-09 tot_iter=     151 conv_iter=      57 cpu clock= 2.69E-01

 tran: time= 1.5842E-09 tot_iter=     155 conv_iter=      59 cpu clock= 2.69E-01

 tran: time= 1.7000E-09 tot_iter=     159 conv_iter=      61 cpu clock= 2.69E-01

 sweep: tran tran0    end, cpu clock= 2.69E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:59 12/01/2025                               

           job ended   at     23:08:59 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2076 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.38E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.45E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.45E-01                                  

 init: end check errors, cpu clock= 2.52E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.52E-01                     

       establish matrix -- done, cpu clock= 2.52E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.52E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.54E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.54E-01                                          

 dcop: end dcop, cpu clock= 2.56E-01 peak memory=      74 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.57E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.59E-01

 tran: time= 3.4548E-10 tot_iter=     164 conv_iter=      63 cpu clock= 2.61E-01

 tran: time= 5.1869E-10 tot_iter=     188 conv_iter=      74 cpu clock= 2.61E-01

 tran: time= 7.3956E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.61E-01

 tran: time= 9.0956E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.61E-01

 tran: time= 1.0796E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.61E-01

 tran: time= 1.2496E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.61E-01

 tran: time= 1.4196E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.62E-01

 tran: time= 1.5896E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.62E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.62E-01

 sweep: tran tran0    end, cpu clock= 2.62E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:07 12/02/2025                               

           job ended   at     11:50:08 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14800 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.37E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.43E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.43E-01                                  

 init: end check errors, cpu clock= 2.50E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.50E-01                     

       establish matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.52E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.53E-01                                          

 dcop: end dcop, cpu clock= 2.54E-01 peak memory=      73 mb tot_iter=       7  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\y01PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.56E-01 

 tran: time= 1.7455E-10 tot_iter=      81 conv_iter=      33 cpu clock= 2.57E-01

 tran: time= 3.4548E-10 tot_iter=     164 conv_iter=      63 cpu clock= 2.59E-01

 tran: time= 5.1869E-10 tot_iter=     188 conv_iter=      74 cpu clock= 2.59E-01

 tran: time= 7.3956E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.60E-01

 tran: time= 9.0956E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.60E-01

 tran: time= 1.0796E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.60E-01

 tran: time= 1.2496E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.60E-01

 tran: time= 1.4196E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.60E-01

 tran: time= 1.5896E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.60E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.60E-01

 sweep: tran tran0    end, cpu clock= 2.60E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:50:11 12/02/2025                               

           job ended   at     11:50:11 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
