

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14524 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.77E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.82E-01 

 tran: time= 1.7774E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.83E-01

 tran: time= 3.4081E-10 tot_iter=     116 conv_iter=      40 cpu clock= 2.84E-01

 tran: time= 5.3125E-10 tot_iter=     133 conv_iter=      47 cpu clock= 2.85E-01

 tran: time= 7.0125E-10 tot_iter=     137 conv_iter=      49 cpu clock= 2.85E-01

 tran: time= 8.7125E-10 tot_iter=     141 conv_iter=      51 cpu clock= 2.85E-01

 tran: time= 1.0413E-09 tot_iter=     145 conv_iter=      53 cpu clock= 2.85E-01

 tran: time= 1.2113E-09 tot_iter=     149 conv_iter=      55 cpu clock= 2.85E-01

 tran: time= 1.3813E-09 tot_iter=     153 conv_iter=      57 cpu clock= 2.85E-01

 tran: time= 1.5513E-09 tot_iter=     157 conv_iter=      59 cpu clock= 2.85E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      61 cpu clock= 2.85E-01

 sweep: tran tran0    end, cpu clock= 2.85E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     23:08:55 12/01/2025                               

           job ended   at     23:08:56 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18280 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.69E-01 

 tran: time= 1.7774E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.71E-01

 tran: time= 3.4081E-10 tot_iter=     116 conv_iter=      40 cpu clock= 2.72E-01

 tran: time= 5.3125E-10 tot_iter=     133 conv_iter=      47 cpu clock= 2.72E-01

 tran: time= 7.0125E-10 tot_iter=     137 conv_iter=      49 cpu clock= 2.72E-01

 tran: time= 8.7125E-10 tot_iter=     141 conv_iter=      51 cpu clock= 2.72E-01

 tran: time= 1.0413E-09 tot_iter=     145 conv_iter=      53 cpu clock= 2.72E-01

 tran: time= 1.2113E-09 tot_iter=     149 conv_iter=      55 cpu clock= 2.72E-01

 tran: time= 1.3813E-09 tot_iter=     153 conv_iter=      57 cpu clock= 2.72E-01

 tran: time= 1.5513E-09 tot_iter=     157 conv_iter=      59 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      61 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:58 12/01/2025                               

           job ended   at     23:08:58 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13012 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.57E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.63E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.64E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.64E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.64E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.64E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.65E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.65E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.65E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:06 12/02/2025                               

           job ended   at     11:50:07 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19980 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.36E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.43E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.43E-01                                  

 init: end check errors, cpu clock= 2.50E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.50E-01                     

       establish matrix -- done, cpu clock= 2.50E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.52E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.52E-01                                          

 dcop: end dcop, cpu clock= 2.53E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.55E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.57E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.59E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.59E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.59E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.59E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.59E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.59E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.59E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.59E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.59E-01

 sweep: tran tran0    end, cpu clock= 2.60E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:50:10 12/02/2025                               

           job ended   at     11:50:10 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20872 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.64E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.71E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.71E-01                                  

 init: end check errors, cpu clock= 2.79E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.79E-01                     

       establish matrix -- done, cpu clock= 2.79E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.79E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.81E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.81E-01                                          

 dcop: end dcop, cpu clock= 2.82E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.84E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.86E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.88E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.88E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.88E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.88E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.88E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.89E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.89E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.89E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.89E-01

 sweep: tran tran0    end, cpu clock= 2.89E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:09:24 12/06/2025                               

           job ended   at     00:09:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14844 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.61E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.68E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.68E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.76E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.76E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.78E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.78E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.81E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.83E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.85E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.86E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.86E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.86E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.86E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.86E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.86E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.86E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.86E-01

 sweep: tran tran0    end, cpu clock= 2.86E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:09:27 12/06/2025                               

           job ended   at     00:09:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21008 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.69E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.69E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.76E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.76E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.76E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.77E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.77E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.77E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.77E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.77E-01

 sweep: tran tran0    end, cpu clock= 2.77E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:21:47 12/06/2025                               

           job ended   at     00:21:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.49E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.49E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.57E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.57E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.59E-01                                          

 dcop: end dcop, cpu clock= 2.60E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.62E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.63E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.65E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.65E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.65E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.65E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.65E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.66E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.66E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.66E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.66E-01

 sweep: tran tran0    end, cpu clock= 2.66E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:21:50 12/06/2025                               

           job ended   at     00:21:50 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13704 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.53E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.53E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.61E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.62E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.66E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.68E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.69E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.69E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.70E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.70E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.70E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.70E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.70E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.70E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.70E-01

 sweep: tran tran0    end, cpu clock= 2.70E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:29:48 12/06/2025                               

           job ended   at     00:29:48 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11724 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.42E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.56E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.56E-01                     

       establish matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.56E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.58E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.58E-01                                          

 dcop: end dcop, cpu clock= 2.60E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.63E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.65E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.65E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.65E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.65E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.65E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.66E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.66E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.66E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.66E-01

 sweep: tran tran0    end, cpu clock= 2.66E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     00:29:52 12/06/2025                               

           job ended   at     00:29:52 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15748 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.54E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.54E-01                                  

 init: end check errors, cpu clock= 2.61E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.61E-01                     

       establish matrix -- done, cpu clock= 2.61E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.62E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.63E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.63E-01                                          

 dcop: end dcop, cpu clock= 2.64E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.67E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.69E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.71E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.71E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.71E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.71E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.71E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.71E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.72E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.72E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:30:46 12/06/2025                               

           job ended   at     00:30:46 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12124 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      75 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.78E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.80E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.82E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.82E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.82E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.82E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.82E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.83E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.83E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.83E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:30:49 12/06/2025                               

           job ended   at     00:30:49 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1764 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.76E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.78E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.80E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.82E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.84E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.84E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.84E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.84E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.84E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.84E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.84E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.84E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.84E-01

 sweep: tran tran0    end, cpu clock= 2.85E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:46:24 12/06/2025                               

           job ended   at     00:46:24 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.11E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.11E-01                                  

 init: end check errors, cpu clock= 3.18E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.18E-01                     

       establish matrix -- done, cpu clock= 3.18E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.19E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.20E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.21E-01                                          

 dcop: end dcop, cpu clock= 3.22E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.24E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 3.26E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 3.27E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 3.28E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 3.28E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 3.28E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 3.28E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 3.28E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 3.28E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 3.28E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 3.28E-01

 sweep: tran tran0    end, cpu clock= 3.28E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.35 seconds                           

           job started at     00:46:27 12/06/2025                               

           job ended   at     00:46:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2376 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.55E-01                                  

 init: end check errors, cpu clock= 3.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.63E-01                     

       establish matrix -- done, cpu clock= 3.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 3.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 3.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 3.65E-01                                          

 dcop: end dcop, cpu clock= 3.66E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.68E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 3.70E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 3.73E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 3.74E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 3.74E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 3.74E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 3.74E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 3.74E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 3.74E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 3.74E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 3.74E-01

 sweep: tran tran0    end, cpu clock= 3.74E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.39 seconds                           

           job started at     00:49:27 12/06/2025                               

           job ended   at     00:49:27 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13928 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.76E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.77E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.77E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.77E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.78E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.78E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.78E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:49:31 12/06/2025                               

           job ended   at     00:49:31 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12796 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.71E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.78E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.78E-01                                  

 init: end check errors, cpu clock= 2.87E-01 peak memory=      75 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.87E-01                     

       establish matrix -- done, cpu clock= 2.88E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 2.88E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 2.89E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.90E-01                                          

 dcop: end dcop, cpu clock= 2.91E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.93E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.95E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.96E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.97E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.97E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.97E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.97E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.97E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.97E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.97E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.97E-01

 sweep: tran tran0    end, cpu clock= 2.97E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.31 seconds                           

           job started at     00:53:06 12/06/2025                               

           job ended   at     00:53:07 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1876 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.55E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.55E-01                                  

 init: end check errors, cpu clock= 2.63E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.63E-01                     

       establish matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.63E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.64E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.65E-01                                          

 dcop: end dcop, cpu clock= 2.66E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.68E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.70E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.72E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.72E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.72E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.72E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.72E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.72E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.72E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:53:09 12/06/2025                               

           job ended   at     00:53:09 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2212 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.08E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 3.08E-01                                  

 init: end check errors, cpu clock= 3.15E-01 peak memory=      75 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.15E-01                     

       establish matrix -- done, cpu clock= 3.15E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 3.16E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 3.17E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 3.17E-01                                          

 dcop: end dcop, cpu clock= 3.19E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 3.21E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 3.23E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 3.24E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 3.25E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 3.25E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 3.25E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 3.25E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 3.25E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 3.25E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 3.25E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 3.25E-01

 sweep: tran tran0    end, cpu clock= 3.25E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.34 seconds                           

           job started at     00:55:29 12/06/2025                               

           job ended   at     00:55:29 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10804 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.52E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.59E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.59E-01                                  

 init: end check errors, cpu clock= 2.66E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.66E-01                     

       establish matrix -- done, cpu clock= 2.66E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.67E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.68E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.68E-01                                          

 dcop: end dcop, cpu clock= 2.70E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.71E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.73E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.75E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.75E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.75E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.75E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.75E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.75E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.76E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.76E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.76E-01

 sweep: tran tran0    end, cpu clock= 2.76E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     00:55:31 12/06/2025                               

           job ended   at     00:55:32 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18836 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.50E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.57E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.57E-01                                  

 init: end check errors, cpu clock= 2.65E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.65E-01                     

       establish matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.65E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.67E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.67E-01                                          

 dcop: end dcop, cpu clock= 2.68E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.71E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.73E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.74E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.75E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.75E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.75E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.75E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.75E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.75E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.75E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.75E-01

 sweep: tran tran0    end, cpu clock= 2.75E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:30 12/06/2025                               

           job ended   at     00:56:30 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.53E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.68E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.70E-01                                          

 dcop: end dcop, cpu clock= 2.71E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.73E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.75E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.77E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.77E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.77E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.77E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.77E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.77E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.77E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     00:56:32 12/06/2025                               

           job ended   at     00:56:33 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12824 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.69E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.70E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.72E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.72E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.73E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.73E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.73E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.73E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.73E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.73E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.73E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:42 12/06/2025                               

           job ended   at     01:01:42 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15440 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.54E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.60E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.60E-01                                  

 init: end check errors, cpu clock= 2.68E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.68E-01                     

       establish matrix -- done, cpu clock= 2.69E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.69E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.70E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.71E-01                                          

 dcop: end dcop, cpu clock= 2.72E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.74E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.76E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.77E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.78E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.78E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.78E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.78E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.78E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.78E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.78E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.78E-01

 sweep: tran tran0    end, cpu clock= 2.78E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:01:45 12/06/2025                               

           job ended   at     01:01:45 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15628 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.57E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.64E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.64E-01                                  

 init: end check errors, cpu clock= 2.72E-01 peak memory=      75 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.72E-01                     

       establish matrix -- done, cpu clock= 2.72E-01 peak memory=      75 mb    

       re-order matrix -- done, cpu clock= 2.72E-01 peak memory=      75 mb     

 init: end setup matrix, cpu clock= 2.73E-01 peak memory=      75 mb            

 dcop: begin dcop, cpu clock= 2.74E-01                                          

 dcop: end dcop, cpu clock= 2.75E-01 peak memory=      75 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.77E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.79E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.80E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.81E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.81E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.81E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.81E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.81E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.81E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.81E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.81E-01

 sweep: tran tran0    end, cpu clock= 2.81E-01 peak memory=      75 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     01:20:43 12/06/2025                               

           job ended   at     01:20:44 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.spi 

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2284 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.58E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.73E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.73E-01                     

       establish matrix -- done, cpu clock= 2.73E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.74E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.77E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\power_out\z00PAD.out.tr0 

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.79E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.80E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.82E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.82E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.82E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.82E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.83E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.83E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.83E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.83E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.83E-01

 sweep: tran tran0    end, cpu clock= 2.83E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.21 seconds                               

           total elapsed time            0.30 seconds                           

           job started at     01:20:47 12/06/2025                               

           job ended   at     01:20:47 12/06/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
