

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14524 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.67E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.67E-01                                  

 init: end check errors, cpu clock= 2.75E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.75E-01                     

       establish matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.77E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.77E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.82E-01 

 tran: time= 1.7774E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.83E-01

 tran: time= 3.4081E-10 tot_iter=     116 conv_iter=      40 cpu clock= 2.84E-01

 tran: time= 5.3125E-10 tot_iter=     133 conv_iter=      47 cpu clock= 2.85E-01

 tran: time= 7.0125E-10 tot_iter=     137 conv_iter=      49 cpu clock= 2.85E-01

 tran: time= 8.7125E-10 tot_iter=     141 conv_iter=      51 cpu clock= 2.85E-01

 tran: time= 1.0413E-09 tot_iter=     145 conv_iter=      53 cpu clock= 2.85E-01

 tran: time= 1.2113E-09 tot_iter=     149 conv_iter=      55 cpu clock= 2.85E-01

 tran: time= 1.3813E-09 tot_iter=     153 conv_iter=      57 cpu clock= 2.85E-01

 tran: time= 1.5513E-09 tot_iter=     157 conv_iter=      59 cpu clock= 2.85E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      61 cpu clock= 2.85E-01

 sweep: tran tran0    end, cpu clock= 2.85E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.18 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     23:08:55 12/01/2025                               

           job ended   at     23:08:56 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18280 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.56E-01 peak memory=      73 mb      

 init: begin check errors, cpu clock= 2.56E-01                                  

 init: end check errors, cpu clock= 2.64E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.64E-01                     

       establish matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.64E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.65E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.66E-01                                          

 dcop: end dcop, cpu clock= 2.67E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps= 101 cpu clock= 2.69E-01 

 tran: time= 1.7774E-10 tot_iter=      57 conv_iter=      21 cpu clock= 2.71E-01

 tran: time= 3.4081E-10 tot_iter=     116 conv_iter=      40 cpu clock= 2.72E-01

 tran: time= 5.3125E-10 tot_iter=     133 conv_iter=      47 cpu clock= 2.72E-01

 tran: time= 7.0125E-10 tot_iter=     137 conv_iter=      49 cpu clock= 2.72E-01

 tran: time= 8.7125E-10 tot_iter=     141 conv_iter=      51 cpu clock= 2.72E-01

 tran: time= 1.0413E-09 tot_iter=     145 conv_iter=      53 cpu clock= 2.72E-01

 tran: time= 1.2113E-09 tot_iter=     149 conv_iter=      55 cpu clock= 2.72E-01

 tran: time= 1.3813E-09 tot_iter=     153 conv_iter=      57 cpu clock= 2.72E-01

 tran: time= 1.5513E-09 tot_iter=     157 conv_iter=      59 cpu clock= 2.72E-01

 tran: time= 1.7000E-09 tot_iter=     161 conv_iter=      61 cpu clock= 2.72E-01

 sweep: tran tran0    end, cpu clock= 2.73E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.27 seconds                           

           job started at     23:08:58 12/01/2025                               

           job ended   at     23:08:58 12/01/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13012 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.41E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.48E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.48E-01                                  

 init: end check errors, cpu clock= 2.55E-01 peak memory=      74 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.55E-01                     

       establish matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb    

       re-order matrix -- done, cpu clock= 2.55E-01 peak memory=      74 mb     

 init: end setup matrix, cpu clock= 2.57E-01 peak memory=      74 mb            

 dcop: begin dcop, cpu clock= 2.57E-01                                          

 dcop: end dcop, cpu clock= 2.59E-01 peak memory=      74 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.61E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.63E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.64E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.64E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.64E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.64E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.65E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.65E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.65E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.65E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.65E-01

 sweep: tran tran0    end, cpu clock= 2.65E-01 peak memory=      74 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.19 seconds                               

           total elapsed time            0.28 seconds                           

           job started at     11:50:06 12/02/2025                               

           job ended   at     11:50:07 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19980 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.36E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option list                                                              

       option node                                                              

       option post                                                              

       option method = gear                                                     

       option gshunt =    1.000E-12                                             

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.43E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 2.43E-01                                  

 init: end check errors, cpu clock= 2.50E-01 peak memory=      73 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.50E-01                     

       establish matrix -- done, cpu clock= 2.50E-01 peak memory=      73 mb    

       re-order matrix -- done, cpu clock= 2.51E-01 peak memory=      73 mb     

 init: end setup matrix, cpu clock= 2.52E-01 peak memory=      73 mb            

 dcop: begin dcop, cpu clock= 2.52E-01                                          

 dcop: end dcop, cpu clock= 2.53E-01 peak memory=      73 mb tot_iter=       5  

 output: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\power_out\z00PAD.out.

 sweep: tran tran0    begin, stop_t=  1.70E-09 #sweeps=4996 cpu clock= 2.55E-01 

 tran: time= 1.7413E-10 tot_iter=      91 conv_iter=      36 cpu clock= 2.57E-01

 tran: time= 3.4171E-10 tot_iter=     172 conv_iter=      66 cpu clock= 2.59E-01

 tran: time= 5.5871E-10 tot_iter=     191 conv_iter=      75 cpu clock= 2.59E-01

 tran: time= 7.2871E-10 tot_iter=     195 conv_iter=      77 cpu clock= 2.59E-01

 tran: time= 8.9871E-10 tot_iter=     199 conv_iter=      79 cpu clock= 2.59E-01

 tran: time= 1.0687E-09 tot_iter=     203 conv_iter=      81 cpu clock= 2.59E-01

 tran: time= 1.2387E-09 tot_iter=     207 conv_iter=      83 cpu clock= 2.59E-01

 tran: time= 1.4087E-09 tot_iter=     211 conv_iter=      85 cpu clock= 2.59E-01

 tran: time= 1.5787E-09 tot_iter=     215 conv_iter=      87 cpu clock= 2.59E-01

 tran: time= 1.7000E-09 tot_iter=     219 conv_iter=      89 cpu clock= 2.59E-01

 sweep: tran tran0    end, cpu clock= 2.60E-01 peak memory=      73 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.20 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     11:50:10 12/02/2025                               

           job ended   at     11:50:10 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
