

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16244 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.63E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.76E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.76E-01                                  

 init: end check errors, cpu clock= 2.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.04E-01                     

       establish matrix -- done, cpu clock= 2.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.08E-01                                          

 dcop: end dcop, cpu clock= 2.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.13E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 2.15E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 2.15E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 2.16E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 2.16E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 2.16E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 2.16E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 2.16E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 2.16E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 2.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 2.16E-01

 sweep: tran tran0    end, cpu clock= 2.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.09 seconds                               

           total elapsed time            0.22 seconds                           

           job started at     23:28:54 11/13/2025                               

           job ended   at     23:28:54 11/13/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
