

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20564 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     12:23:46 11/15/2025                               

           job ended   at     12:23:46 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.52E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.52E-01                                  

 init: end check errors, cpu clock= 1.69E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.69E-01                     

       establish matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.71E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.72E-01                                          

 dcop: end dcop, cpu clock= 1.76E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.78E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.79E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.79E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.79E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.79E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.80E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.80E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.80E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.80E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.80E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.80E-01

 sweep: tran tran0    end, cpu clock= 1.80E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     12:54:35 11/15/2025                               

           job ended   at     12:54:35 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10756 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.23E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.26E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.26E-01                                  

 init: end check errors, cpu clock= 1.28E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.28E-01                     

       establish matrix -- done, cpu clock= 1.29E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.29E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.29E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.29E-01                                          

 dcop: end dcop, cpu clock= 1.31E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.32E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.33E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.34E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.34E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.34E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.34E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.34E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.34E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.35E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.35E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.35E-01

 sweep: tran tran0    end, cpu clock= 1.35E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     13:37:52 11/15/2025                               

           job ended   at     13:37:52 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10728 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:25:23 11/15/2025                               

           job ended   at     22:25:23 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8264 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:36 11/15/2025                               

           job ended   at     22:40:36 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1800 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:14 11/15/2025                               

           job ended   at     22:54:14 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14652 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.74E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.87E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.87E-01                                  

 init: end check errors, cpu clock= 2.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.14E-01                     

       establish matrix -- done, cpu clock= 2.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.16E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.17E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.18E-01                                          

 dcop: end dcop, cpu clock= 2.22E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.24E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 2.26E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 2.26E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 2.26E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 2.26E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 2.27E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 2.27E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 2.27E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 2.27E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 2.27E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 2.27E-01

 sweep: tran tran0    end, cpu clock= 2.27E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.09 seconds                               

           total elapsed time            0.23 seconds                           

           job started at     09:08:53 11/16/2025                               

           job ended   at     09:08:53 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13208 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.07E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:26 11/16/2025                               

           job ended   at     09:17:26 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22388 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:31 11/16/2025                               

           job ended   at     09:17:31 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6240 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:28:10 11/16/2025                               

           job ended   at     09:28:10 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20368 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:14 11/16/2025                               

           job ended   at     09:28:14 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22400 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.09E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.12E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.12E-01                                  

 init: end check errors, cpu clock= 1.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.14E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.16E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.19E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.19E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.19E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.19E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.19E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:56:01 11/16/2025                               

           job ended   at     09:56:01 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:56:04 11/16/2025                               

           job ended   at     09:56:04 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14104 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.01E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.02E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.02E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:18:01 11/16/2025                               

           job ended   at     10:18:01 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.15E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.17E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.17E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.18E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.18E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:18:05 11/16/2025                               

           job ended   at     10:18:05 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19804 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.13E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:27 11/16/2025                               

           job ended   at     10:21:27 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5104 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.16E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.19E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.19E-01                                  

 init: end check errors, cpu clock= 1.23E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.23E-01                     

       establish matrix -- done, cpu clock= 1.23E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.23E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.23E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.24E-01                                          

 dcop: end dcop, cpu clock= 1.25E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.27E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.28E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.29E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.29E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.29E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.30E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.30E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.30E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.30E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.31E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.31E-01

 sweep: tran tran0    end, cpu clock= 1.31E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     10:21:31 11/16/2025                               

           job ended   at     10:21:31 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21292 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.17E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.17E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:48 11/16/2025                               

           job ended   at     10:49:48 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14264 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:49:51 11/16/2025                               

           job ended   at     10:49:51 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21816 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:56:42 11/16/2025                               

           job ended   at     10:56:42 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11436 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:45 11/16/2025                               

           job ended   at     10:56:45 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5908 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.30E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.38E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.38E-01                                  

 init: end check errors, cpu clock= 1.56E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.56E-01                     

       establish matrix -- done, cpu clock= 1.57E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.57E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.58E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.59E-01                                          

 dcop: end dcop, cpu clock= 1.62E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.64E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.65E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.65E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.65E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.65E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.66E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.66E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.66E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.66E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.66E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.66E-01

 sweep: tran tran0    end, cpu clock= 1.66E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.17 seconds                           

           job started at     11:02:31 11/16/2025                               

           job ended   at     11:02:31 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3868 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:34 11/16/2025                               

           job ended   at     11:02:34 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.40E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.49E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.49E-01                                  

 init: end check errors, cpu clock= 1.65E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.65E-01                     

       establish matrix -- done, cpu clock= 1.66E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.66E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.67E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.68E-01                                          

 dcop: end dcop, cpu clock= 1.71E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.73E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.74E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.74E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.74E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.75E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.75E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.75E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.75E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.75E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.75E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.75E-01

 sweep: tran tran0    end, cpu clock= 1.75E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     11:04:32 11/16/2025                               

           job ended   at     11:04:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9820 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.08E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.08E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.08E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.08E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:35 11/16/2025                               

           job ended   at     11:04:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22452 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:40 11/16/2025                               

           job ended   at     11:12:40 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:12:43 11/16/2025                               

           job ended   at     11:12:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15744 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:21:42 11/16/2025                               

           job ended   at     11:21:42 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9736 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:45 11/16/2025                               

           job ended   at     11:21:45 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7976 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:26 11/16/2025                               

           job ended   at     11:34:26 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17908 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.11E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:29 11/16/2025                               

           job ended   at     11:34:29 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16772 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.13E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:15:06 11/16/2025                               

           job ended   at     13:15:06 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19184 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.00E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.01E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.01E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.01E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.01E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.01E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     13:15:09 11/16/2025                               

           job ended   at     13:15:09 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4436 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.17E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.18E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.18E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.18E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.19E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:26:24 11/17/2025                               

           job ended   at     10:26:24 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20064 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:26:27 11/17/2025                               

           job ended   at     10:26:27 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6112 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.60E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.60E-02                     

       establish matrix -- done, cpu clock= 9.60E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 9.90E-02 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.00E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.00E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.01E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.01E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.01E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.01E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.01E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.01E-01

 sweep: tran tran0    end, cpu clock= 1.01E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:29:58 11/17/2025                               

           job ended   at     10:29:58 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15276 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:30:02 11/17/2025                               

           job ended   at     10:30:02 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
