

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20564 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     12:23:46 11/15/2025                               

           job ended   at     12:23:46 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.52E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.52E-01                                  

 init: end check errors, cpu clock= 1.69E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.69E-01                     

       establish matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.71E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.72E-01                                          

 dcop: end dcop, cpu clock= 1.76E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.78E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.79E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.79E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.79E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.79E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.80E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.80E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.80E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.80E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.80E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.80E-01

 sweep: tran tran0    end, cpu clock= 1.80E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     12:54:35 11/15/2025                               

           job ended   at     12:54:35 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\a01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10756 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.23E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.26E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.26E-01                                  

 init: end check errors, cpu clock= 1.28E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.28E-01                     

       establish matrix -- done, cpu clock= 1.29E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.29E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.29E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.29E-01                                          

 dcop: end dcop, cpu clock= 1.31E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.32E-01 

 tran: time= 3.0772E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.33E-01

 tran: time= 6.0772E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.34E-01

 tran: time= 9.0772E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.34E-01

 tran: time= 1.2077E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.34E-01

 tran: time= 1.5645E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.34E-01

 tran: time= 1.9356E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.34E-01

 tran: time= 2.2356E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.34E-01

 tran: time= 2.5356E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.35E-01

 tran: time= 2.8356E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.35E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.35E-01

 sweep: tran tran0    end, cpu clock= 1.35E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     13:37:52 11/15/2025                               

           job ended   at     13:37:52 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
