

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13344 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.05E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:47 11/15/2025                               

           job ended   at     12:23:47 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12500 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.11E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.11E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.11E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.11E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.12E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.12E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.12E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:54:36 11/15/2025                               

           job ended   at     12:54:36 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17956 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.13E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.13E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.13E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.14E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     13:37:53 11/15/2025                               

           job ended   at     13:37:53 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16724 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.09E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.20E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.20E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.20E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.20E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.20E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.20E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.21E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.21E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.21E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:25:23 11/15/2025                               

           job ended   at     22:25:23 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1600 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:36 11/15/2025                               

           job ended   at     22:40:36 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.14E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:15 11/15/2025                               

           job ended   at     22:54:15 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18280 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.15E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.15E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:08:53 11/16/2025                               

           job ended   at     09:08:53 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12456 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.09E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.10E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.10E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.10E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.10E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:26 11/16/2025                               

           job ended   at     09:17:26 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17088 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.02E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.02E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.02E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.03E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:31 11/16/2025                               

           job ended   at     09:17:32 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20240 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:28:11 11/16/2025                               

           job ended   at     09:28:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13816 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.05E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.05E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.05E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.05E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:14 11/16/2025                               

           job ended   at     09:28:15 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16552 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.11E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.11E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.12E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.12E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.12E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.12E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.12E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:01 11/16/2025                               

           job ended   at     09:56:01 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18024 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:05 11/16/2025                               

           job ended   at     09:56:05 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19804 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.16E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.17E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.17E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.17E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.17E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:18:02 11/16/2025                               

           job ended   at     10:18:02 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9000 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.06E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.08E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.09E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.09E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.09E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.09E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.09E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:06 11/16/2025                               

           job ended   at     10:18:06 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12652 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.06E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.06E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:27 11/16/2025                               

           job ended   at     10:21:27 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16268 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.42E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.42E-01                                  

 init: end check errors, cpu clock= 1.44E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.44E-01                     

       establish matrix -- done, cpu clock= 1.45E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.45E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.45E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.45E-01                                          

 dcop: end dcop, cpu clock= 1.47E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.49E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.50E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.50E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.51E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.51E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.51E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.51E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.52E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.52E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.52E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.52E-01

 sweep: tran tran0    end, cpu clock= 1.52E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.15 seconds                           

           job started at     10:21:32 11/16/2025                               

           job ended   at     10:21:32 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18280 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.17E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.17E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.17E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.17E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.17E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:48 11/16/2025                               

           job ended   at     10:49:48 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17444 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.03E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:49:51 11/16/2025                               

           job ended   at     10:49:51 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21044 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.13E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.16E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.16E-01                                  

 init: end check errors, cpu clock= 1.19E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.19E-01                     

       establish matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.19E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.19E-01                                          

 dcop: end dcop, cpu clock= 1.21E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.23E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.23E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.23E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.24E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.24E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.24E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.24E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.24E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.24E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.24E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.24E-01

 sweep: tran tran0    end, cpu clock= 1.25E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     10:56:42 11/16/2025                               

           job ended   at     10:56:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13136 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.05E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:45 11/16/2025                               

           job ended   at     10:56:45 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1296 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.14E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.14E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:02:31 11/16/2025                               

           job ended   at     11:02:31 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14520 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.07E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.07E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.07E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:35 11/16/2025                               

           job ended   at     11:02:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14416 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:33 11/16/2025                               

           job ended   at     11:04:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22060 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:36 11/16/2025                               

           job ended   at     11:04:36 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12576 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.10E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.10E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.10E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.11E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.11E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.11E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:12:41 11/16/2025                               

           job ended   at     11:12:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17012 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.15E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:44 11/16/2025                               

           job ended   at     11:12:44 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16868 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.16E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.16E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.16E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.16E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.17E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:21:43 11/16/2025                               

           job ended   at     11:21:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15308 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:46 11/16/2025                               

           job ended   at     11:21:46 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2860 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.19E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.19E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.19E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.20E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.20E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.20E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:26 11/16/2025                               

           job ended   at     11:34:26 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14700 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.03E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:29 11/16/2025                               

           job ended   at     11:34:29 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16832 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.52E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.52E-01                                  

 init: end check errors, cpu clock= 1.68E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.68E-01                     

       establish matrix -- done, cpu clock= 1.69E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.69E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.69E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.70E-01                                          

 dcop: end dcop, cpu clock= 1.73E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.74E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.76E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.76E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.76E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.76E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.76E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.76E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.77E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.77E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.77E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.77E-01

 sweep: tran tran0    end, cpu clock= 1.77E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     13:15:07 11/16/2025                               

           job ended   at     13:15:07 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15236 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.05E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:15:10 11/16/2025                               

           job ended   at     13:15:10 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15420 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.16E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.18E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.18E-01                                  

 init: end check errors, cpu clock= 1.21E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.21E-01                     

       establish matrix -- done, cpu clock= 1.21E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.21E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.21E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.22E-01                                          

 dcop: end dcop, cpu clock= 1.23E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.25E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.26E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.26E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.27E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.27E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.27E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.27E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.28E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.28E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.28E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.28E-01

 sweep: tran tran0    end, cpu clock= 1.28E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     10:26:25 11/17/2025                               

           job ended   at     10:26:25 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11884 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.07E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.07E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.07E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:26:28 11/17/2025                               

           job ended   at     10:26:28 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14176 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:29:59 11/17/2025                               

           job ended   at     10:29:59 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17180 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.02E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.02E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.02E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.02E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.02E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.02E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:30:03 11/17/2025                               

           job ended   at     10:30:03 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3000 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.15E-01

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.15E-01

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.16E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.16E-01

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:48:22 11/17/2025                               

           job ended   at     10:48:22 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3780 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.00E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.30E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.30E-02                                  

 init: end check errors, cpu clock= 9.50E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.50E-02                     

       establish matrix -- done, cpu clock= 9.50E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.50E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.50E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.50E-02                                          

 dcop: end dcop, cpu clock= 9.70E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 9.80E-02 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 9.90E-02

 tran: time= 6.6517E-10 tot_iter=      36 conv_iter=      15 cpu clock= 9.90E-02

 tran: time= 9.6517E-10 tot_iter=      42 conv_iter=      17 cpu clock= 9.90E-02

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 9.90E-02

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 9.90E-02

 tran: time= 1.8061E-09 tot_iter=      63 conv_iter=      23 cpu clock= 9.90E-02

 tran: time= 2.2225E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.00E-01

 tran: time= 2.5225E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.00E-01

 tran: time= 2.8225E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.00E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.00E-01

 sweep: tran tran0    end, cpu clock= 1.00E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:48:25 11/17/2025                               

           job ended   at     10:48:25 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
