

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b02out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15072 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 6.6518E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.13E-01

 tran: time= 9.6518E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.14E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8068E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.14E-01

 tran: time= 2.2218E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5218E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8218E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:08:55 11/16/2025                               

           job ended   at     09:08:55 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b02out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10912 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.01E-01

 tran: time= 6.6518E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.01E-01

 tran: time= 9.6518E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.02E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.02E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.02E-01

 tran: time= 1.8068E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.02E-01

 tran: time= 2.2218E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.5218E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 2.8218E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     09:17:28 11/16/2025                               

           job ended   at     09:17:28 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\b02out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15124 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.7279E-10 tot_iter=      30 conv_iter=      13 cpu clock= 1.05E-01

 tran: time= 6.6518E-10 tot_iter=      36 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 9.6518E-10 tot_iter=      42 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.2652E-09 tot_iter=      48 conv_iter=      19 cpu clock= 1.06E-01

 tran: time= 1.5652E-09 tot_iter=      55 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.8068E-09 tot_iter=      63 conv_iter=      23 cpu clock= 1.06E-01

 tran: time= 2.2218E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5218E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8218E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      32 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:33 11/16/2025                               

           job ended   at     09:17:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
