

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1268 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.17E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.20E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.20E-01                                  

 init: end check errors, cpu clock= 1.22E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.22E-01                     

       establish matrix -- done, cpu clock= 1.22E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.23E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.23E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.23E-01                                          

 dcop: end dcop, cpu clock= 1.24E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.25E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.26E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.26E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.26E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.26E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.27E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.27E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.27E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.27E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.27E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.27E-01

 sweep: tran tran0    end, cpu clock= 1.27E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     21:22:15 11/02/2025                               

           job ended   at     21:22:15 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15748 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.12E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.12E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:27:44 11/02/2025                               

           job ended   at     21:27:44 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5996 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.30E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.33E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.33E-01                                  

 init: end check errors, cpu clock= 1.35E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.35E-01                     

       establish matrix -- done, cpu clock= 1.35E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.36E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.36E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.36E-01                                          

 dcop: end dcop, cpu clock= 1.37E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.39E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.40E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.40E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.40E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.41E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.41E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.41E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.41E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.42E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.42E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.42E-01

 sweep: tran tran0    end, cpu clock= 1.42E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     21:33:10 11/02/2025                               

           job ended   at     21:33:10 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14864 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.19E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.19E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.19E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.19E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.19E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     08:09:47 11/03/2025                               

           job ended   at     08:09:48 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      24144 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     08:15:40 11/03/2025                               

           job ended   at     08:15:40 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14044 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:04:33 11/05/2025                               

           job ended   at     09:04:33 11/05/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18600 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     18:23:55 11/07/2025                               

           job ended   at     18:23:55 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8396 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:28:58 11/07/2025                               

           job ended   at     18:28:58 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10592 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.13E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     01:50:26 11/10/2025                               

           job ended   at     01:50:26 11/10/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      384 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.06E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.08E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.08E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.08E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.08E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.08E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     22:22:26 11/11/2025                               

           job ended   at     22:22:26 11/11/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
