

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11236 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     12:23:47 11/15/2025                               

           job ended   at     12:23:47 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10956 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     12:54:36 11/15/2025                               

           job ended   at     12:54:36 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20748 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:37:53 11/15/2025                               

           job ended   at     13:37:53 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13916 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.12E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.12E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.20E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.20E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.20E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.20E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.20E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.21E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:25:24 11/15/2025                               

           job ended   at     22:25:24 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17240 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:37 11/15/2025                               

           job ended   at     22:40:37 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11636 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:16 11/15/2025                               

           job ended   at     22:54:17 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6096 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.16E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:08:54 11/16/2025                               

           job ended   at     09:08:54 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14652 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:27 11/16/2025                               

           job ended   at     09:17:27 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4392 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:32 11/16/2025                               

           job ended   at     09:17:32 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8204 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.12E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:12 11/16/2025                               

           job ended   at     09:28:12 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17544 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     09:28:15 11/16/2025                               

           job ended   at     09:28:15 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9476 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:56:02 11/16/2025                               

           job ended   at     09:56:02 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12792 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:05 11/16/2025                               

           job ended   at     09:56:05 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18540 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:18:03 11/16/2025                               

           job ended   at     10:18:03 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12360 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.09E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:06 11/16/2025                               

           job ended   at     10:18:07 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9996 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:28 11/16/2025                               

           job ended   at     10:21:28 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.27E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.31E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 2.31E-01                                  

 init: end check errors, cpu clock= 2.34E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.34E-01                     

       establish matrix -- done, cpu clock= 2.34E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.35E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.35E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.35E-01                                          

 dcop: end dcop, cpu clock= 2.37E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.39E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 2.41E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 2.41E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 2.41E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 2.41E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 2.42E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 2.42E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 2.42E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 2.42E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 2.42E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 2.43E-01

 sweep: tran tran0    end, cpu clock= 2.43E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.24 seconds                           

           job started at     10:21:33 11/16/2025                               

           job ended   at     10:21:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11108 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.11E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.16E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.20E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.20E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.20E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.20E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.20E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.20E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.21E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.21E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.21E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.21E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:49 11/16/2025                               

           job ended   at     10:49:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22072 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:52 11/16/2025                               

           job ended   at     10:49:52 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18864 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.15E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.17E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.18E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.18E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.18E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.19E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.19E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:56:43 11/16/2025                               

           job ended   at     10:56:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10132 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:46 11/16/2025                               

           job ended   at     10:56:46 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10236 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:32 11/16/2025                               

           job ended   at     11:02:32 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16520 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.37E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.46E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.46E-01                                  

 init: end check errors, cpu clock= 1.63E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.63E-01                     

       establish matrix -- done, cpu clock= 1.64E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.65E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.65E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.66E-01                                          

 dcop: end dcop, cpu clock= 1.69E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.71E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.72E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.72E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.72E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.73E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.73E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.73E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.73E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.73E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.73E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.73E-01

 sweep: tran tran0    end, cpu clock= 1.74E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     11:02:35 11/16/2025                               

           job ended   at     11:02:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22356 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.14E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.17E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.17E-01                                  

 init: end check errors, cpu clock= 1.19E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.19E-01                     

       establish matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.19E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.20E-01                                          

 dcop: end dcop, cpu clock= 1.21E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.23E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.23E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.23E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.24E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.24E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.24E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.24E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.24E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.24E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.24E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.24E-01

 sweep: tran tran0    end, cpu clock= 1.25E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     11:04:33 11/16/2025                               

           job ended   at     11:04:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21148 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:36 11/16/2025                               

           job ended   at     11:04:36 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20068 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.17E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:41 11/16/2025                               

           job ended   at     11:12:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6768 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:12:44 11/16/2025                               

           job ended   at     11:12:44 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2532 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.60E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.60E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.00E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.00E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.01E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.01E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.01E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.01E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.01E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.01E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:21:43 11/16/2025                               

           job ended   at     11:21:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16584 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:21:46 11/16/2025                               

           job ended   at     11:21:46 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5772 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:27 11/16/2025                               

           job ended   at     11:34:27 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8640 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:34:30 11/16/2025                               

           job ended   at     11:34:30 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7784 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     13:15:07 11/16/2025                               

           job ended   at     13:15:07 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17040 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.01E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.01E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.01E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.01E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.02E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.02E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     13:15:10 11/16/2025                               

           job ended   at     13:15:10 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17412 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.14E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.19E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.19E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.19E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.19E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.20E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:26:25 11/17/2025                               

           job ended   at     10:26:25 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13404 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.71E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.85E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.85E-01                                  

 init: end check errors, cpu clock= 2.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.15E-01                     

       establish matrix -- done, cpu clock= 2.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.17E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.17E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.20E-01                                          

 dcop: end dcop, cpu clock= 2.23E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.26E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 2.27E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 2.27E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 2.28E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 2.28E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 2.28E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 2.28E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 2.28E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 2.28E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 2.28E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 2.29E-01

 sweep: tran tran0    end, cpu clock= 2.29E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.10 seconds                               

           total elapsed time            0.23 seconds                           

           job started at     10:26:28 11/17/2025                               

           job ended   at     10:26:29 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10564 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:29:59 11/17/2025                               

           job ended   at     10:29:59 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18388 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.01E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.01E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.01E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.01E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.01E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.01E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:30:04 11/17/2025                               

           job ended   at     10:30:04 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.11E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:48:22 11/17/2025                               

           job ended   at     10:48:22 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\c01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11844 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0219E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.0219E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.0219E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2022E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5061E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.04E-01

 tran: time= 1.8998E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.1998E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.4998E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.7998E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:48:25 11/17/2025                               

           job ended   at     10:48:25 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
