

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11396 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.05E-01                       

 sweep: dc dc0    end, cpu clock= 1.12E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:41 11/15/2025                               

           job ended   at     12:23:41 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21220 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.10E-01                       

 sweep: dc dc0    end, cpu clock= 1.17E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     12:54:29 11/15/2025                               

           job ended   at     12:54:29 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6452 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.03E-01                       

 sweep: dc dc0    end, cpu clock= 1.10E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:37:46 11/15/2025                               

           job ended   at     13:37:46 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14380 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.12E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.16E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.16E-01                     

       establish matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.17E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.17E-01                       

 sweep: dc dc0    end, cpu clock= 1.24E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     22:25:17 11/15/2025                               

           job ended   at     22:25:17 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18752 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.11E-01                       

 sweep: dc dc0    end, cpu clock= 1.18E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:30 11/15/2025                               

           job ended   at     22:40:30 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12120 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.13E-01                       

 sweep: dc dc0    end, cpu clock= 1.20E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:08 11/15/2025                               

           job ended   at     22:54:08 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2172 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.09E-01                       

 sweep: dc dc0    end, cpu clock= 1.16E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:03:10 11/16/2025                               

           job ended   at     09:03:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8712 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 9.90E-02                       

 sweep: dc dc0    end, cpu clock= 1.06E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:08:44 11/16/2025                               

           job ended   at     09:08:44 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13480 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.01E-01                       

 sweep: dc dc0    end, cpu clock= 1.08E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:17 11/16/2025                               

           job ended   at     09:17:18 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18704 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.01E-01                       

 sweep: dc dc0    end, cpu clock= 1.08E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:01 11/16/2025                               

           job ended   at     09:28:02 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3864 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.10E-01                       

 sweep: dc dc0    end, cpu clock= 1.17E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:55:53 11/16/2025                               

           job ended   at     09:55:53 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9012 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 9.90E-02                       

 sweep: dc dc0    end, cpu clock= 1.06E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:17:53 11/16/2025                               

           job ended   at     10:17:53 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8432 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.08E-01                       

 sweep: dc dc0    end, cpu clock= 1.15E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:21:19 11/16/2025                               

           job ended   at     10:21:19 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20408 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.09E-01                       

 sweep: dc dc0    end, cpu clock= 1.16E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:40 11/16/2025                               

           job ended   at     10:49:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7612 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.12E-01                       

 sweep: dc dc0    end, cpu clock= 1.19E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:56:35 11/16/2025                               

           job ended   at     10:56:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8364 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.08E-01                       

 sweep: dc dc0    end, cpu clock= 1.15E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:02:18 11/16/2025                               

           job ended   at     11:02:19 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11572 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.06E-01                       

 sweep: dc dc0    end, cpu clock= 1.13E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:26 11/16/2025                               

           job ended   at     11:04:27 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13864 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.12E-01                       

 sweep: dc dc0    end, cpu clock= 1.19E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:33 11/16/2025                               

           job ended   at     11:12:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8500 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.03E-01                       

 sweep: dc dc0    end, cpu clock= 1.14E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:35 11/16/2025                               

           job ended   at     11:21:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8996 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.09E-01                       

 sweep: dc dc0    end, cpu clock= 1.16E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:19 11/16/2025                               

           job ended   at     11:34:19 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9336 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.06E-01                       

 sweep: dc dc0    end, cpu clock= 1.13E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:14:58 11/16/2025                               

           job ended   at     13:14:58 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.12E-01                       

 sweep: dc dc0    end, cpu clock= 1.19E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:26:18 11/17/2025                               

           job ended   at     10:26:18 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17228 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.04E-01                       

 sweep: dc dc0    end, cpu clock= 1.11E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:29:49 11/17/2025                               

           job ended   at     10:29:50 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\puxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16524 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 sweep: dc dc0    begin, #sweeps= 100 cpu clock= 1.07E-01                       

 sweep: dc dc0    end, cpu clock= 1.14E-01 peak memory=      72 mb              

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:48:14 11/17/2025                               

           job ended   at     10:48:14 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
