

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5112 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.49E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.52E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.52E-01                                  

 init: end check errors, cpu clock= 1.55E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.55E-01                     

       establish matrix -- done, cpu clock= 1.55E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.55E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.55E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.55E-01                                          

 dcop: end dcop, cpu clock= 1.57E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.58E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.59E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.59E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.59E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.59E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.59E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.60E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.60E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.60E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.60E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.60E-01

 sweep: tran tran0    end, cpu clock= 1.60E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.16 seconds                           

           job started at     21:22:09 11/02/2025                               

           job ended   at     21:22:09 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19168 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.03E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:27:38 11/02/2025                               

           job ended   at     21:27:38 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13092 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.06E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.07E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:33:04 11/02/2025                               

           job ended   at     21:33:04 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10356 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.11E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.16E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.16E-01                     

       establish matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.16E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.19E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.19E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.20E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.20E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.20E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.20E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.20E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     08:09:42 11/03/2025                               

           job ended   at     08:09:42 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16608 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.10E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.11E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.11E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     08:15:34 11/03/2025                               

           job ended   at     08:15:34 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4388 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.12E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.13E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.13E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:04:27 11/05/2025                               

           job ended   at     09:04:27 11/05/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19612 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.15E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     18:23:49 11/07/2025                               

           job ended   at     18:23:49 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12384 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.02E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.03E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.03E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:28:53 11/07/2025                               

           job ended   at     18:28:53 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20644 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.11E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.12E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     01:50:21 11/10/2025                               

           job ended   at     01:50:21 11/10/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9980 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.56E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.56E-01                                  

 init: end check errors, cpu clock= 1.73E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.73E-01                     

       establish matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.75E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.76E-01                                          

 dcop: end dcop, cpu clock= 1.78E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.79E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.80E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.81E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.81E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.81E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.81E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.81E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.81E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.81E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.82E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.82E-01

 sweep: tran tran0    end, cpu clock= 1.82E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     22:22:21 11/11/2025                               

           job ended   at     22:22:22 11/11/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
