

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1196 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.03E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:45 11/15/2025                               

           job ended   at     12:23:45 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8708 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.18E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.20E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.20E-01                                  

 init: end check errors, cpu clock= 1.22E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.22E-01                     

       establish matrix -- done, cpu clock= 1.23E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.23E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.23E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.23E-01                                          

 dcop: end dcop, cpu clock= 1.24E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.26E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.26E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.27E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.27E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.27E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.27E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.27E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.27E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.28E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.28E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.28E-01

 sweep: tran tran0    end, cpu clock= 1.28E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     12:54:33 11/15/2025                               

           job ended   at     12:54:33 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14556 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.14E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     13:37:50 11/15/2025                               

           job ended   at     13:37:50 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11084 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.14E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.17E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.17E-01                                  

 init: end check errors, cpu clock= 1.19E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.19E-01                     

       establish matrix -- done, cpu clock= 1.19E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.20E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.20E-01                                          

 dcop: end dcop, cpu clock= 1.22E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.23E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.24E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.24E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.24E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.24E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.24E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.25E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.25E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.25E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.25E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.25E-01

 sweep: tran tran0    end, cpu clock= 1.25E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     22:25:21 11/15/2025                               

           job ended   at     22:25:21 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14656 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.15E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.16E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:34 11/15/2025                               

           job ended   at     22:40:34 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8064 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.09E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.14E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.15E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.17E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.17E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.18E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.18E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.18E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.19E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:12 11/15/2025                               

           job ended   at     22:54:12 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17324 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.12E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.12E-01                                  

 init: end check errors, cpu clock= 1.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.14E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.16E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.18E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.19E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.19E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.19E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.19E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.19E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:03:14 11/16/2025                               

           job ended   at     09:03:15 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22216 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.03E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:08:49 11/16/2025                               

           job ended   at     09:08:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20772 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.04E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.05E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:22 11/16/2025                               

           job ended   at     09:17:22 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15744 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.09E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.10E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:06 11/16/2025                               

           job ended   at     09:28:06 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19396 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.16E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.16E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:55:57 11/16/2025                               

           job ended   at     09:55:57 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10532 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.06E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.06E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:17:57 11/16/2025                               

           job ended   at     10:17:57 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12576 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.05E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:23 11/16/2025                               

           job ended   at     10:21:23 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16896 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.09E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.16E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.17E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.18E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.18E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.18E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.19E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.19E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.19E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:44 11/16/2025                               

           job ended   at     10:49:44 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11800 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.57E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.57E-01                                  

 init: end check errors, cpu clock= 1.72E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.72E-01                     

       establish matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.74E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.76E-01                                          

 dcop: end dcop, cpu clock= 1.78E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.80E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.81E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.82E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.82E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.82E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.82E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.82E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.82E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.82E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.83E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.83E-01

 sweep: tran tran0    end, cpu clock= 1.83E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     10:56:39 11/16/2025                               

           job ended   at     10:56:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17016 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.07E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.07E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:28 11/16/2025                               

           job ended   at     11:02:28 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10212 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.01E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.01E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.01E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.02E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.02E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.02E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:04:30 11/16/2025                               

           job ended   at     11:04:30 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16364 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.44E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.53E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.53E-01                                  

 init: end check errors, cpu clock= 1.69E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.69E-01                     

       establish matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.70E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.71E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.72E-01                                          

 dcop: end dcop, cpu clock= 1.75E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.77E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.78E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.78E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.78E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.79E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.79E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.79E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.80E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.80E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.80E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.80E-01

 sweep: tran tran0    end, cpu clock= 1.80E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     11:12:37 11/16/2025                               

           job ended   at     11:12:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19844 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.10E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.10E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:39 11/16/2025                               

           job ended   at     11:21:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8124 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.14E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.15E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:23 11/16/2025                               

           job ended   at     11:34:23 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rdtout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14716 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.37E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.45E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.45E-01                                  

 init: end check errors, cpu clock= 1.61E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.61E-01                     

       establish matrix -- done, cpu clock= 1.62E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.62E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.62E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.64E-01                                          

 dcop: end dcop, cpu clock= 1.66E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.68E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 1.69E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 1.69E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 1.70E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 1.70E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 1.70E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.70E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.70E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 1.70E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 1.70E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 1.70E-01

 sweep: tran tran0    end, cpu clock= 1.71E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.17 seconds                           

           job started at     13:15:02 11/16/2025                               

           job ended   at     13:15:02 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
