

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      960 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.12E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.16E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.16E-01                                  

 init: end check errors, cpu clock= 1.20E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.20E-01                     

       establish matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.20E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.20E-01                                          

 dcop: end dcop, cpu clock= 1.22E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.24E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.25E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.25E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.25E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.25E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.25E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.25E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.25E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.26E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.26E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.26E-01

 sweep: tran tran0    end, cpu clock= 1.26E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     21:22:06 11/02/2025                               

           job ended   at     21:22:06 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18192 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     21:27:36 11/02/2025                               

           job ended   at     21:27:36 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      24344 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.08E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.09E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:33:01 11/02/2025                               

           job ended   at     21:33:01 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7764 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.11E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.18E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.18E-01                     

       establish matrix -- done, cpu clock= 1.18E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.18E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.19E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.19E-01                                          

 dcop: end dcop, cpu clock= 1.20E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.22E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.23E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.23E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.23E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.23E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.24E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.24E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.24E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.24E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.24E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.24E-01

 sweep: tran tran0    end, cpu clock= 1.24E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     08:09:40 11/03/2025                               

           job ended   at     08:09:40 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21528 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     08:15:32 11/03/2025                               

           job ended   at     08:15:32 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6192 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.15E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.18E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.20E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.23E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.24E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.24E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.24E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.24E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.24E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.24E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.24E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.24E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.25E-01

 sweep: tran tran0    end, cpu clock= 1.25E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     09:04:25 11/05/2025                               

           job ended   at     09:04:25 11/05/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10800 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.17E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     18:23:47 11/07/2025                               

           job ended   at     18:23:48 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      2460 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     18:28:51 11/07/2025                               

           job ended   at     18:28:51 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13420 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.17E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.17E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.17E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     01:50:19 11/10/2025                               

           job ended   at     01:50:19 11/10/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\rutout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12276 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:22:20 11/11/2025                               

           job ended   at     22:22:20 11/11/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
