

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3812 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 3.21E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 3.25E-01 peak memory=      70 mb      

 init: begin check errors, cpu clock= 3.25E-01                                  

 init: end check errors, cpu clock= 3.29E-01 peak memory=      71 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 3.29E-01                     

       establish matrix -- done, cpu clock= 3.29E-01 peak memory=      71 mb    

       re-order matrix -- done, cpu clock= 3.29E-01 peak memory=      71 mb     

 init: end setup matrix, cpu clock= 3.29E-01 peak memory=      71 mb            

 dcop: begin dcop, cpu clock= 3.30E-01                                          

 dcop: end dcop, cpu clock= 3.33E-01 peak memory=      71 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 3.35E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 3.36E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 3.36E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 3.37E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 3.37E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 3.37E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 3.37E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 3.38E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 3.38E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 3.38E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 3.38E-01

 sweep: tran tran0    end, cpu clock= 3.38E-01 peak memory=      71 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.35 seconds                           

           job started at     21:22:08 11/02/2025                               

           job ended   at     21:22:08 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14472 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.13E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:27:38 11/02/2025                               

           job ended   at     21:27:38 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      23960 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.06E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     21:33:03 11/02/2025                               

           job ended   at     21:33:03 11/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10796 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     08:09:41 11/03/2025                               

           job ended   at     08:09:41 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11320 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.13E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     08:15:33 11/03/2025                               

           job ended   at     08:15:34 11/03/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11472 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.11E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:04:27 11/05/2025                               

           job ended   at     09:04:27 11/05/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14576 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.12E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.17E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.17E-01                     

       establish matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.17E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.17E-01                                          

 dcop: end dcop, cpu clock= 1.18E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.20E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.20E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.21E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.21E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.21E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.21E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.21E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.21E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.21E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.21E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.22E-01

 sweep: tran tran0    end, cpu clock= 1.22E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     18:23:49 11/07/2025                               

           job ended   at     18:23:49 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12636 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.09E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:28:52 11/07/2025                               

           job ended   at     18:28:53 11/07/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20932 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.12E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.12E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     01:50:21 11/10/2025                               

           job ended   at     01:50:21 11/10/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\ruxout.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8992 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0232E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.0232E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.0232E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2023E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5195E-09 tot_iter=      57 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.9177E-09 tot_iter=      66 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.2177E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 2.5177E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 2.8177E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     22:22:21 11/11/2025                               

           job ended   at     22:22:21 11/11/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
