

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19976 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.05E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.05E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.05E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:51 11/15/2025                               

           job ended   at     12:23:51 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14464 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.11E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:54:40 11/15/2025                               

           job ended   at     12:54:40 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20172 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.03E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.03E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.03E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.03E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     13:38:03 11/15/2025                               

           job ended   at     13:38:03 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12408 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.46E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.54E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.54E-01                                  

 init: end check errors, cpu clock= 1.70E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.70E-01                     

       establish matrix -- done, cpu clock= 1.71E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.72E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.72E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.73E-01                                          

 dcop: end dcop, cpu clock= 1.77E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.78E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.80E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.80E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.80E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.80E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.80E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.81E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.81E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.81E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.81E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.81E-01

 sweep: tran tran0    end, cpu clock= 1.81E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     22:25:28 11/15/2025                               

           job ended   at     22:25:28 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22000 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.11E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.17E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.17E-01                     

       establish matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.17E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.17E-01                                          

 dcop: end dcop, cpu clock= 1.19E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.21E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.22E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.22E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.22E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.22E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.22E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.22E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.23E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.23E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.23E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.23E-01

 sweep: tran tran0    end, cpu clock= 1.23E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:41 11/15/2025                               

           job ended   at     22:40:41 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7388 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.16E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.16E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:26 11/15/2025                               

           job ended   at     22:54:26 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21988 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:17:35 11/16/2025                               

           job ended   at     09:17:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10532 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.11E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.11E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.11E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.11E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:40 11/16/2025                               

           job ended   at     09:17:40 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18168 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.12E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:16 11/16/2025                               

           job ended   at     09:28:16 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10412 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:20 11/16/2025                               

           job ended   at     09:28:20 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20192 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:56:06 11/16/2025                               

           job ended   at     09:56:06 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.01E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.01E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.02E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.02E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.02E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.02E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     09:56:09 11/16/2025                               

           job ended   at     09:56:09 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20216 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.13E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.13E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.13E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.13E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:07 11/16/2025                               

           job ended   at     10:18:07 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5424 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.10E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:11 11/16/2025                               

           job ended   at     10:18:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18824 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.26E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.31E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.31E-01                                  

 init: end check errors, cpu clock= 1.34E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.34E-01                     

       establish matrix -- done, cpu clock= 1.34E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.35E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.35E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.36E-01                                          

 dcop: end dcop, cpu clock= 1.39E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.42E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.44E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.44E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.45E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.45E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.45E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.45E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.46E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.46E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.47E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.47E-01

 sweep: tran tran0    end, cpu clock= 1.47E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.15 seconds                           

           job started at     10:21:34 11/16/2025                               

           job ended   at     10:21:34 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19844 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.11E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.11E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.12E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:39 11/16/2025                               

           job ended   at     10:21:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19136 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.13E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:49:53 11/16/2025                               

           job ended   at     10:49:53 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15396 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.13E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.13E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:56 11/16/2025                               

           job ended   at     10:49:56 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10744 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.13E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:47 11/16/2025                               

           job ended   at     10:56:47 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20908 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.06E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.06E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:50 11/16/2025                               

           job ended   at     10:56:50 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21616 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.06E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.06E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:36 11/16/2025                               

           job ended   at     11:02:36 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21904 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.15E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:02:39 11/16/2025                               

           job ended   at     11:02:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15868 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:37 11/16/2025                               

           job ended   at     11:04:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9884 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.07E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.07E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:40 11/16/2025                               

           job ended   at     11:04:40 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20912 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:45 11/16/2025                               

           job ended   at     11:12:45 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16364 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.08E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:12:48 11/16/2025                               

           job ended   at     11:12:48 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.03E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.03E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.03E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:47 11/16/2025                               

           job ended   at     11:21:47 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19508 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.7571E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.7571E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.7571E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8177E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.2300E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.07E-01

 tran: time= 2.5300E-09 tot_iter=      78 conv_iter=      27 cpu clock= 1.07E-01

 tran: time= 2.8300E-09 tot_iter=      83 conv_iter=      29 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:50 11/16/2025                               

           job ended   at     11:21:50 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12624 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.47E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.56E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.56E-01                                  

 init: end check errors, cpu clock= 1.71E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.71E-01                     

       establish matrix -- done, cpu clock= 1.72E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.73E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.73E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.75E-01                                          

 dcop: end dcop, cpu clock= 1.78E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.79E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.81E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.81E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.81E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.82E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.82E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.82E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.82E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.82E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.83E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.83E-01

 sweep: tran tran0    end, cpu clock= 1.83E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.19 seconds                           

           job started at     11:34:31 11/16/2025                               

           job ended   at     11:34:31 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11036 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.11E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.11E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.11E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.12E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:34 11/16/2025                               

           job ended   at     11:34:34 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13208 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.13E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     13:15:11 11/16/2025                               

           job ended   at     13:15:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y00out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8588 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.8424E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.8424E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 9.8424E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8423E-09 tot_iter=      58 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.2128E-09 tot_iter=      67 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 2.5128E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.08E-01

 tran: time= 2.8128E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:15:14 11/16/2025                               

           job ended   at     13:15:15 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
