

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.10E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:50 11/15/2025                               

           job ended   at     12:23:50 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19936 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.15E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.15E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     12:54:39 11/15/2025                               

           job ended   at     12:54:39 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19280 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.17E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.17E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.17E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.17E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.17E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.17E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     13:38:01 11/15/2025                               

           job ended   at     13:38:01 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11672 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.16E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.16E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:25:26 11/15/2025                               

           job ended   at     22:25:27 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11408 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.52E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.61E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.61E-01                                  

 init: end check errors, cpu clock= 1.79E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.79E-01                     

       establish matrix -- done, cpu clock= 1.80E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.80E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.81E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.82E-01                                          

 dcop: end dcop, cpu clock= 1.85E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.87E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.88E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.88E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.88E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.88E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.88E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.89E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.89E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.89E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.89E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.89E-01

 sweep: tran tran0    end, cpu clock= 1.89E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.07 seconds                               

           total elapsed time            0.19 seconds                           

           job started at     22:40:39 11/15/2025                               

           job ended   at     22:40:40 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16576 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.15E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.15E-01                     

       establish matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.15E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.16E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.19E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.20E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.20E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.20E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.20E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.20E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.20E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.20E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.21E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:22 11/15/2025                               

           job ended   at     22:54:22 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5672 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.05E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.05E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.08E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.7565E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.11E-01

 tran: time= 6.7565E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.7565E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.12E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.12E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 1.8957E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.12E-01

 tran: time= 2.1348E-09 tot_iter=      69 conv_iter=      25 cpu clock= 1.12E-01

 tran: time= 2.4348E-09 tot_iter=      74 conv_iter=      27 cpu clock= 1.12E-01

 tran: time= 2.7348E-09 tot_iter=      80 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:37 11/16/2025                               

           job ended   at     09:17:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17964 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7565E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.7565E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.7565E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2757E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5757E-09 tot_iter=      53 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8957E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.05E-01

 tran: time= 2.1348E-09 tot_iter=      69 conv_iter=      25 cpu clock= 1.05E-01

 tran: time= 2.4348E-09 tot_iter=      74 conv_iter=      27 cpu clock= 1.05E-01

 tran: time= 2.7348E-09 tot_iter=      80 conv_iter=      29 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:42 11/16/2025                               

           job ended   at     09:17:42 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21176 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.16E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.16E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.16E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:28:18 11/16/2025                               

           job ended   at     09:28:18 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1744 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.09E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.09E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.10E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:28:22 11/16/2025                               

           job ended   at     09:28:22 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      660 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.08E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.08E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.08E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.08E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.08E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.09E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:07 11/16/2025                               

           job ended   at     09:56:07 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19508 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.05E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.05E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:11 11/16/2025                               

           job ended   at     09:56:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16600 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.08E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.08E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:09 11/16/2025                               

           job ended   at     10:18:09 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19340 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.07E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.07E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.07E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:13 11/16/2025                               

           job ended   at     10:18:13 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22056 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 2.60E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 2.65E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 2.65E-01                                  

 init: end check errors, cpu clock= 2.74E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.74E-01                     

       establish matrix -- done, cpu clock= 2.74E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.75E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.75E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.75E-01                                          

 dcop: end dcop, cpu clock= 2.80E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.85E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 2.87E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 2.87E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 2.87E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 2.88E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 2.88E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 2.88E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 2.88E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 2.89E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 2.89E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 2.89E-01

 sweep: tran tran0    end, cpu clock= 2.90E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.29 seconds                           

           job started at     10:21:36 11/16/2025                               

           job ended   at     10:21:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3880 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.10E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.30E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.30E-02                                  

 init: end check errors, cpu clock= 9.60E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.60E-02                     

       establish matrix -- done, cpu clock= 9.60E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.60E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.60E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.60E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 9.90E-02 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.00E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.00E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.00E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.00E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.00E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.01E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.01E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.01E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.01E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.01E-01

 sweep: tran tran0    end, cpu clock= 1.01E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:21:40 11/16/2025                               

           job ended   at     10:21:40 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16308 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.16E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.17E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.17E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.17E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.17E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:54 11/16/2025                               

           job ended   at     10:49:54 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14808 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.07E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.07E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.07E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:49:57 11/16/2025                               

           job ended   at     10:49:57 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17728 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.13E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.14E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.14E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:56:48 11/16/2025                               

           job ended   at     10:56:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21992 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.07E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.07E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.08E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.08E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:51 11/16/2025                               

           job ended   at     10:56:52 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14936 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.11E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.11E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.11E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.11E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:37 11/16/2025                               

           job ended   at     11:02:38 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8936 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.02E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.03E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.03E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.03E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:02:40 11/16/2025                               

           job ended   at     11:02:40 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17176 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.08E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.08E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.08E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.08E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.08E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.09E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.09E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:38 11/16/2025                               

           job ended   at     11:04:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16804 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.10E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.11E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.11E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:41 11/16/2025                               

           job ended   at     11:04:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10996 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.15E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.15E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.15E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.15E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:47 11/16/2025                               

           job ended   at     11:12:47 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16908 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.04E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:12:49 11/16/2025                               

           job ended   at     11:12:50 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20840 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.06E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.06E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.06E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:49 11/16/2025                               

           job ended   at     11:21:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8936 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.7563E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 6.7563E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.05E-01

 tran: time= 9.7563E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 1.2756E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5756E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8866E-09 tot_iter=      64 conv_iter=      23 cpu clock= 1.06E-01

 tran: time= 2.1253E-09 tot_iter=      70 conv_iter=      25 cpu clock= 1.06E-01

 tran: time= 2.4253E-09 tot_iter=      75 conv_iter=      27 cpu clock= 1.06E-01

 tran: time= 2.7253E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:52 11/16/2025                               

           job ended   at     11:21:52 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8032 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.12E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.12E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.13E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.13E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.13E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.13E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.13E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.13E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:32 11/16/2025                               

           job ended   at     11:34:32 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22036 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.10E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:35 11/16/2025                               

           job ended   at     11:34:35 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18620 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.39E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.47E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.47E-01                                  

 init: end check errors, cpu clock= 1.63E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.63E-01                     

       establish matrix -- done, cpu clock= 1.64E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.64E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.65E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.66E-01                                          

 dcop: end dcop, cpu clock= 1.68E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.70E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.72E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.72E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.72E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.72E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.72E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.72E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.72E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.72E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.73E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.73E-01

 sweep: tran tran0    end, cpu clock= 1.73E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     13:15:13 11/16/2025                               

           job ended   at     13:15:13 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14984 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.05E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.05E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.05E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.05E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:15:16 11/16/2025                               

           job ended   at     13:15:16 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11304 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.09E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.09E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.09E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.09E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.09E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.10E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.10E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:26:31 11/17/2025                               

           job ended   at     10:26:31 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19200 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.03E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:26:34 11/17/2025                               

           job ended   at     10:26:34 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4372 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.02E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.02E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.02E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.02E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.03E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:30:07 11/17/2025                               

           job ended   at     10:30:07 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12392 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.06E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.06E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.06E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.06E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.07E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.07E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:30:10 11/17/2025                               

           job ended   at     10:30:10 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19528 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.15E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.15E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.15E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.16E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.16E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.16E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:48:28 11/17/2025                               

           job ended   at     10:48:28 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\y01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18096 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.8416E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.03E-01

 tran: time= 6.8416E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.04E-01

 tran: time= 9.8416E-10 tot_iter=      40 conv_iter=      16 cpu clock= 1.04E-01

 tran: time= 1.2842E-09 tot_iter=      46 conv_iter=      18 cpu clock= 1.04E-01

 tran: time= 1.5842E-09 tot_iter=      52 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8053E-09 tot_iter=      59 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.1575E-09 tot_iter=      68 conv_iter=      25 cpu clock= 1.04E-01

 tran: time= 2.4575E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.04E-01

 tran: time= 2.7575E-09 tot_iter=      79 conv_iter=      29 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:48:30 11/17/2025                               

           job ended   at     10:48:30 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
