

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19196 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.07E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.07E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.07E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.08E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:23:50 11/15/2025                               

           job ended   at     12:23:50 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20136 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.10E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.10E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.10E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.10E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.10E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     12:54:39 11/15/2025                               

           job ended   at     12:54:40 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8156 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.07E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.07E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:38:02 11/15/2025                               

           job ended   at     13:38:02 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17048 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.11E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.16E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.16E-01                     

       establish matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.16E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.16E-01                                          

 dcop: end dcop, cpu clock= 1.18E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.19E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.20E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.20E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.20E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.21E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.21E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.21E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.21E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.21E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.21E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.21E-01

 sweep: tran tran0    end, cpu clock= 1.21E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:25:27 11/15/2025                               

           job ended   at     22:25:27 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21540 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.16E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.16E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.16E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.16E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.17E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.17E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.17E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:40:40 11/15/2025                               

           job ended   at     22:40:40 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4632 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.13E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.13E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.13E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:54:23 11/15/2025                               

           job ended   at     22:54:23 11/15/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9780 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.13E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 9.6770E-10 tot_iter=      38 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.2677E-09 tot_iter=      45 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.6160E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8382E-09 tot_iter=      66 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1382E-09 tot_iter=      72 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.4382E-09 tot_iter=      76 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.7382E-09 tot_iter=      80 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      30 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:17:37 11/16/2025                               

           job ended   at     09:17:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16740 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.06E-01 peak memory=      72 mb tot_iter=       7  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.08E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.08E-01

 tran: time= 9.6770E-10 tot_iter=      38 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.2677E-09 tot_iter=      45 conv_iter=      17 cpu clock= 1.09E-01

 tran: time= 1.6160E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.09E-01

 tran: time= 1.8382E-09 tot_iter=      66 conv_iter=      22 cpu clock= 1.09E-01

 tran: time= 2.1382E-09 tot_iter=      72 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.4382E-09 tot_iter=      76 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.7382E-09 tot_iter=      80 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      30 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:17:42 11/16/2025                               

           job ended   at     09:17:43 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16324 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.13E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:28:19 11/16/2025                               

           job ended   at     09:28:19 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5352 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.60E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.60E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.00E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.01E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.01E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.01E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.01E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.01E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     09:28:22 11/16/2025                               

           job ended   at     09:28:22 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10624 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.11E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.11E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.11E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.11E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.11E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.11E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:08 11/16/2025                               

           job ended   at     09:56:08 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15296 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:56:11 11/16/2025                               

           job ended   at     09:56:11 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18536 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:10 11/16/2025                               

           job ended   at     10:18:10 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      22092 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.08E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.10E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.11E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.12E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.12E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.12E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.13E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.13E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.13E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.13E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.13E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.13E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:18:13 11/16/2025                               

           job ended   at     10:18:13 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      4284 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.16E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.16E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.16E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.17E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.17E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.17E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.17E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:21:37 11/16/2025                               

           job ended   at     10:21:37 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15464 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.04E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.05E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:21:41 11/16/2025                               

           job ended   at     10:21:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12632 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.15E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.17E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.17E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.17E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.18E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.18E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.18E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.18E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.18E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.19E-01

 sweep: tran tran0    end, cpu clock= 1.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:49:55 11/16/2025                               

           job ended   at     10:49:55 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20228 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.07E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.07E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.07E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:49:57 11/16/2025                               

           job ended   at     10:49:57 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17652 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.13E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.13E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.13E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.13E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:56:49 11/16/2025                               

           job ended   at     10:56:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13948 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.07E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.07E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.07E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.07E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:56:52 11/16/2025                               

           job ended   at     10:56:52 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5084 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.06E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.08E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.08E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.08E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.09E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.09E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.10E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:38 11/16/2025                               

           job ended   at     11:02:38 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12704 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:02:41 11/16/2025                               

           job ended   at     11:02:41 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20092 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.07E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.07E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.07E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.07E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.08E-01

 sweep: tran tran0    end, cpu clock= 1.08E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:39 11/16/2025                               

           job ended   at     11:04:39 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      1856 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.04E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.05E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.05E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.05E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.05E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.05E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:04:42 11/16/2025                               

           job ended   at     11:04:42 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11468 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.14E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.15E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:12:47 11/16/2025                               

           job ended   at     11:12:47 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18696 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.04E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:12:50 11/16/2025                               

           job ended   at     11:12:50 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12560 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.07E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.08E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.08E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:21:49 11/16/2025                               

           job ended   at     11:21:49 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15464 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       8  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.6914E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 6.6914E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 9.6764E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 1.2676E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.6134E-09 tot_iter=      60 conv_iter=      20 cpu clock= 1.03E-01

 tran: time= 1.8348E-09 tot_iter=      67 conv_iter=      22 cpu clock= 1.03E-01

 tran: time= 2.1348E-09 tot_iter=      73 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.4348E-09 tot_iter=      77 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.7348E-09 tot_iter=      81 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      30 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     11:21:52 11/16/2025                               

           job ended   at     11:21:52 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18888 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.15E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.15E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.15E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.16E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     11:34:33 11/16/2025                               

           job ended   at     11:34:33 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15304 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     11:34:36 11/16/2025                               

           job ended   at     11:34:36 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19960 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.43E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.52E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.52E-01                                  

 init: end check errors, cpu clock= 1.67E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.67E-01                     

       establish matrix -- done, cpu clock= 1.68E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.69E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.69E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.70E-01                                          

 dcop: end dcop, cpu clock= 1.73E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.75E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.76E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.76E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.76E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.77E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.77E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.77E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.77E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.77E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.77E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.77E-01

 sweep: tran tran0    end, cpu clock= 1.77E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     13:15:14 11/16/2025                               

           job ended   at     13:15:14 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19020 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.08E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.08E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.08E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.08E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.08E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     13:15:17 11/16/2025                               

           job ended   at     13:15:17 11/16/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11004 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.14E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.14E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.15E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.15E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.15E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.15E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:26:31 11/17/2025                               

           job ended   at     10:26:31 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15940 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.70E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.70E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.90E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.01E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.01E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.01E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.01E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.01E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.02E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.02E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.02E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.02E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.02E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:26:34 11/17/2025                               

           job ended   at     10:26:35 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18712 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:30:07 11/17/2025                               

           job ended   at     10:30:07 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12732 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.35E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.43E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.43E-01                                  

 init: end check errors, cpu clock= 1.59E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.59E-01                     

       establish matrix -- done, cpu clock= 1.60E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.60E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.60E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.61E-01                                          

 dcop: end dcop, cpu clock= 1.64E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.66E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.67E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.67E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.68E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.68E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.68E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.68E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.68E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.68E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.68E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.68E-01

 sweep: tran tran0    end, cpu clock= 1.69E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.17 seconds                           

           job started at     10:30:11 11/17/2025                               

           job ended   at     10:30:11 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17800 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.08E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.08E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.14E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:48:28 11/17/2025                               

           job ended   at     10:48:28 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output\z01out.spi    

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9784 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.20E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.40E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.40E-02                                  

 init: end check errors, cpu clock= 9.60E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.60E-02                     

       establish matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.70E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.70E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.70E-02                                          

 dcop: end dcop, cpu clock= 9.80E-02 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.00E-01 

 tran: time= 3.6913E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.00E-01

 tran: time= 6.6913E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.00E-01

 tran: time= 9.6786E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.01E-01

 tran: time= 1.2679E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.01E-01

 tran: time= 1.6095E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.01E-01

 tran: time= 1.8286E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.01E-01

 tran: time= 2.1286E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.01E-01

 tran: time= 2.4286E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.01E-01

 tran: time= 2.7286E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.01E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.01E-01

 sweep: tran tran0    end, cpu clock= 1.02E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:48:31 11/17/2025                               

           job ended   at     10:48:31 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
