

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\io_buf_default_sim_ti

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16664 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.21E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.24E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.24E-01                                  

 init: end check errors, cpu clock= 1.26E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.26E-01                     

       establish matrix -- done, cpu clock= 1.27E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.27E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.27E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.27E-01                                          

 dcop: end dcop, cpu clock= 1.30E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.31E-01 

 tran: time= 6.2166E-10 tot_iter=    1219 conv_iter=     139 cpu clock= 1.70E-01

 tran: time= 1.2640E-09 tot_iter=    1257 conv_iter=     150 cpu clock= 1.71E-01

 tran: time= 1.8484E-09 tot_iter=    1269 conv_iter=     153 cpu clock= 1.72E-01

 tran: time= 2.5515E-09 tot_iter=    1279 conv_iter=     156 cpu clock= 1.72E-01

 tran: time= 3.2154E-09 tot_iter=    1290 conv_iter=     159 cpu clock= 1.72E-01

 tran: time= 3.7364E-09 tot_iter=    1297 conv_iter=     161 cpu clock= 1.72E-01

 tran: time= 4.3364E-09 tot_iter=    1303 conv_iter=     163 cpu clock= 1.73E-01

 tran: time= 4.9364E-09 tot_iter=    1307 conv_iter=     165 cpu clock= 1.73E-01

 tran: time= 5.5364E-09 tot_iter=    1311 conv_iter=     167 cpu clock= 1.73E-01

 tran: time= 6.0000E-09 tot_iter=    1315 conv_iter=     169 cpu clock= 1.73E-01

 sweep: tran tran0    end, cpu clock= 1.73E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.17 seconds                           

           job started at     18:58:35 11/19/2025                               

           job ended   at     18:58:35 11/19/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\io_buf_default_sim_ti

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6720 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 6.2166E-10 tot_iter=    1219 conv_iter=     139 cpu clock= 1.40E-01

 tran: time= 1.2640E-09 tot_iter=    1257 conv_iter=     150 cpu clock= 1.41E-01

 tran: time= 1.8484E-09 tot_iter=    1269 conv_iter=     153 cpu clock= 1.41E-01

 tran: time= 2.5515E-09 tot_iter=    1279 conv_iter=     156 cpu clock= 1.42E-01

 tran: time= 3.2154E-09 tot_iter=    1290 conv_iter=     159 cpu clock= 1.42E-01

 tran: time= 3.7364E-09 tot_iter=    1297 conv_iter=     161 cpu clock= 1.42E-01

 tran: time= 4.3364E-09 tot_iter=    1303 conv_iter=     163 cpu clock= 1.42E-01

 tran: time= 4.9364E-09 tot_iter=    1307 conv_iter=     165 cpu clock= 1.42E-01

 tran: time= 5.5364E-09 tot_iter=    1311 conv_iter=     167 cpu clock= 1.43E-01

 tran: time= 6.0000E-09 tot_iter=    1315 conv_iter=     169 cpu clock= 1.43E-01

 sweep: tran tran0    end, cpu clock= 1.43E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     18:58:39 11/19/2025                               

           job ended   at     18:58:39 11/19/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\io_buf_default_sim_ti

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      17528 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 6.2166E-10 tot_iter=    1219 conv_iter=     139 cpu clock= 1.35E-01

 tran: time= 1.2640E-09 tot_iter=    1257 conv_iter=     150 cpu clock= 1.36E-01

 tran: time= 1.8484E-09 tot_iter=    1269 conv_iter=     153 cpu clock= 1.37E-01

 tran: time= 2.5515E-09 tot_iter=    1279 conv_iter=     156 cpu clock= 1.37E-01

 tran: time= 3.2154E-09 tot_iter=    1290 conv_iter=     159 cpu clock= 1.37E-01

 tran: time= 3.7364E-09 tot_iter=    1297 conv_iter=     161 cpu clock= 1.37E-01

 tran: time= 4.3364E-09 tot_iter=    1303 conv_iter=     163 cpu clock= 1.38E-01

 tran: time= 4.9364E-09 tot_iter=    1307 conv_iter=     165 cpu clock= 1.38E-01

 tran: time= 5.5364E-09 tot_iter=    1311 conv_iter=     167 cpu clock= 1.38E-01

 tran: time= 6.0000E-09 tot_iter=    1315 conv_iter=     169 cpu clock= 1.38E-01

 sweep: tran tran0    end, cpu clock= 1.38E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     19:05:26 11/19/2025                               

           job ended   at     19:05:27 11/19/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\io_buf_default_sim_ti

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7396 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 6.2166E-10 tot_iter=    1219 conv_iter=     139 cpu clock= 1.33E-01

 tran: time= 1.2640E-09 tot_iter=    1257 conv_iter=     150 cpu clock= 1.34E-01

 tran: time= 1.8484E-09 tot_iter=    1269 conv_iter=     153 cpu clock= 1.34E-01

 tran: time= 2.5515E-09 tot_iter=    1279 conv_iter=     156 cpu clock= 1.35E-01

 tran: time= 3.2154E-09 tot_iter=    1290 conv_iter=     159 cpu clock= 1.35E-01

 tran: time= 3.7364E-09 tot_iter=    1297 conv_iter=     161 cpu clock= 1.35E-01

 tran: time= 4.3364E-09 tot_iter=    1303 conv_iter=     163 cpu clock= 1.35E-01

 tran: time= 4.9364E-09 tot_iter=    1307 conv_iter=     165 cpu clock= 1.35E-01

 tran: time= 5.5364E-09 tot_iter=    1311 conv_iter=     167 cpu clock= 1.35E-01

 tran: time= 6.0000E-09 tot_iter=    1315 conv_iter=     169 cpu clock= 1.36E-01

 sweep: tran tran0    end, cpu clock= 1.36E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     19:05:31 11/19/2025                               

           job ended   at     19:05:31 11/19/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
