# yaml_editor_config.py — Configuration and schema definitions
# All UI field definitions and defaults in one place for easy maintenance

from datetime import datetime

# UI Schema — defines all form fields, grouping, and layout
UI_SCHEMA = {
    "general_settings": {
        "title": "General Settings",
        "fields": [
            ("IBIS Version", "ibis_version", "e.g. 5.1, 7.0"),
            ("File Name", "file_name", "Output .ibs file"),
            ("File Rev", "file_rev", "e.g. 0.1"),
            ("Date", "date", "Auto-filled"),
            ("Copyright", "copyright", "Your lab/company"),
            ("Spice Type", "spice_type", "hspice, spectre, ltspice..."),
            ("Iterate", "iterate", "1 = yes"),
            ("Cleanup", "cleanup", "0 = keep temp files")
        ],
        "cols": 3  # 3 columns layout
    },
    
    "multiline_fields": {
        "title": None,  # No section title
        "fields": [
            ("Source", "source", "Netlist generated by Grok", "Origin of the data"),
            ("Notes", "notes", "I really wouldn't try to use this driver. It's really bad.", "Be honest"),
            ("Disclaimer", "disclaimer", "This file is only for demonstration purposes.", "Legal text")
        ]
    },
    
    "component": {
        "title": "Component",
        "fields": [
            ("Component Name", "component", "e.g. SN74LVC1G07"),
            ("Manufacturer", "manufacturer", "e.g. Texas Instruments"),
            ("spiceFile", "spiceFile", "Path to SPICE netlist")
        ]
    },
    
    "global_defaults": {
        "title": "Global Defaults",
        "groups": [
            ("Simulation", [
                ("Sim Time (s)", "sim_time", "e.g. 6e-9"),
                ("Rload (Ω)", "r_load", "Usually 50")
            ]),
            ("Temperature Range [°C]", [
                ("Typ", "temp_typ", None),
                ("Min", "temp_min", None),
                ("Max", "temp_max", None)
            ]),
            ("Voltage Range [V]", [
                ("Typ", "voltage_typ", None),
                ("Min", "voltage_min", None),
                ("Max", "voltage_max", None)
            ]),
            ("Pullup Ref [V]", [
                ("Typ", "pullup_typ", None),
                ("Min", "pullup_min", None),
                ("Max", "pullup_max", None)
            ]),
            ("Pulldown Ref [V]", [
                ("Typ", "pulldown_typ", None),
                ("Min", "pulldown_min", None),
                ("Max", "pulldown_max", None)
            ]),
            ("Power Clamp Ref [V]", [
                ("Typ", "power_clamp_typ", None),
                ("Min", "power_clamp_min", None),
                ("Max", "power_clamp_max", None)
            ]),
            ("GND Clamp Ref [V]", [
                ("Typ", "gnd_clamp_typ", None),
                ("Min", "gnd_clamp_min", None),
                ("Max", "gnd_clamp_max", None)
            ]),
            ("VIL [V]", [
                ("Typ", "vil_typ", None),
                ("Min", "vil_min", None),
                ("Max", "vil_max", None)
            ]),
            ("VIH [V]", [
                ("Typ", "vih_typ", None),
                ("Min", "vih_min", None),
                ("Max", "vih_max", None)
            ]),
            ("Pin Parasitics", [
                ("R_pkg typ (Ω)", "r_pkg_typ", None),
                ("min", "r_pkg_min", None),
                ("max", "r_pkg_max", None),
                ("L_pkg typ (H)", "l_pkg_typ", None),
                ("min", "l_pkg_min", None),
                ("max", "l_pkg_max", None),
                ("C_pkg typ (F)", "c_pkg_typ", None),
                ("min", "c_pkg_min", None),
                ("max", "c_pkg_max", None),
            ]),
        ]
    },
    
    "models": {
        "title": "Models",
        "columns": ("Name", "Type", "Enable", "Polarity"),
        "height": 8
    },
    
    "pins": {
        "title": "Pins",
        "columns": ("Pin", "Signal", "Model", "Input Pin", "Enable Pin"),
        "height": 12
    }
}

# Default values for all fields
DEFAULTS = {
    # General settings
    "ibis_version": "5.1",
    "file_name": "my_model.ibs",
    "file_rev": "0.1",
    "date": lambda: datetime.now().strftime("%B %d, %Y"),
    "copyright": "© 2025 Your Lab",
    "spice_type": "hspice",
    "iterate": "1",
    "cleanup": "0",
    
    # Multiline
    "source": "Netlist generated by Grok",
    "notes": "I really wouldn't try to use this driver. It's really bad.",
    "disclaimer": "This file is only for demonstration purposes.",
    
    # Component
    "component": "FastBuffer",
    "manufacturer": "YourCompany",
    "spiceFile": "",
    
    # Global defaults
    "sim_time": "6e-9",
    "r_load": "50",
    "temp_typ": "27",
    "temp_min": "0",
    "temp_max": "100",
    "voltage_typ": "3.3",
    "voltage_min": "3.0",
    "voltage_max": "3.6",
    "pullup_typ": "3.3",
    "pullup_min": None,
    "pullup_max": None,
    "pulldown_typ": "0",
    "pulldown_min": None,
    "pulldown_max": None,
    "power_clamp_typ": "3.3",
    "power_clamp_min": None,
    "power_clamp_max": None,
    "gnd_clamp_typ": "0",
    "gnd_clamp_min": None,
    "gnd_clamp_max": None,
    "vil_typ": "0.8",
    "vil_min": None,
    "vil_max": None,
    "vih_typ": "2.0",
    "vih_min": None,
    "vih_max": None,
    "r_pkg_typ": "0.2",
    "r_pkg_min": "0.1",
    "r_pkg_max": "0.4",
    "l_pkg_typ": "5e-9",
    "l_pkg_min": "3e-9",
    "l_pkg_max": "8e-9",
    "c_pkg_typ": "1e-12",
    "c_pkg_min": "0.5e-12",
    "c_pkg_max": "2e-12",
}

# Example data for new files
EXAMPLE_MODELS = [
    {"name": "buffer", "type": "I/O", "enable": "oe", "polarity": "Non-Inverting"}
]

EXAMPLE_PINS = [
    {"pinName": "1", "signalName": "pad", "modelName": "buffer", "inputPin": "in", "enablePin": "oe"},
    {"pinName": "2", "signalName": "vdd", "modelName": "POWER", "inputPin": "", "enablePin": ""},
    {"pinName": "3", "signalName": "vss", "modelName": "GND", "inputPin": "", "enablePin": ""},
]

# UI Styling constants
COLORS = {
    "tooltip_bg": "#ffffe0",
    "tooltip_fg": "#000000",
    "log_bg": "#0d1117",
    "log_fg_info": "#d4d4d4",
    "log_fg_success": "#00ff41",
    "log_fg_warning": "#ffaa00",
    "log_fg_error": "#ff5555",
}

FONTS = {
    "title_large": ("Helvetica", 18, "bold"),
    "title_medium": ("Helvetica", 16, "bold"),
    "title_small": ("Helvetica", 12, "bold"),
    "tooltip": ("Segoe UI", 9),
    "monospace": ("Consolas", 10),
}

# Editor configuration
EDITOR_CONFIG = {
    "window_width": 1560,
    "window_height": 1000,
    "min_width": 1200,
    "min_height": 800,
    "auto_backup_interval": 30000,  # 30 seconds in ms
    "log_height": 10,
}
