

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\a00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5440 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.15E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.18E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.18E-01                                  

 init: end check errors, cpu clock= 1.20E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.20E-01                     

       establish matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.21E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.21E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.21E-01                                          

 dcop: end dcop, cpu clock= 1.24E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.25E-01 

 tran: time= 7.6501E-10 tot_iter=      63 conv_iter=      21 cpu clock= 1.27E-01

 tran: time= 1.3142E-09 tot_iter=      77 conv_iter=      25 cpu clock= 1.28E-01

 tran: time= 1.8298E-09 tot_iter=      89 conv_iter=      28 cpu clock= 1.28E-01

 tran: time= 2.4880E-09 tot_iter=      98 conv_iter=      31 cpu clock= 1.28E-01

 tran: time= 3.0880E-09 tot_iter=     103 conv_iter=      33 cpu clock= 1.28E-01

 tran: time= 3.6880E-09 tot_iter=     109 conv_iter=      35 cpu clock= 1.28E-01

 tran: time= 4.2330E-09 tot_iter=     117 conv_iter=      37 cpu clock= 1.29E-01

 tran: time= 4.8194E-09 tot_iter=     124 conv_iter=      39 cpu clock= 1.29E-01

 tran: time= 5.4194E-09 tot_iter=     129 conv_iter=      41 cpu clock= 1.29E-01

 tran: time= 6.0000E-09 tot_iter=     133 conv_iter=      43 cpu clock= 1.29E-01

 sweep: tran tran0    end, cpu clock= 1.29E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     18:20:49 11/27/2025                               

           job ended   at     18:20:49 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\a00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      12064 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 7.6501E-10 tot_iter=      63 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.3142E-09 tot_iter=      77 conv_iter=      25 cpu clock= 1.11E-01

 tran: time= 1.8298E-09 tot_iter=      89 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.4880E-09 tot_iter=      98 conv_iter=      31 cpu clock= 1.11E-01

 tran: time= 3.0880E-09 tot_iter=     103 conv_iter=      33 cpu clock= 1.11E-01

 tran: time= 3.6880E-09 tot_iter=     109 conv_iter=      35 cpu clock= 1.12E-01

 tran: time= 4.2330E-09 tot_iter=     117 conv_iter=      37 cpu clock= 1.12E-01

 tran: time= 4.8194E-09 tot_iter=     124 conv_iter=      39 cpu clock= 1.12E-01

 tran: time= 5.4194E-09 tot_iter=     129 conv_iter=      41 cpu clock= 1.12E-01

 tran: time= 6.0000E-09 tot_iter=     133 conv_iter=      43 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:20:53 11/27/2025                               

           job ended   at     18:20:53 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\a00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13548 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.03E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.06E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.06E-01                                  

 init: end check errors, cpu clock= 1.08E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.08E-01                     

       establish matrix -- done, cpu clock= 1.08E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 7.6501E-10 tot_iter=      63 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.3142E-09 tot_iter=      77 conv_iter=      25 cpu clock= 1.14E-01

 tran: time= 1.8298E-09 tot_iter=      89 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 2.4880E-09 tot_iter=      98 conv_iter=      31 cpu clock= 1.15E-01

 tran: time= 3.0880E-09 tot_iter=     103 conv_iter=      33 cpu clock= 1.15E-01

 tran: time= 3.6880E-09 tot_iter=     109 conv_iter=      35 cpu clock= 1.15E-01

 tran: time= 4.2330E-09 tot_iter=     117 conv_iter=      37 cpu clock= 1.15E-01

 tran: time= 4.8194E-09 tot_iter=     124 conv_iter=      39 cpu clock= 1.15E-01

 tran: time= 5.4194E-09 tot_iter=     129 conv_iter=      41 cpu clock= 1.15E-01

 tran: time= 6.0000E-09 tot_iter=     133 conv_iter=      43 cpu clock= 1.16E-01

 sweep: tran tran0    end, cpu clock= 1.16E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     19:01:41 11/27/2025                               

           job ended   at     19:01:42 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\a00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14092 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.06E-01 

 tran: time= 7.6501E-10 tot_iter=      63 conv_iter=      21 cpu clock= 1.07E-01

 tran: time= 1.3142E-09 tot_iter=      77 conv_iter=      25 cpu clock= 1.08E-01

 tran: time= 1.8298E-09 tot_iter=      89 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 2.4880E-09 tot_iter=      98 conv_iter=      31 cpu clock= 1.08E-01

 tran: time= 3.0880E-09 tot_iter=     103 conv_iter=      33 cpu clock= 1.08E-01

 tran: time= 3.6880E-09 tot_iter=     109 conv_iter=      35 cpu clock= 1.09E-01

 tran: time= 4.2330E-09 tot_iter=     117 conv_iter=      37 cpu clock= 1.09E-01

 tran: time= 4.8194E-09 tot_iter=     124 conv_iter=      39 cpu clock= 1.09E-01

 tran: time= 5.4194E-09 tot_iter=     129 conv_iter=      41 cpu clock= 1.09E-01

 tran: time= 6.0000E-09 tot_iter=     133 conv_iter=      43 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     19:01:44 11/27/2025                               

           job ended   at     19:01:44 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
