

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\y01out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16312 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.04E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.04E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 6.1347E-10 tot_iter=     877 conv_iter=     129 cpu clock= 1.30E-01

 tran: time= 1.2917E-09 tot_iter=     903 conv_iter=     136 cpu clock= 1.31E-01

 tran: time= 1.9807E-09 tot_iter=     912 conv_iter=     139 cpu clock= 1.31E-01

 tran: time= 2.4470E-09 tot_iter=     920 conv_iter=     141 cpu clock= 1.32E-01

 tran: time= 3.0129E-09 tot_iter=     930 conv_iter=     144 cpu clock= 1.32E-01

 tran: time= 3.7818E-09 tot_iter=     939 conv_iter=     147 cpu clock= 1.32E-01

 tran: time= 4.3818E-09 tot_iter=     944 conv_iter=     149 cpu clock= 1.32E-01

 tran: time= 4.9818E-09 tot_iter=     948 conv_iter=     151 cpu clock= 1.32E-01

 tran: time= 5.5818E-09 tot_iter=     952 conv_iter=     153 cpu clock= 1.33E-01

 tran: time= 6.0000E-09 tot_iter=     956 conv_iter=     155 cpu clock= 1.33E-01

 sweep: tran tran0    end, cpu clock= 1.33E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     18:20:59 11/27/2025                               

           job ended   at     18:20:59 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\y01out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16088 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.03E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.03E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.06E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 6.1347E-10 tot_iter=     877 conv_iter=     129 cpu clock= 1.31E-01

 tran: time= 1.2917E-09 tot_iter=     903 conv_iter=     136 cpu clock= 1.32E-01

 tran: time= 1.9807E-09 tot_iter=     912 conv_iter=     139 cpu clock= 1.32E-01

 tran: time= 2.4470E-09 tot_iter=     920 conv_iter=     141 cpu clock= 1.33E-01

 tran: time= 3.0129E-09 tot_iter=     930 conv_iter=     144 cpu clock= 1.33E-01

 tran: time= 3.7818E-09 tot_iter=     939 conv_iter=     147 cpu clock= 1.33E-01

 tran: time= 4.3818E-09 tot_iter=     944 conv_iter=     149 cpu clock= 1.33E-01

 tran: time= 4.9818E-09 tot_iter=     948 conv_iter=     151 cpu clock= 1.33E-01

 tran: time= 5.5818E-09 tot_iter=     952 conv_iter=     153 cpu clock= 1.34E-01

 tran: time= 6.0000E-09 tot_iter=     956 conv_iter=     155 cpu clock= 1.34E-01

 sweep: tran tran0    end, cpu clock= 1.34E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     18:21:02 11/27/2025                               

           job ended   at     18:21:03 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
