

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\z00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5368 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=      23  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 6.4188E-10 tot_iter=      63 conv_iter=      20 cpu clock= 1.11E-01

 tran: time= 1.2949E-09 tot_iter=      74 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.0077E-09 tot_iter=      85 conv_iter=      27 cpu clock= 1.12E-01

 tran: time= 2.6233E-09 tot_iter=      94 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.1211E-09 tot_iter=      99 conv_iter=      32 cpu clock= 1.12E-01

 tran: time= 3.7211E-09 tot_iter=     103 conv_iter=      34 cpu clock= 1.12E-01

 tran: time= 4.3211E-09 tot_iter=     107 conv_iter=      36 cpu clock= 1.13E-01

 tran: time= 4.9211E-09 tot_iter=     111 conv_iter=      38 cpu clock= 1.13E-01

 tran: time= 5.5211E-09 tot_iter=     115 conv_iter=      40 cpu clock= 1.13E-01

 tran: time= 6.0000E-09 tot_iter=     119 conv_iter=      42 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:20:58 11/27/2025                               

           job ended   at     18:20:58 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\z00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7808 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      23  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 6.4188E-10 tot_iter=      63 conv_iter=      20 cpu clock= 1.10E-01

 tran: time= 1.2949E-09 tot_iter=      74 conv_iter=      24 cpu clock= 1.10E-01

 tran: time= 2.0077E-09 tot_iter=      85 conv_iter=      27 cpu clock= 1.11E-01

 tran: time= 2.6233E-09 tot_iter=      94 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.1211E-09 tot_iter=      99 conv_iter=      32 cpu clock= 1.11E-01

 tran: time= 3.7211E-09 tot_iter=     103 conv_iter=      34 cpu clock= 1.11E-01

 tran: time= 4.3211E-09 tot_iter=     107 conv_iter=      36 cpu clock= 1.11E-01

 tran: time= 4.9211E-09 tot_iter=     111 conv_iter=      38 cpu clock= 1.11E-01

 tran: time= 5.5211E-09 tot_iter=     115 conv_iter=      40 cpu clock= 1.12E-01

 tran: time= 6.0000E-09 tot_iter=     119 conv_iter=      42 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     18:21:01 11/27/2025                               

           job ended   at     18:21:02 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\z00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7052 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.14E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.16E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.16E-01                                  

 init: end check errors, cpu clock= 1.19E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.19E-01                     

       establish matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.20E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.20E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.21E-01                                          

 dcop: end dcop, cpu clock= 1.23E-01 peak memory=      72 mb tot_iter=      23  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.24E-01 

 tran: time= 6.4188E-10 tot_iter=      63 conv_iter=      20 cpu clock= 1.26E-01

 tran: time= 1.2949E-09 tot_iter=      74 conv_iter=      24 cpu clock= 1.26E-01

 tran: time= 2.0077E-09 tot_iter=      85 conv_iter=      27 cpu clock= 1.27E-01

 tran: time= 2.6233E-09 tot_iter=      94 conv_iter=      30 cpu clock= 1.27E-01

 tran: time= 3.1211E-09 tot_iter=      99 conv_iter=      32 cpu clock= 1.27E-01

 tran: time= 3.7211E-09 tot_iter=     103 conv_iter=      34 cpu clock= 1.27E-01

 tran: time= 4.3211E-09 tot_iter=     107 conv_iter=      36 cpu clock= 1.28E-01

 tran: time= 4.9211E-09 tot_iter=     111 conv_iter=      38 cpu clock= 1.28E-01

 tran: time= 5.5211E-09 tot_iter=     115 conv_iter=      40 cpu clock= 1.28E-01

 tran: time= 6.0000E-09 tot_iter=     119 conv_iter=      42 cpu clock= 1.28E-01

 sweep: tran tran0    end, cpu clock= 1.28E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     19:01:48 11/27/2025                               

           job ended   at     19:01:48 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\1127test\z00out.s

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11276 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=      23  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 6.4188E-10 tot_iter=      63 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 1.2949E-09 tot_iter=      74 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.0077E-09 tot_iter=      85 conv_iter=      27 cpu clock= 1.05E-01

 tran: time= 2.6233E-09 tot_iter=      94 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.1211E-09 tot_iter=      99 conv_iter=      32 cpu clock= 1.05E-01

 tran: time= 3.7211E-09 tot_iter=     103 conv_iter=      34 cpu clock= 1.05E-01

 tran: time= 4.3211E-09 tot_iter=     107 conv_iter=      36 cpu clock= 1.05E-01

 tran: time= 4.9211E-09 tot_iter=     111 conv_iter=      38 cpu clock= 1.06E-01

 tran: time= 5.5211E-09 tot_iter=     115 conv_iter=      40 cpu clock= 1.06E-01

 tran: time= 6.0000E-09 tot_iter=     119 conv_iter=      42 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     19:01:51 11/27/2025                               

           job ended   at     19:01:51 11/27/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
