

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10212 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.72E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.86E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.86E-01                                  

 init: end check errors, cpu clock= 2.18E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.18E-01                     

       establish matrix -- done, cpu clock= 2.20E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.20E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.21E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.24E-01                                          

 dcop: end dcop, cpu clock= 2.28E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.29E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 2.32E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 2.32E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 2.32E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 2.32E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 2.32E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 2.32E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 2.33E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 2.33E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 2.33E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 2.33E-01

 sweep: tran tran0    end, cpu clock= 2.33E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.10 seconds                               

           total elapsed time            0.24 seconds                           

           job started at     22:36:29 11/17/2025                               

           job ended   at     22:36:29 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13188 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.09E-01 

 tran: time= 3.0786E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 6.0786E-10 tot_iter=      35 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 9.0786E-10 tot_iter=      41 conv_iter=      16 cpu clock= 1.10E-01

 tran: time= 1.2079E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.10E-01

 tran: time= 1.5677E-09 tot_iter=      59 conv_iter=      21 cpu clock= 1.10E-01

 tran: time= 1.9458E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.2458E-09 tot_iter=      73 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.5458E-09 tot_iter=      77 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.8458E-09 tot_iter=      81 conv_iter=      30 cpu clock= 1.11E-01

 tran: time= 3.0000E-09 tot_iter=      83 conv_iter=      31 cpu clock= 1.11E-01

 sweep: tran tran0    end, cpu clock= 1.11E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     22:36:32 11/17/2025                               

           job ended   at     22:36:32 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16512 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.14E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.14E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:53:02 11/18/2025                               

           job ended   at     09:53:02 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3972 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.06E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.08E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.08E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.09E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.09E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.09E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.09E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.09E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.09E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:53:07 11/18/2025                               

           job ended   at     09:53:07 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20492 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.00E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.00E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.03E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.04E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.04E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.04E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.05E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.05E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.05E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.05E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.05E-01

 sweep: tran tran0    end, cpu clock= 1.05E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:02:35 11/18/2025                               

           job ended   at     10:02:35 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21328 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.02E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.05E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.05E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:02:38 11/18/2025                               

           job ended   at     10:02:38 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21288 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.50E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.80E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.80E-02                                  

 init: end check errors, cpu clock= 1.00E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.00E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.01E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.05E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.05E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.05E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.05E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.05E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:22:53 11/18/2025                               

           job ended   at     10:22:53 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11480 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.80E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.01E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.01E-01                                  

 init: end check errors, cpu clock= 1.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.03E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.07E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.08E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.08E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.08E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.08E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.08E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.08E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.09E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.09E-01

 sweep: tran tran0    end, cpu clock= 1.09E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:22:57 11/18/2025                               

           job ended   at     10:22:57 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10548 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  1.00E-08 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 1.1586E-09 tot_iter=      41 conv_iter=      16 cpu clock= 1.05E-01

 tran: time= 2.1302E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 3.3538E-09 tot_iter=      69 conv_iter=      25 cpu clock= 1.06E-01

 tran: time= 4.3538E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.06E-01

 tran: time= 5.3538E-09 tot_iter=      77 conv_iter=      29 cpu clock= 1.06E-01

 tran: time= 6.3538E-09 tot_iter=      81 conv_iter=      31 cpu clock= 1.06E-01

 tran: time= 7.3538E-09 tot_iter=      85 conv_iter=      33 cpu clock= 1.06E-01

 tran: time= 8.3538E-09 tot_iter=      89 conv_iter=      35 cpu clock= 1.06E-01

 tran: time= 9.3538E-09 tot_iter=      93 conv_iter=      37 cpu clock= 1.06E-01

 tran: time= 1.0000E-08 tot_iter=      97 conv_iter=      39 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:28:11 11/18/2025                               

           job ended   at     10:28:11 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14612 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.06E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.11E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.11E-01                     

       establish matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.11E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.11E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.11E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  1.00E-08 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 1.1586E-09 tot_iter=      41 conv_iter=      16 cpu clock= 1.16E-01

 tran: time= 2.1302E-09 tot_iter=      62 conv_iter=      22 cpu clock= 1.16E-01

 tran: time= 3.3538E-09 tot_iter=      69 conv_iter=      25 cpu clock= 1.16E-01

 tran: time= 4.3538E-09 tot_iter=      73 conv_iter=      27 cpu clock= 1.16E-01

 tran: time= 5.3538E-09 tot_iter=      77 conv_iter=      29 cpu clock= 1.16E-01

 tran: time= 6.3538E-09 tot_iter=      81 conv_iter=      31 cpu clock= 1.17E-01

 tran: time= 7.3538E-09 tot_iter=      85 conv_iter=      33 cpu clock= 1.17E-01

 tran: time= 8.3538E-09 tot_iter=      89 conv_iter=      35 cpu clock= 1.17E-01

 tran: time= 9.3538E-09 tot_iter=      93 conv_iter=      37 cpu clock= 1.17E-01

 tran: time= 1.0000E-08 tot_iter=      97 conv_iter=      39 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:28:14 11/18/2025                               

           job ended   at     10:28:14 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      15328 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.16E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.18E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.19E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.19E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.19E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.19E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.19E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.19E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.19E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:29:54 11/18/2025                               

           job ended   at     10:29:54 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\a00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      3648 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.01E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.06E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.06E-01                     

       establish matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.08E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.0961E-10 tot_iter=      30 conv_iter=      12 cpu clock= 1.10E-01

 tran: time= 7.4688E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.11E-01

 tran: time= 1.0469E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.11E-01

 tran: time= 1.3469E-09 tot_iter=      53 conv_iter=      19 cpu clock= 1.11E-01

 tran: time= 1.5564E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.11E-01

 tran: time= 1.9043E-09 tot_iter=      69 conv_iter=      24 cpu clock= 1.11E-01

 tran: time= 2.2043E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.11E-01

 tran: time= 2.5043E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.11E-01

 tran: time= 2.8043E-09 tot_iter=      83 conv_iter=      30 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      87 conv_iter=      32 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:29:57 11/18/2025                               

           job ended   at     10:29:57 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
