

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      8000 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.09E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.12E-01 

 tran: time= 3.6949E-10 tot_iter=      26 conv_iter=      11 cpu clock= 1.13E-01

 tran: time= 6.6949E-10 tot_iter=      32 conv_iter=      13 cpu clock= 1.13E-01

 tran: time= 9.6814E-10 tot_iter=      39 conv_iter=      15 cpu clock= 1.13E-01

 tran: time= 1.2681E-09 tot_iter=      46 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.6139E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 1.8408E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.1408E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.4408E-09 tot_iter=      76 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 2.7408E-09 tot_iter=      80 conv_iter=      28 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      30 cpu clock= 1.14E-01

 sweep: tran tran0    end, cpu clock= 1.14E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     22:36:28 11/17/2025                               

           job ended   at     22:36:28 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20580 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 4.0166E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.14E-01

 tran: time= 7.0166E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.14E-01

 tran: time= 1.0017E-09 tot_iter=      40 conv_iter=      16 cpu clock= 1.14E-01

 tran: time= 1.3017E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.14E-01

 tran: time= 1.6460E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.15E-01

 tran: time= 1.8724E-09 tot_iter=      66 conv_iter=      23 cpu clock= 1.15E-01

 tran: time= 2.1724E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.15E-01

 tran: time= 2.4724E-09 tot_iter=      77 conv_iter=      27 cpu clock= 1.15E-01

 tran: time= 2.7724E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:53:02 11/18/2025                               

           job ended   at     09:53:02 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11480 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.48E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.57E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.57E-01                                  

 init: end check errors, cpu clock= 1.72E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.72E-01                     

       establish matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.74E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.74E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.75E-01                                          

 dcop: end dcop, cpu clock= 1.78E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.80E-01 

 tran: time= 4.0166E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.81E-01

 tran: time= 7.0166E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.81E-01

 tran: time= 1.0017E-09 tot_iter=      40 conv_iter=      16 cpu clock= 1.81E-01

 tran: time= 1.3017E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.81E-01

 tran: time= 1.6460E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.82E-01

 tran: time= 1.8724E-09 tot_iter=      66 conv_iter=      23 cpu clock= 1.82E-01

 tran: time= 2.1724E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.82E-01

 tran: time= 2.4724E-09 tot_iter=      77 conv_iter=      27 cpu clock= 1.82E-01

 tran: time= 2.7724E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.82E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.82E-01

 sweep: tran tran0    end, cpu clock= 1.82E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.06 seconds                               

           total elapsed time            0.18 seconds                           

           job started at     10:02:34 11/18/2025                               

           job ended   at     10:02:35 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      388 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.60E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.60E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 4.0166E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.02E-01

 tran: time= 7.0166E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 1.0017E-09 tot_iter=      40 conv_iter=      16 cpu clock= 1.02E-01

 tran: time= 1.3017E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.03E-01

 tran: time= 1.6460E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.03E-01

 tran: time= 1.8724E-09 tot_iter=      66 conv_iter=      23 cpu clock= 1.03E-01

 tran: time= 2.1724E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.03E-01

 tran: time= 2.4724E-09 tot_iter=      77 conv_iter=      27 cpu clock= 1.03E-01

 tran: time= 2.7724E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.03E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.10 seconds                           

           job started at     10:22:53 11/18/2025                               

           job ended   at     10:22:53 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      16600 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.13E-01                                          

 dcop: end dcop, cpu clock= 1.14E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  1.00E-08 #sweeps= 101 cpu clock= 1.16E-01 

 tran: time= 1.0617E-09 tot_iter=      35 conv_iter=      14 cpu clock= 1.17E-01

 tran: time= 2.1071E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.17E-01

 tran: time= 3.1854E-09 tot_iter=      68 conv_iter=      24 cpu clock= 1.17E-01

 tran: time= 4.1854E-09 tot_iter=      72 conv_iter=      26 cpu clock= 1.18E-01

 tran: time= 5.1854E-09 tot_iter=      76 conv_iter=      28 cpu clock= 1.18E-01

 tran: time= 6.1854E-09 tot_iter=      80 conv_iter=      30 cpu clock= 1.18E-01

 tran: time= 7.1854E-09 tot_iter=      84 conv_iter=      32 cpu clock= 1.18E-01

 tran: time= 8.1854E-09 tot_iter=      88 conv_iter=      34 cpu clock= 1.18E-01

 tran: time= 9.1854E-09 tot_iter=      92 conv_iter=      36 cpu clock= 1.18E-01

 tran: time= 1.0000E-08 tot_iter=      96 conv_iter=      38 cpu clock= 1.18E-01

 sweep: tran tran0    end, cpu clock= 1.18E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:28:10 11/18/2025                               

           job ended   at     10:28:10 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\rdxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9276 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.10E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.10E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.13E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.15E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.17E-01 

 tran: time= 4.0166E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.18E-01

 tran: time= 7.0166E-10 tot_iter=      34 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 1.0017E-09 tot_iter=      40 conv_iter=      16 cpu clock= 1.19E-01

 tran: time= 1.3017E-09 tot_iter=      47 conv_iter=      18 cpu clock= 1.19E-01

 tran: time= 1.6460E-09 tot_iter=      60 conv_iter=      21 cpu clock= 1.19E-01

 tran: time= 1.8724E-09 tot_iter=      66 conv_iter=      23 cpu clock= 1.19E-01

 tran: time= 2.1724E-09 tot_iter=      72 conv_iter=      25 cpu clock= 1.20E-01

 tran: time= 2.4724E-09 tot_iter=      77 conv_iter=      27 cpu clock= 1.20E-01

 tran: time= 2.7724E-09 tot_iter=      81 conv_iter=      29 cpu clock= 1.20E-01

 tran: time= 3.0000E-09 tot_iter=      85 conv_iter=      31 cpu clock= 1.20E-01

 sweep: tran tran0    end, cpu clock= 1.20E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.03 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:29:54 11/18/2025                               

           job ended   at     10:29:54 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
