

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      11244 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.71E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.89E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.89E-01                                  

 init: end check errors, cpu clock= 2.24E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.24E-01                     

       establish matrix -- done, cpu clock= 2.25E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.26E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.27E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.30E-01                                          

 dcop: end dcop, cpu clock= 2.35E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.37E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 2.39E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 2.40E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 2.40E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 2.40E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 2.40E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 2.40E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 2.41E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 2.41E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 2.41E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 2.41E-01

 sweep: tran tran0    end, cpu clock= 2.41E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.11 seconds                               

           total elapsed time            0.25 seconds                           

           job started at     22:36:35 11/17/2025                               

           job ended   at     22:36:35 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19732 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.56E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.69E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.69E-01                                  

 init: end check errors, cpu clock= 2.03E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 2.03E-01                     

       establish matrix -- done, cpu clock= 2.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 2.06E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 2.06E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 2.08E-01                                          

 dcop: end dcop, cpu clock= 2.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 2.16E-01 

 tran: time= 3.0779E-10 tot_iter=      25 conv_iter=      10 cpu clock= 2.18E-01

 tran: time= 6.0779E-10 tot_iter=      32 conv_iter=      12 cpu clock= 2.18E-01

 tran: time= 9.0779E-10 tot_iter=      38 conv_iter=      14 cpu clock= 2.18E-01

 tran: time= 1.2078E-09 tot_iter=      45 conv_iter=      16 cpu clock= 2.18E-01

 tran: time= 1.5562E-09 tot_iter=      57 conv_iter=      19 cpu clock= 2.18E-01

 tran: time= 1.9374E-09 tot_iter=      67 conv_iter=      22 cpu clock= 2.19E-01

 tran: time= 2.2374E-09 tot_iter=      73 conv_iter=      24 cpu clock= 2.19E-01

 tran: time= 2.5374E-09 tot_iter=      78 conv_iter=      26 cpu clock= 2.19E-01

 tran: time= 2.8374E-09 tot_iter=      82 conv_iter=      28 cpu clock= 2.19E-01

 tran: time= 3.0000E-09 tot_iter=      84 conv_iter=      29 cpu clock= 2.19E-01

 sweep: tran tran0    end, cpu clock= 2.19E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.10 seconds                               

           total elapsed time            0.22 seconds                           

           job started at     22:36:38 11/17/2025                               

           job ended   at     22:36:38 11/17/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      10480 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.05E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.10E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.10E-01                     

       establish matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.10E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.10E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.12E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.14E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.14E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.15E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.15E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.15E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.15E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     09:53:10 11/18/2025                               

           job ended   at     09:53:11 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      6936 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.05E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.06E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.06E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.06E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.06E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.06E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.07E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.07E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.07E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.07E-01

 sweep: tran tran0    end, cpu clock= 1.07E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     09:53:14 11/18/2025                               

           job ended   at     09:53:14 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20748 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.02E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.04E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.04E-01                                  

 init: end check errors, cpu clock= 1.07E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.07E-01                     

       establish matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.07E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.07E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.07E-01                                          

 dcop: end dcop, cpu clock= 1.09E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.10E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.11E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.11E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.11E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.11E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.11E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.12E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.12E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.12E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.12E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:02:41 11/18/2025                               

           job ended   at     10:02:41 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      5428 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.00E-01                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.03E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.04E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:02:45 11/18/2025                               

           job ended   at     10:02:45 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18752 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.40E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.70E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.70E-02                                  

 init: end check errors, cpu clock= 9.90E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.90E-02                     

       establish matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.90E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.90E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.90E-02                                          

 dcop: end dcop, cpu clock= 1.01E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.02E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.03E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.03E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.03E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.03E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.03E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.04E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.04E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.04E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.04E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.04E-01

 sweep: tran tran0    end, cpu clock= 1.04E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:23:01 11/18/2025                               

           job ended   at     10:23:01 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19132 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.60E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.01E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.01E-01                     

       establish matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.01E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.01E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.02E-01                                          

 dcop: end dcop, cpu clock= 1.03E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.04E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.05E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.05E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.05E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.05E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.05E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.06E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.06E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.06E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.06E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.06E-01

 sweep: tran tran0    end, cpu clock= 1.06E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:23:05 11/18/2025                               

           job ended   at     10:23:05 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7992 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.07E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.09E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.09E-01                                  

 init: end check errors, cpu clock= 1.12E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.12E-01                     

       establish matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.12E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.12E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.12E-01                                          

 dcop: end dcop, cpu clock= 1.13E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  1.00E-08 #sweeps= 101 cpu clock= 1.15E-01 

 tran: time= 1.0785E-09 tot_iter=      35 conv_iter=      14 cpu clock= 1.16E-01

 tran: time= 2.0090E-09 tot_iter=      57 conv_iter=      20 cpu clock= 1.16E-01

 tran: time= 3.0020E-09 tot_iter=      67 conv_iter=      24 cpu clock= 1.16E-01

 tran: time= 4.0020E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.16E-01

 tran: time= 5.0020E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.16E-01

 tran: time= 6.0020E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.17E-01

 tran: time= 7.0020E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.17E-01

 tran: time= 8.0020E-09 tot_iter=      87 conv_iter=      34 cpu clock= 1.17E-01

 tran: time= 9.0020E-09 tot_iter=      91 conv_iter=      36 cpu clock= 1.17E-01

 tran: time= 1.0000E-08 tot_iter=      95 conv_iter=      38 cpu clock= 1.17E-01

 sweep: tran tran0    end, cpu clock= 1.17E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:28:17 11/18/2025                               

           job ended   at     10:28:17 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      14132 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.30E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.50E-02 peak memory=      72 mb      

 init: begin check errors, cpu clock= 9.50E-02                                  

 init: end check errors, cpu clock= 9.80E-02 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 9.80E-02                     

       establish matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 9.80E-02 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 9.80E-02 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 9.80E-02                                          

 dcop: end dcop, cpu clock= 1.00E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  1.00E-08 #sweeps= 101 cpu clock= 1.01E-01 

 tran: time= 1.0785E-09 tot_iter=      35 conv_iter=      14 cpu clock= 1.02E-01

 tran: time= 2.0090E-09 tot_iter=      57 conv_iter=      20 cpu clock= 1.02E-01

 tran: time= 3.0020E-09 tot_iter=      67 conv_iter=      24 cpu clock= 1.03E-01

 tran: time= 4.0020E-09 tot_iter=      71 conv_iter=      26 cpu clock= 1.03E-01

 tran: time= 5.0020E-09 tot_iter=      75 conv_iter=      28 cpu clock= 1.03E-01

 tran: time= 6.0020E-09 tot_iter=      79 conv_iter=      30 cpu clock= 1.03E-01

 tran: time= 7.0020E-09 tot_iter=      83 conv_iter=      32 cpu clock= 1.03E-01

 tran: time= 8.0020E-09 tot_iter=      87 conv_iter=      34 cpu clock= 1.03E-01

 tran: time= 9.0020E-09 tot_iter=      91 conv_iter=      36 cpu clock= 1.03E-01

 tran: time= 1.0000E-08 tot_iter=      95 conv_iter=      38 cpu clock= 1.03E-01

 sweep: tran tran0    end, cpu clock= 1.03E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.11 seconds                           

           job started at     10:28:20 11/18/2025                               

           job ended   at     10:28:20 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      20216 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.12E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.14E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.14E-01                                  

 init: end check errors, cpu clock= 1.17E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.17E-01                     

       establish matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.17E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.17E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.17E-01                                          

 dcop: end dcop, cpu clock= 1.19E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.21E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.21E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.21E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.21E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.22E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.22E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.22E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.22E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.22E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.22E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.22E-01

 sweep: tran tran0    end, cpu clock= 1.22E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:30:00 11/18/2025                               

           job ended   at     10:30:00 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy\tests\output_buf\x00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9940 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.04E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.07E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.07E-01                                  

 init: end check errors, cpu clock= 1.09E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.09E-01                     

       establish matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.09E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.09E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.10E-01                                          

 dcop: end dcop, cpu clock= 1.11E-01 peak memory=      72 mb tot_iter=       3  

 sweep: tran tran0    begin, stop_t=  3.00E-09 #sweeps= 101 cpu clock= 1.13E-01 

 tran: time= 3.5733E-10 tot_iter=      20 conv_iter=       9 cpu clock= 1.13E-01

 tran: time= 6.5733E-10 tot_iter=      27 conv_iter=      11 cpu clock= 1.14E-01

 tran: time= 9.5733E-10 tot_iter=      33 conv_iter=      13 cpu clock= 1.14E-01

 tran: time= 1.2573E-09 tot_iter=      40 conv_iter=      15 cpu clock= 1.14E-01

 tran: time= 1.5226E-09 tot_iter=      48 conv_iter=      17 cpu clock= 1.14E-01

 tran: time= 1.8460E-09 tot_iter=      59 conv_iter=      20 cpu clock= 1.14E-01

 tran: time= 2.1431E-09 tot_iter=      65 conv_iter=      22 cpu clock= 1.14E-01

 tran: time= 2.4100E-09 tot_iter=      71 conv_iter=      24 cpu clock= 1.14E-01

 tran: time= 2.7100E-09 tot_iter=      75 conv_iter=      26 cpu clock= 1.14E-01

 tran: time= 3.0000E-09 tot_iter=      79 conv_iter=      28 cpu clock= 1.15E-01

 sweep: tran tran0    end, cpu clock= 1.15E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.02 seconds                               

           total elapsed time            0.12 seconds                           

           job started at     10:30:03 11/18/2025                               

           job ended   at     10:30:03 11/18/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
