

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\runout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      19204 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.14E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.14E-01                     

       establish matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.15E-01                                          

 dcop: end dcop, cpu clock= 1.17E-01 peak memory=      72 mb tot_iter=      18  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.18E-01 

 tran: time= 6.5201E-10 tot_iter=      42 conv_iter=      18 cpu clock= 1.19E-01

 tran: time= 1.2272E-09 tot_iter=      67 conv_iter=      29 cpu clock= 1.20E-01

 tran: time= 1.9025E-09 tot_iter=      95 conv_iter=      40 cpu clock= 1.21E-01

 tran: time= 2.4056E-09 tot_iter=     110 conv_iter=      45 cpu clock= 1.21E-01

 tran: time= 3.1443E-09 tot_iter=     127 conv_iter=      53 cpu clock= 1.22E-01

 tran: time= 3.7379E-09 tot_iter=     131 conv_iter=      55 cpu clock= 1.22E-01

 tran: time= 4.3379E-09 tot_iter=     135 conv_iter=      57 cpu clock= 1.22E-01

 tran: time= 4.9379E-09 tot_iter=     139 conv_iter=      59 cpu clock= 1.22E-01

 tran: time= 5.5379E-09 tot_iter=     143 conv_iter=      61 cpu clock= 1.22E-01

 tran: time= 6.0000E-09 tot_iter=     147 conv_iter=      63 cpu clock= 1.22E-01

 sweep: tran tran0    end, cpu clock= 1.22E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     23:21:49 12/02/2025                               

           job ended   at     23:21:49 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\runout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      18828 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 9.90E-02 peak memory=      71 mb      

 init: begin check errors, cpu clock= 9.90E-02                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.02E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.02E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.04E-01 peak memory=      72 mb tot_iter=      18  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.06E-01 

 tran: time= 6.5201E-10 tot_iter=      42 conv_iter=      18 cpu clock= 1.07E-01

 tran: time= 1.2272E-09 tot_iter=      67 conv_iter=      29 cpu clock= 1.08E-01

 tran: time= 1.9025E-09 tot_iter=      95 conv_iter=      40 cpu clock= 1.08E-01

 tran: time= 2.4056E-09 tot_iter=     110 conv_iter=      45 cpu clock= 1.09E-01

 tran: time= 3.1443E-09 tot_iter=     127 conv_iter=      53 cpu clock= 1.09E-01

 tran: time= 3.7379E-09 tot_iter=     131 conv_iter=      55 cpu clock= 1.09E-01

 tran: time= 4.3379E-09 tot_iter=     135 conv_iter=      57 cpu clock= 1.09E-01

 tran: time= 4.9379E-09 tot_iter=     139 conv_iter=      59 cpu clock= 1.10E-01

 tran: time= 5.5379E-09 tot_iter=     143 conv_iter=      61 cpu clock= 1.10E-01

 tran: time= 6.0000E-09 tot_iter=     147 conv_iter=      63 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     23:23:35 12/02/2025                               

           job ended   at     23:23:35 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
