

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\ruxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9952 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.08E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.11E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.11E-01                                  

 init: end check errors, cpu clock= 1.13E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.13E-01                     

       establish matrix -- done, cpu clock= 1.13E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.14E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.14E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.14E-01                                          

 dcop: end dcop, cpu clock= 1.16E-01 peak memory=      72 mb tot_iter=      21  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.17E-01 

 tran: time= 6.6560E-10 tot_iter=      33 conv_iter=      14 cpu clock= 1.18E-01

 tran: time= 1.2000E-09 tot_iter=      55 conv_iter=      23 cpu clock= 1.19E-01

 tran: time= 1.8374E-09 tot_iter=      93 conv_iter=      38 cpu clock= 1.20E-01

 tran: time= 2.4319E-09 tot_iter=     110 conv_iter=      45 cpu clock= 1.20E-01

 tran: time= 3.1457E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.20E-01

 tran: time= 3.6633E-09 tot_iter=     136 conv_iter=      56 cpu clock= 1.21E-01

 tran: time= 4.2154E-09 tot_iter=     151 conv_iter=      62 cpu clock= 1.21E-01

 tran: time= 4.9262E-09 tot_iter=     157 conv_iter=      65 cpu clock= 1.21E-01

 tran: time= 5.5262E-09 tot_iter=     161 conv_iter=      67 cpu clock= 1.21E-01

 tran: time= 6.0000E-09 tot_iter=     165 conv_iter=      69 cpu clock= 1.22E-01

 sweep: tran tran0    end, cpu clock= 1.22E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     23:21:49 12/02/2025                               

           job ended   at     23:21:49 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\ruxout.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      9648 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.00E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.05E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.05E-01                     

       establish matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      21  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.09E-01 

 tran: time= 6.6560E-10 tot_iter=      33 conv_iter=      14 cpu clock= 1.10E-01

 tran: time= 1.2000E-09 tot_iter=      55 conv_iter=      23 cpu clock= 1.10E-01

 tran: time= 1.8374E-09 tot_iter=      93 conv_iter=      38 cpu clock= 1.11E-01

 tran: time= 2.4319E-09 tot_iter=     110 conv_iter=      45 cpu clock= 1.12E-01

 tran: time= 3.1457E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.12E-01

 tran: time= 3.6633E-09 tot_iter=     136 conv_iter=      56 cpu clock= 1.12E-01

 tran: time= 4.2154E-09 tot_iter=     151 conv_iter=      62 cpu clock= 1.13E-01

 tran: time= 4.9262E-09 tot_iter=     157 conv_iter=      65 cpu clock= 1.13E-01

 tran: time= 5.5262E-09 tot_iter=     161 conv_iter=      67 cpu clock= 1.13E-01

 tran: time= 6.0000E-09 tot_iter=     165 conv_iter=      69 cpu clock= 1.13E-01

 sweep: tran tran0    end, cpu clock= 1.13E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     23:23:35 12/02/2025                               

           job ended   at     23:23:35 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
