

****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\y00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      13480 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.10E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.13E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.13E-01                                  

 init: end check errors, cpu clock= 1.16E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.16E-01                     

       establish matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.16E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.16E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.17E-01                                          

 dcop: end dcop, cpu clock= 1.19E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.20E-01 

 tran: time= 6.6344E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.21E-01

 tran: time= 1.2253E-09 tot_iter=      63 conv_iter=      26 cpu clock= 1.22E-01

 tran: time= 1.9813E-09 tot_iter=      82 conv_iter=      34 cpu clock= 1.22E-01

 tran: time= 2.4543E-09 tot_iter=      94 conv_iter=      38 cpu clock= 1.23E-01

 tran: time= 3.0767E-09 tot_iter=     115 conv_iter=      47 cpu clock= 1.23E-01

 tran: time= 3.6331E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.23E-01

 tran: time= 4.3176E-09 tot_iter=     133 conv_iter=      56 cpu clock= 1.24E-01

 tran: time= 4.8975E-09 tot_iter=     137 conv_iter=      58 cpu clock= 1.24E-01

 tran: time= 5.4975E-09 tot_iter=     141 conv_iter=      60 cpu clock= 1.24E-01

 tran: time= 6.0000E-09 tot_iter=     145 conv_iter=      62 cpu clock= 1.24E-01

 sweep: tran tran0    end, cpu clock= 1.24E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.14 seconds                           

           job started at     23:21:58 12/02/2025                               

           job ended   at     23:21:59 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\y00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21352 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.90E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.02E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.02E-01                                  

 init: end check errors, cpu clock= 1.04E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.04E-01                     

       establish matrix -- done, cpu clock= 1.04E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.05E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.05E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.05E-01                                          

 dcop: end dcop, cpu clock= 1.07E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.08E-01 

 tran: time= 6.6344E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.09E-01

 tran: time= 1.2253E-09 tot_iter=      63 conv_iter=      26 cpu clock= 1.10E-01

 tran: time= 1.9813E-09 tot_iter=      82 conv_iter=      34 cpu clock= 1.11E-01

 tran: time= 2.4543E-09 tot_iter=      94 conv_iter=      38 cpu clock= 1.11E-01

 tran: time= 3.0767E-09 tot_iter=     115 conv_iter=      47 cpu clock= 1.12E-01

 tran: time= 3.6331E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.12E-01

 tran: time= 4.3176E-09 tot_iter=     133 conv_iter=      56 cpu clock= 1.12E-01

 tran: time= 4.8975E-09 tot_iter=     137 conv_iter=      58 cpu clock= 1.12E-01

 tran: time= 5.4975E-09 tot_iter=     141 conv_iter=      60 cpu clock= 1.12E-01

 tran: time= 6.0000E-09 tot_iter=     145 conv_iter=      62 cpu clock= 1.12E-01

 sweep: tran tran0    end, cpu clock= 1.12E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     23:22:02 12/02/2025                               

           job ended   at     23:22:02 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\y00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      21296 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 1.80E-01                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.83E-01 peak memory=      72 mb      

 init: begin check errors, cpu clock= 1.83E-01                                  

 init: end check errors, cpu clock= 1.85E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.85E-01                     

       establish matrix -- done, cpu clock= 1.85E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.86E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.86E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.86E-01                                          

 dcop: end dcop, cpu clock= 1.88E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.89E-01 

 tran: time= 6.6344E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.90E-01

 tran: time= 1.2253E-09 tot_iter=      63 conv_iter=      26 cpu clock= 1.92E-01

 tran: time= 1.9813E-09 tot_iter=      82 conv_iter=      34 cpu clock= 1.93E-01

 tran: time= 2.4543E-09 tot_iter=      94 conv_iter=      38 cpu clock= 1.93E-01

 tran: time= 3.0767E-09 tot_iter=     115 conv_iter=      47 cpu clock= 1.94E-01

 tran: time= 3.6331E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.95E-01

 tran: time= 4.3176E-09 tot_iter=     133 conv_iter=      56 cpu clock= 1.95E-01

 tran: time= 4.8975E-09 tot_iter=     137 conv_iter=      58 cpu clock= 1.96E-01

 tran: time= 5.4975E-09 tot_iter=     141 conv_iter=      60 cpu clock= 1.96E-01

 tran: time= 6.0000E-09 tot_iter=     145 conv_iter=      62 cpu clock= 1.96E-01

 sweep: tran tran0    end, cpu clock= 1.96E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.05 seconds                               

           total elapsed time            0.22 seconds                           

           job started at     23:23:44 12/02/2025                               

           job ended   at     23:23:44 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 


****** PrimeSim HSPICE -- T-2022.06 win64 (May 20 2022 7637141) ******          

 Input File: C:\Users\sh3qm\PycharmProjects\s2ibispy_new\tests\io_buf\y00out.spi

 lic:  

 lic: FLEXlm: SDK_12.10 

 lic: USER:   sh3qm                HOSTNAME: rd78ece-emclab 

 lic: HOSTID: 00ff89f5aa52         PID:      7960 

 lic: Using FLEXlm license file: 

 lic: 1704@synopsys.lic.mst.edu 

 lic: Checkout 1 hspice 

 lic: License/Maintenance for hspice will expire on 04-may-2026/2025.06 

 lic: 1(in_use)/50(total) FLOATING license(s) on SERVER 1704@synopsys.lic.mst.ed

 lic:   

 init: begin read circuit files, cpu clock= 9.70E-02                            

       option search = C:/synopsys/Hspice_T-2022.06/parts/behave/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/AD/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/XILINX/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/TLINE/                

       option search = C:/synopsys/Hspice_T-2022.06/parts/TI/                   

       option search = C:/synopsys/Hspice_T-2022.06/parts/SIGNET/               

       option search = C:/synopsys/Hspice_T-2022.06/parts/PCI/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/LIN_TECH/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/PET/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/DI0/                  

       option search = C:/synopsys/Hspice_T-2022.06/parts/COMLINE/              

       option search = C:/synopsys/Hspice_T-2022.06/parts/BURR_BRM/             

       option search = C:/synopsys/Hspice_T-2022.06/parts/BJT/                  

       option ingold =     2.00                                                 

 init: end read circuit files, cpu clock= 1.00E-01 peak memory=      71 mb      

 init: begin check errors, cpu clock= 1.00E-01                                  

 init: end check errors, cpu clock= 1.02E-01 peak memory=      72 mb            

 init: begin setup matrix, pivot=     0 cpu clock= 1.02E-01                     

       establish matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb    

       re-order matrix -- done, cpu clock= 1.03E-01 peak memory=      72 mb     

 init: end setup matrix, cpu clock= 1.03E-01 peak memory=      72 mb            

 dcop: begin dcop, cpu clock= 1.03E-01                                          

 dcop: end dcop, cpu clock= 1.05E-01 peak memory=      72 mb tot_iter=      20  

 sweep: tran tran0    begin, stop_t=  6.00E-09 #sweeps=6001 cpu clock= 1.06E-01 

 tran: time= 6.6344E-10 tot_iter=      28 conv_iter=      12 cpu clock= 1.07E-01

 tran: time= 1.2253E-09 tot_iter=      63 conv_iter=      26 cpu clock= 1.08E-01

 tran: time= 1.9813E-09 tot_iter=      82 conv_iter=      34 cpu clock= 1.08E-01

 tran: time= 2.4543E-09 tot_iter=      94 conv_iter=      38 cpu clock= 1.09E-01

 tran: time= 3.0767E-09 tot_iter=     115 conv_iter=      47 cpu clock= 1.09E-01

 tran: time= 3.6331E-09 tot_iter=     125 conv_iter=      52 cpu clock= 1.10E-01

 tran: time= 4.3176E-09 tot_iter=     133 conv_iter=      56 cpu clock= 1.10E-01

 tran: time= 4.8975E-09 tot_iter=     137 conv_iter=      58 cpu clock= 1.10E-01

 tran: time= 5.4975E-09 tot_iter=     141 conv_iter=      60 cpu clock= 1.10E-01

 tran: time= 6.0000E-09 tot_iter=     145 conv_iter=      62 cpu clock= 1.10E-01

 sweep: tran tran0    end, cpu clock= 1.10E-01 peak memory=      72 mb          

>info:         ***** hspice job concluded                                       

           total cpu time            0.04 seconds                               

           total elapsed time            0.13 seconds                           

           job started at     23:23:50 12/02/2025                               

           job ended   at     23:23:50 12/02/2025                               
>info:         ***** hspice job concluded


 lic: Release hspice token(s) 
